server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /proxy/ {
        resolver 8.8.8.8;
        proxy_pass https://$http_host$request_uri;
        proxy_set_header Host $host;
        proxy_ssl_server_name on;
    }
}