export const s = {
    panel: {
        display: 'flex',
        flexDirection: 'column' as const,
        height: '100%',
        background: 'rgba(15,23,42,0.98)',
    },
    toolbar: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '8px 12px',
        borderBottom: '1px solid rgba(100,116,139,0.2)',
        flexWrap: 'wrap' as const,
    },
    btn: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(30,41,59,0.8)',
        color: 'var(--slate-300)',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnPrimary: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #3b82f6',
        background: 'var(--accent)',
        color: '#fff',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnDanger: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #ef4444',
        background: 'rgba(239,68,68,0.2)',
        color: 'var(--error)',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnSuccess: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #22c55e',
        background: 'rgba(34,197,94,0.15)',
        color: 'var(--success)',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    main: { display: 'flex', flex: 1, overflow: 'hidden' },
    palette: {
        width: 160,
        borderRight: '1px solid rgba(100,116,139,0.2)',
        padding: 8,
        overflowY: 'auto' as const,
        flexShrink: 0,
    },
    paletteTitle: {
        fontSize: 10,
        color: 'var(--slate-400)',
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        marginBottom: 6,
    },
    paletteItem: {
        padding: '6px 8px',
        borderRadius: 4,
        background: 'rgba(30,41,59,0.8)',
        border: '1px solid rgba(100,116,139,0.2)',
        marginBottom: 4,
        cursor: 'grab',
        fontSize: 11,
        color: 'var(--slate-300)',
        display: 'flex',
        alignItems: 'center',
        gap: 6,
    },
    paletteDot: (color: string) => ({
        width: 8,
        height: 8,
        borderRadius: '50%',
        background: color,
        flexShrink: 0,
    }),
    canvas: {
        flex: 1,
        padding: 8,
        overflowY: 'auto' as const,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 6,
    },
    canvasEmpty: {
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--slate-500)',
        fontSize: 13,
    },
    primitiveCard: (color: string, selected: boolean) => ({
        padding: '8px 10px',
        borderRadius: 6,
        border: selected ? `1px solid ${color}` : '1px solid rgba(100,116,139,0.25)',
        background: selected ? `rgba(${hexToRgb(color)},0.08)` : 'rgba(30,41,59,0.5)',
        cursor: 'pointer',
        transition: 'all 0.12s',
    }),
    primitiveHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    primitiveType: (color: string) => ({
        fontSize: 10,
        fontWeight: 600,
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        color,
    }),
    primitiveLabel: { fontSize: 12, color: 'var(--slate-200)' },
    inspector: {
        width: 300,
        borderLeft: '1px solid rgba(100,116,139,0.2)',
        padding: 8,
        overflowY: 'auto' as const,
        flexShrink: 0,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 6,
    },
    inspectorTitle: {
        fontSize: 10,
        color: 'var(--slate-400)',
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    preview: {
        width: 260,
        borderLeft: '1px solid rgba(100,116,139,0.2)',
        padding: 8,
        overflowY: 'auto' as const,
        flexShrink: 0,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 6,
    },
    previewTitle: {
        fontSize: 10,
        color: 'var(--slate-400)',
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    json: {
        fontFamily: 'monospace',
        fontSize: 9,
        color: 'var(--slate-400)',
        whiteSpace: 'pre-wrap' as const,
        wordBreak: 'break-all' as const,
        background: 'rgba(0,0,0,0.3)',
        padding: 8,
        borderRadius: 4,
        maxHeight: 300,
        overflowY: 'auto' as const,
    },
    fieldLabel: {
        fontSize: 10,
        color: 'var(--slate-400)',
        fontWeight: 600,
        marginBottom: 2,
        display: 'block',
    },
    input: {
        width: '100%',
        padding: '4px 6px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(0,0,0,0.3)',
        color: 'var(--slate-200)',
        fontSize: 11,
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    select: {
        width: '100%',
        padding: '4px 6px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(0,0,0,0.3)',
        color: 'var(--slate-200)',
        fontSize: 11,
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    agentRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        padding: '3px 4px',
        borderRadius: 4,
        background: 'rgba(255,255,255,0.03)',
        marginBottom: 2,
        fontSize: 10,
    },
    addBtn: {
        padding: '2px 6px',
        borderRadius: 3,
        border: '1px dashed rgba(100,116,139,0.3)',
        background: 'transparent',
        color: 'var(--slate-500)',
        cursor: 'pointer',
        fontSize: 10,
        width: '100%',
        textAlign: 'center' as const,
    },
    iconBtn: {
        background: 'transparent',
        border: 'none',
        color: 'var(--slate-500)',
        cursor: 'pointer',
        padding: 2,
        display: 'flex',
        alignItems: 'center',
        borderRadius: 3,
    },
    validBadge: (ok: boolean) => ({
        display: 'inline-flex',
        alignItems: 'center',
        gap: 3,
        padding: '2px 6px',
        borderRadius: 4,
        fontSize: 10,
        fontWeight: 600,
        background: ok ? 'rgba(34,197,94,0.15)' : 'rgba(239,68,68,0.15)',
        color: ok ? '#22c55e' : '#ef4444',
    }),
    sectionTitle: {
        fontSize: 10,
        color: 'var(--slate-500)',
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        fontWeight: 600,
        marginTop: 4,
        marginBottom: 2,
    },
    toast: {
        position: 'fixed' as const,
        bottom: 20,
        right: 20,
        padding: '8px 14px',
        borderRadius: 6,
        fontSize: 11,
        zIndex: 9999,
        color: '#fff',
    },
};

function hexToRgb(hex: string): string {
    const v = parseInt(hex.replace('#', ''), 16);
    return `${(v >> 16) & 255}, ${(v >> 8) & 255}, ${v & 255}`;
}
