export const s = {
    panel: {
        display: 'flex',
        flexDirection: 'column' as const,
        height: '100%',
        background: 'rgba(15,23,42,0.98)',
    },
    toolbar: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '8px 12px',
        borderBottom: '1px solid rgba(100,116,139,0.2)',
        flexWrap: 'wrap' as const,
    },
    btn: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(30,41,59,0.8)',
        color: '#cbd5e1',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnPrimary: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #3b82f6',
        background: '#3b82f6',
        color: '#fff',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnDanger: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #ef4444',
        background: 'rgba(239,68,68,0.2)',
        color: '#ef4444',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    btnSuccess: {
        padding: '4px 10px',
        borderRadius: 4,
        border: '1px solid #22c55e',
        background: 'rgba(34,197,94,0.15)',
        color: '#22c55e',
        cursor: 'pointer',
        fontSize: 11,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    main: { display: 'flex', flex: 1, overflow: 'hidden' },
    ruleList: {
        width: 320,
        borderRight: '1px solid rgba(100,116,139,0.2)',
        padding: 8,
        overflowY: 'auto' as const,
        flexShrink: 0,
    },
    ruleCard: (enabled: boolean, selected: boolean) => ({
        padding: '8px 10px',
        borderRadius: 6,
        border: selected ? '1px solid #3b82f6' : '1px solid rgba(100,116,139,0.2)',
        background: selected ? 'rgba(59,130,246,0.08)' : 'rgba(30,41,59,0.5)',
        marginBottom: 4,
        cursor: 'pointer',
        opacity: enabled ? 1 : 0.5,
    }),
    editor: {
        flex: 1,
        padding: 8,
        overflowY: 'auto' as const,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 8,
    },
    preview: {
        width: 280,
        borderLeft: '1px solid rgba(100,116,139,0.2)',
        padding: 8,
        overflowY: 'auto' as const,
        flexShrink: 0,
    },
    fieldLabel: {
        fontSize: 10,
        color: '#94a3b8',
        fontWeight: 600,
        marginBottom: 2,
        display: 'block',
    },
    input: {
        width: '100%',
        padding: '4px 6px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(0,0,0,0.3)',
        color: '#e2e8f0',
        fontSize: 11,
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    select: {
        width: '100%',
        padding: '4px 6px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.3)',
        background: 'rgba(0,0,0,0.3)',
        color: '#e2e8f0',
        fontSize: 11,
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    sectionTitle: {
        fontSize: 10,
        color: '#64748b',
        textTransform: 'uppercase' as const,
        letterSpacing: 0.5,
        fontWeight: 600,
        marginTop: 6,
        marginBottom: 4,
    },
    badge: (color: string) => ({
        display: 'inline-flex',
        alignItems: 'center',
        gap: 3,
        padding: '2px 6px',
        borderRadius: 4,
        fontSize: 9,
        fontWeight: 600,
        background: `${color}15`,
        color,
    }),
    conditionBlock: {
        padding: '6px 8px',
        borderRadius: 4,
        border: '1px solid rgba(100,116,139,0.2)',
        background: 'rgba(0,0,0,0.15)',
        marginBottom: 4,
    },
    actionRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        padding: '4px 6px',
        borderRadius: 4,
        background: 'rgba(255,255,255,0.02)',
        marginBottom: 2,
        fontSize: 10,
    },
    addBtn: {
        padding: '2px 6px',
        borderRadius: 3,
        border: '1px dashed rgba(100,116,139,0.3)',
        background: 'transparent',
        color: '#64748b',
        cursor: 'pointer',
        fontSize: 10,
        width: '100%',
        textAlign: 'center' as const,
        marginTop: 2,
    },
    iconBtn: {
        background: 'transparent',
        border: 'none',
        color: '#64748b',
        cursor: 'pointer',
        padding: 2,
        display: 'flex',
        alignItems: 'center',
        borderRadius: 3,
    },
    toast: {
        position: 'fixed' as const,
        bottom: 20,
        right: 20,
        padding: '8px 14px',
        borderRadius: 6,
        fontSize: 11,
        zIndex: 9999,
        color: '#fff',
    },
    row: { display: 'flex', gap: 4, alignItems: 'center', flexWrap: 'wrap' as const },
};
