import type { Achievement } from '../contracts/ecosystem';

export const ACHIEVEMENTS: Achievement[] = [
    // ── First Steps (10) ──
    {
        id: 'first_key',
        title: 'First Key',
        description: 'Add your first API key',
        category: 'first_steps',
        icon: '🔑',
        condition: 'keys_added >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_probe',
        title: 'First Contact',
        description: 'Successfully probe a key',
        category: 'first_steps',
        icon: '📡',
        condition: 'probes_done >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_chat',
        title: 'First Words',
        description: 'Send your first chat message',
        category: 'first_steps',
        icon: '💬',
        condition: 'chats_done >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_debate',
        title: 'First Debate',
        description: 'Complete your first debate session',
        category: 'first_steps',
        icon: '🎤',
        condition: 'debates_done >= 1',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'first_memory',
        title: 'First Memory',
        description: 'Store your first memory',
        category: 'first_steps',
        icon: '🧠',
        condition: 'memories_stored >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_error',
        title: 'Baptism by Fire',
        description: 'Handle your first error gracefully',
        category: 'first_steps',
        icon: '🔥',
        condition: 'errors_handled >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_role',
        title: 'Role Call',
        description: 'Create your first role',
        category: 'first_steps',
        icon: '🎭',
        condition: 'roles_created >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_group',
        title: 'Team Player',
        description: 'Join or create a group',
        category: 'first_steps',
        icon: '👥',
        condition: 'groups_joined >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_export',
        title: 'Archivist',
        description: 'Export your first dataset',
        category: 'first_steps',
        icon: '📦',
        condition: 'exports_done >= 1',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'first_template',
        title: 'Pattern Seeker',
        description: 'Save your first template',
        category: 'first_steps',
        icon: '📋',
        condition: 'templates_saved >= 1',
        points: 10,
        isUnlocked: false,
    },

    // ── Provider Mastery (15) ──
    {
        id: 'two_providers',
        title: 'Dual Wielder',
        description: 'Add keys from 2 different providers',
        category: 'provider_mastery',
        icon: '⚡',
        condition: 'providers_active >= 2',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'all_providers',
        title: 'Collector',
        description: 'Add keys from all 6 providers',
        category: 'provider_mastery',
        icon: '🏛️',
        condition: 'providers_active >= 6',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'key_hoarder',
        title: 'Key Hoarder',
        description: 'Add 20 API keys total',
        category: 'provider_mastery',
        icon: '🗝️',
        condition: 'keys_added >= 20',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'key_tycoon',
        title: 'Key Tycoon',
        description: 'Add 50 API keys total',
        category: 'provider_mastery',
        icon: '👑',
        condition: 'keys_added >= 50',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'probe_master',
        title: 'Probe Master',
        description: 'Run 100 probes',
        category: 'provider_mastery',
        icon: '📡',
        condition: 'probes_done >= 100',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'uptime_hero',
        title: 'Uptime Hero',
        description: 'Maintain 100% uptime for 7 days',
        category: 'provider_mastery',
        icon: '💪',
        condition: 'uptime_days >= 7',
        points: 40,
        isUnlocked: false,
    },
    {
        id: 'circuit_breaker',
        title: 'Circuit Breaker',
        description: 'Survive 10 circuit breaker opens',
        category: 'provider_mastery',
        icon: '🔌',
        condition: 'circuit_breaks >= 10',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'rate_limit_survivor',
        title: 'Rate Limit Survivor',
        description: 'Handle 50 rate limit errors',
        category: 'provider_mastery',
        icon: '🚦',
        condition: 'rate_limits >= 50',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'pool_party',
        title: 'Pool Party',
        description: 'Create 5 key pools',
        category: 'provider_mastery',
        icon: '🏊',
        condition: 'pools_created >= 5',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'pool_master',
        title: 'Pool Master',
        description: 'Create 15 key pools',
        category: 'provider_mastery',
        icon: '🏆',
        condition: 'pools_created >= 15',
        points: 40,
        isUnlocked: false,
    },
    {
        id: 'group_builder',
        title: 'Group Builder',
        description: 'Create 10 key groups',
        category: 'provider_mastery',
        icon: '🏗️',
        condition: 'groups_created >= 10',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'rotator',
        title: 'Rotator',
        description: 'Set up key rotation',
        category: 'provider_mastery',
        icon: '🔄',
        condition: 'rotation_setup >= 1',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'budget_watcher',
        title: 'Budget Watcher',
        description: 'Set budget limits for 3 providers',
        category: 'provider_mastery',
        icon: '💰',
        condition: 'budgets_set >= 3',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'thousand_calls',
        title: 'Thousand Cuts',
        description: 'Make 1000 successful API calls',
        category: 'provider_mastery',
        icon: '📞',
        condition: 'api_calls >= 1000',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'ten_thousand',
        title: 'Ten Thousand',
        description: 'Make 10000 successful API calls',
        category: 'provider_mastery',
        icon: '🎯',
        condition: 'api_calls >= 10000',
        points: 60,
        isUnlocked: false,
    },

    // ── Debate Champion (15) ──
    {
        id: 'debate_winner',
        title: 'First Victory',
        description: 'Win your first debate',
        category: 'debate_champion',
        icon: '🏅',
        condition: 'debates_won >= 1',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'debate_streak_3',
        title: 'Hat Trick',
        description: 'Win 3 debates in a row',
        category: 'debate_champion',
        icon: '🎩',
        condition: 'debate_streak >= 3',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'debate_streak_5',
        title: 'Champion',
        description: 'Win 5 debates in a row',
        category: 'debate_champion',
        icon: '🏆',
        condition: 'debate_streak >= 5',
        points: 40,
        isUnlocked: false,
    },
    {
        id: 'debate_master',
        title: 'Debate Master',
        description: 'Win 20 debates total',
        category: 'debate_champion',
        icon: '👑',
        condition: 'debates_won >= 20',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'strategy_explorer',
        title: 'Strategist',
        description: 'Use 5 different debate strategies',
        category: 'debate_champion',
        icon: '🧠',
        condition: 'strategies_used >= 5',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'strategy_collector',
        title: 'Tactician',
        description: 'Use all 6 base debate strategies',
        category: 'debate_champion',
        icon: '📚',
        condition: 'strategies_used >= 6',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'agent_army',
        title: 'Agent Army',
        description: 'Debate with 10+ agents at once',
        category: 'debate_champion',
        icon: '🤖',
        condition: 'max_agents_debate >= 10',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'full_house',
        title: 'Full House',
        description: 'Debate with all 22 agents',
        category: 'debate_champion',
        icon: '🎪',
        condition: 'max_agents_debate >= 22',
        points: 60,
        isUnlocked: false,
    },
    {
        id: 'arena_explorer',
        title: 'Arena Explorer',
        description: 'Use 5 different arena layouts',
        category: 'debate_champion',
        icon: '🎭',
        condition: 'layouts_used >= 5',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'layout_collector',
        title: 'Layout Collector',
        description: 'Use all 10 arena layouts',
        category: 'debate_champion',
        icon: '🌟',
        condition: 'layouts_used >= 10',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'tournament_winner',
        title: 'Tournament Champion',
        description: 'Win a debate tournament',
        category: 'debate_champion',
        icon: '🏆',
        condition: 'tournaments_won >= 1',
        points: 40,
        isUnlocked: false,
    },
    {
        id: 'consensus_builder',
        title: 'Consensus Builder',
        description: 'Reach consensus in 5 debates',
        category: 'debate_champion',
        icon: '🤝',
        condition: 'consensus_reached >= 5',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'debate_historian',
        title: 'Historian',
        description: 'Complete 50 debate sessions',
        category: 'debate_champion',
        icon: '📜',
        condition: 'debates_done >= 50',
        points: 45,
        isUnlocked: false,
    },
    {
        id: 'comeback_king',
        title: 'Comeback King',
        description: 'Come back from 3 rounds behind to win',
        category: 'debate_champion',
        icon: '👑',
        condition: 'comebacks >= 1',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'peacemaker',
        title: 'Peacemaker',
        description: 'Resolve a debate without escalation',
        category: 'debate_champion',
        icon: '🕊️',
        condition: 'peaceful_resolutions >= 1',
        points: 20,
        isUnlocked: false,
    },

    // ── Memory Keeper (10) ──
    {
        id: 'memory_hoarder',
        title: 'Memory Hoarder',
        description: 'Store 100 memories',
        category: 'memory_keeper',
        icon: '🧠',
        condition: 'memories_stored >= 100',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'memory_master',
        title: 'Memory Master',
        description: 'Store 1000 memories',
        category: 'memory_keeper',
        icon: '💎',
        condition: 'memories_stored >= 1000',
        points: 45,
        isUnlocked: false,
    },
    {
        id: 'consolidator',
        title: 'Consolidator',
        description: 'Run 10 memory consolidations',
        category: 'memory_keeper',
        icon: '🔄',
        condition: 'consolidations >= 10',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'palace_builder',
        title: 'Palace Builder',
        description: 'Build a memory palace with 5 rooms',
        category: 'memory_keeper',
        icon: '🏰',
        condition: 'palace_rooms >= 5',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'forgetful',
        title: 'Forgetful',
        description: 'Let 10 memories decay naturally',
        category: 'memory_keeper',
        icon: '🌊',
        condition: 'memories_decayed >= 10',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'emotional',
        title: 'Emotional',
        description: 'Tag 20 memories with emotions',
        category: 'memory_keeper',
        icon: '❤️',
        condition: 'emotions_tagged >= 20',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'searcher',
        title: 'Memory Searcher',
        description: 'Use memory search 50 times',
        category: 'memory_keeper',
        icon: '🔍',
        condition: 'memory_searches >= 50',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'time_traveler',
        title: 'Time Traveler',
        description: 'Restore from a memory snapshot',
        category: 'memory_keeper',
        icon: '⏰',
        condition: 'snapshots_restored >= 1',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'knowledge_graph',
        title: 'Knowledge Weaver',
        description: 'Create 100 semantic connections',
        category: 'memory_keeper',
        icon: '🕸️',
        condition: 'semantic_links >= 100',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'memory_king',
        title: 'Memory King',
        description: 'Store memories across all 7 stores',
        category: 'memory_keeper',
        icon: '👑',
        condition: 'stores_active >= 7',
        points: 50,
        isUnlocked: false,
    },

    // ── Collector (15) ──
    {
        id: 'five_creatures',
        title: 'Collector',
        description: 'Unlock 5 creatures',
        category: 'collector',
        icon: '🐠',
        condition: 'creatures_unlocked >= 5',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'ten_creatures',
        title: 'Aquarist',
        description: 'Unlock 10 creatures',
        category: 'collector',
        icon: '🐟',
        condition: 'creatures_unlocked >= 10',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'twenty_creatures',
        title: 'Zookeeper',
        description: 'Unlock 20 creatures',
        category: 'collector',
        icon: '🐡',
        condition: 'creatures_unlocked >= 20',
        points: 40,
        isUnlocked: false,
    },
    {
        id: 'thirty_creatures',
        title: 'Menagerie',
        description: 'Unlock 30 creatures',
        category: 'collector',
        icon: '🐋',
        condition: 'creatures_unlocked >= 30',
        points: 60,
        isUnlocked: false,
    },
    {
        id: 'all_creatures',
        title: 'Living Museum',
        description: 'Unlock all 52 creatures',
        category: 'collector',
        icon: '🏛️',
        condition: 'creatures_unlocked >= 52',
        points: 100,
        isUnlocked: false,
    },
    {
        id: 'rare_collector',
        title: 'Rare Specimen',
        description: 'Unlock 5 rare creatures',
        category: 'collector',
        icon: '💎',
        condition: 'rare_unlocked >= 5',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'epic_collector',
        title: 'Epic Collection',
        description: 'Unlock 3 epic creatures',
        category: 'collector',
        icon: '🌟',
        condition: 'epic_unlocked >= 3',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'legendary_found',
        title: 'Legendary Discovery',
        description: 'Unlock 1 legendary creature',
        category: 'collector',
        icon: '👑',
        condition: 'legendary_unlocked >= 1',
        points: 80,
        isUnlocked: false,
    },
    {
        id: 'all_legendary',
        title: 'Mythic',
        description: 'Unlock all legendary creatures',
        category: 'collector',
        icon: '🏆',
        condition: 'legendary_unlocked >= 4',
        points: 150,
        isUnlocked: false,
    },
    {
        id: 'five_themes',
        title: 'Explorer',
        description: 'Unlock 5 aquarium themes',
        category: 'collector',
        icon: '🗺️',
        condition: 'themes_unlocked >= 5',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'ten_themes',
        title: 'World Traveler',
        description: 'Unlock 10 aquarium themes',
        category: 'collector',
        icon: '🌍',
        condition: 'themes_unlocked >= 10',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'fifteen_themes',
        title: 'Dimension Hopper',
        description: 'Unlock 15 aquarium themes',
        category: 'collector',
        icon: '🌌',
        condition: 'themes_unlocked >= 15',
        points: 55,
        isUnlocked: false,
    },
    {
        id: 'twenty_themes',
        title: 'Omni-Voyager',
        description: 'Unlock 20 aquarium themes',
        category: 'collector',
        icon: '🚀',
        condition: 'themes_unlocked >= 20',
        points: 80,
        isUnlocked: false,
    },
    {
        id: 'all_themes',
        title: 'Grand Master',
        description: 'Unlock all aquarium themes',
        category: 'collector',
        icon: '🏅',
        condition: 'themes_unlocked >= 25',
        points: 120,
        isUnlocked: false,
    },
    {
        id: 'completionist',
        title: 'Completionist',
        description: 'Unlock all creatures AND all themes',
        category: 'collector',
        icon: '🎯',
        condition: 'all_creatures_and_themes >= 1',
        points: 200,
        isUnlocked: false,
    },

    // ── Streak (5) ──
    {
        id: 'streak_7',
        title: 'Week Warrior',
        description: '7-day activity streak',
        category: 'streak',
        icon: '📅',
        condition: 'streak_days >= 7',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'streak_14',
        title: 'Fortnight',
        description: '14-day activity streak',
        category: 'streak',
        icon: '🔥',
        condition: 'streak_days >= 14',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'streak_30',
        title: 'Monthly Master',
        description: '30-day activity streak',
        category: 'streak',
        icon: '💪',
        condition: 'streak_days >= 30',
        points: 60,
        isUnlocked: false,
    },
    {
        id: 'streak_60',
        title: 'Two Months Strong',
        description: '60-day activity streak',
        category: 'streak',
        icon: '🏆',
        condition: 'streak_days >= 60',
        points: 100,
        isUnlocked: false,
    },
    {
        id: 'streak_100',
        title: 'Century',
        description: '100-day activity streak',
        category: 'streak',
        icon: '👑',
        condition: 'streak_days >= 100',
        points: 200,
        isUnlocked: false,
    },

    // ── Hidden (15) ──
    {
        id: 'hidden_midnight',
        title: 'Night Owl',
        description: 'Use the system at midnight',
        category: 'hidden',
        icon: '🦉',
        condition: 'hidden_midnight',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'hidden_404',
        title: 'Lost Explorer',
        description: 'Visit the 404 page',
        category: 'hidden',
        icon: '🧭',
        condition: 'hidden_404',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'hidden_escape',
        title: 'Houdini',
        description: 'Escape from a stuck state',
        category: 'hidden',
        icon: '🔓',
        condition: 'hidden_escape',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'hidden_theme',
        title: 'Theme Hopper',
        description: 'Switch themes 10 times in one session',
        category: 'hidden',
        icon: '🎨',
        condition: 'hidden_theme_hopper',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'hidden_keysmash',
        title: 'Keyboard Warrior',
        description: 'Type 1000 characters in a single prompt',
        category: 'hidden',
        icon: '⌨️',
        condition: 'hidden_keysmash',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'hidden_easter_egg',
        title: 'Egg Hunter',
        description: 'Find a secret easter egg',
        category: 'hidden',
        icon: '🥚',
        condition: 'hidden_easter_egg',
        points: 50,
        isUnlocked: false,
    },
    {
        id: 'hidden_masochist',
        title: 'Debugger',
        description: 'Open the debug panel 100 times',
        category: 'hidden',
        icon: '🐛',
        condition: 'hidden_debugger',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'hidden_hoarder',
        title: 'Data Hoarder',
        description: 'Have 1MB of stored data',
        category: 'hidden',
        icon: '💾',
        condition: 'hidden_hoarder',
        points: 30,
        isUnlocked: false,
    },
    {
        id: 'hidden_clicker',
        title: 'Button Masher',
        description: 'Click 1000 buttons',
        category: 'hidden',
        icon: '🖱️',
        condition: 'hidden_clicker',
        points: 15,
        isUnlocked: false,
    },
    {
        id: 'hidden_scroll',
        title: 'Infinite Scroll',
        description: 'Scroll 10000px in one panel',
        category: 'hidden',
        icon: '📜',
        condition: 'hidden_scroll',
        points: 10,
        isUnlocked: false,
    },
    {
        id: 'hidden_menu',
        title: 'Menu Explorer',
        description: 'Open every single nav section',
        category: 'hidden',
        icon: '🧭',
        condition: 'hidden_menu',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'hidden_zen',
        title: 'Zen Mode',
        description: 'Idle for 30 minutes straight',
        category: 'hidden',
        icon: '🧘',
        condition: 'hidden_zen',
        points: 20,
        isUnlocked: false,
    },
    {
        id: 'hidden_speed',
        title: 'Speed Demon',
        description: 'Send 10 messages in 1 minute',
        category: 'hidden',
        icon: '⚡',
        condition: 'hidden_speed',
        points: 25,
        isUnlocked: false,
    },
    {
        id: 'hidden_hat_trick',
        title: 'Triple Threat',
        description: 'Win 3 debates on the same topic',
        category: 'hidden',
        icon: '🎩',
        condition: 'hidden_hat_trick',
        points: 35,
        isUnlocked: false,
    },
    {
        id: 'hidden_omniscient',
        title: 'Omniscient',
        description: 'Use all features at least once',
        category: 'hidden',
        icon: '🧿',
        condition: 'hidden_omniscient',
        points: 100,
        isUnlocked: false,
    },
];

export function getAchievementsByCategory(category: string): Achievement[] {
    return ACHIEVEMENTS.filter((a) => a.category === category);
}

export function getUnlockedAchievements(): Achievement[] {
    return ACHIEVEMENTS.filter((a) => a.isUnlocked);
}
