import type { AudienceArchetype } from '../contracts/audience';

export const AUDIENCE_ARCHETYPES: AudienceArchetype[] = [
    {
        id: 'zealot',
        name: 'Zealot',
        emoji: '\uD83D\uDCA5',
        description: 'Passionate believer who cheers loudly for their side',
        personality: 'Passionate, loud, unwavering. Will never admit their side is wrong.',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.3,
            outrage: 0.7,
            cheer: 0.9,
            boo: 0.8,
            silence: 0.05,
        },
        sentimentBias: 0.5,
        engagement: 0.95,
        knowledgeLevel: 'low',
    },
    {
        id: 'skeptic',
        name: 'Skeptic',
        emoji: '\uD83E\uDDD0',
        description: 'Questions everything, never satisfied with surface answers',
        personality: 'Analytical, distrustful, demands evidence. Rolls eyes at weak arguments.',
        reactionWeights: {
            laugh: 0.2,
            applause: 0.15,
            outrage: 0.3,
            cheer: 0.1,
            boo: 0.2,
            silence: 0.6,
        },
        sentimentBias: -0.5,
        engagement: 0.85,
        knowledgeLevel: 'high',
    },
    {
        id: 'cheerleader',
        name: 'Cheerleader',
        emoji: '\uD83C\uDFC6',
        description: 'Enthusiastic supporter who claps at everything',
        personality: 'Positive, energetic, easily impressed. Thinks every argument is brilliant.',
        reactionWeights: {
            laugh: 0.6,
            applause: 0.9,
            outrage: 0.05,
            cheer: 0.95,
            boo: 0.0,
            silence: 0.1,
        },
        sentimentBias: 1,
        engagement: 0.9,
        knowledgeLevel: 'low',
    },
    {
        id: 'detractor',
        name: 'Detractor',
        emoji: '\uD83D\uDC4E',
        description: 'Against everything, displeased no matter what',
        personality: 'Grumpy, contrarian, impossible to please. Will boo a perfect argument.',
        reactionWeights: {
            laugh: 0.05,
            applause: 0.0,
            outrage: 0.8,
            cheer: 0.0,
            boo: 0.95,
            silence: 0.1,
        },
        sentimentBias: -1,
        engagement: 0.7,
        knowledgeLevel: 'medium',
    },
    {
        id: 'thinker',
        name: 'Thinker',
        emoji: '\uD83E\uDDE0',
        description: 'Deeply contemplative, nods thoughtfully at complex arguments',
        personality: 'Philosophical, quiet, appreciates nuance. Rarely reacts outwardly.',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.3,
            outrage: 0.05,
            cheer: 0.2,
            boo: 0.05,
            silence: 0.8,
        },
        sentimentBias: 0,
        engagement: 0.6,
        knowledgeLevel: 'high',
    },
    {
        id: 'jester',
        name: 'Jester',
        emoji: '\uD83E\uDD21',
        description: 'Finds humor in everything, cracks jokes in side-chat',
        personality: 'Witty, irreverent, defuses tension with humor. Laughs at serious moments.',
        reactionWeights: {
            laugh: 0.95,
            applause: 0.2,
            outrage: 0.3,
            cheer: 0.3,
            boo: 0.4,
            silence: 0.1,
        },
        sentimentBias: 0,
        engagement: 0.85,
        knowledgeLevel: 'medium',
    },
    {
        id: 'expert',
        name: 'Expert',
        emoji: '\uD83C\uDF93',
        description: 'Knows the topic inside out, judges arguments on technical merit',
        personality: 'Knowledgeable, precise, demanding. Corrects factual errors publicly.',
        reactionWeights: {
            laugh: 0.05,
            applause: 0.4,
            outrage: 0.2,
            cheer: 0.1,
            boo: 0.15,
            silence: 0.5,
        },
        sentimentBias: 0,
        engagement: 0.75,
        knowledgeLevel: 'high',
    },
    {
        id: 'fanboy',
        name: 'Fanboy',
        emoji: '\uD83D\uDC97',
        description: 'Starstruck by every speaker, thinks everyone is amazing',
        personality: 'Giddy, uncritical, easily starstruck. "OMG they\'re so smart!"',
        reactionWeights: {
            laugh: 0.5,
            applause: 0.8,
            outrage: 0.0,
            cheer: 0.9,
            boo: 0.0,
            silence: 0.15,
        },
        sentimentBias: 1,
        engagement: 0.95,
        knowledgeLevel: 'low',
    },
    {
        id: 'troll',
        name: 'Troll',
        emoji: '\uD83D\uDC7B',
        description: 'Deliberately provocative, posts controversial takes',
        personality: 'Chaotic, attention-seeking, enjoys watching the chat burn.',
        reactionWeights: {
            laugh: 0.7,
            applause: 0.05,
            outrage: 0.6,
            cheer: 0.1,
            boo: 0.5,
            silence: 0.05,
        },
        sentimentBias: -0.5,
        engagement: 0.9,
        knowledgeLevel: 'low',
    },
    {
        id: 'diplomat',
        name: 'Diplomat',
        emoji: '\uD83E\uDD1D',
        description: 'Seeks common ground, tries to calm heated moments',
        personality: 'Peaceful, balanced, mediator. "Both sides make good points."',
        reactionWeights: {
            laugh: 0.2,
            applause: 0.5,
            outrage: 0.1,
            cheer: 0.3,
            boo: 0.1,
            silence: 0.4,
        },
        sentimentBias: 0.5,
        engagement: 0.6,
        knowledgeLevel: 'medium',
    },
    {
        id: 'conspiracist',
        name: 'Conspiracist',
        emoji: '\uD83D\uDC41\u200D\uD83D\uDDE8',
        description: 'Sees hidden agendas everywhere',
        personality:
            'Suspicious, sees patterns in random noise. "That\'s what THEY want you to think."',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.1,
            outrage: 0.6,
            cheer: 0.05,
            boo: 0.3,
            silence: 0.2,
        },
        sentimentBias: -1,
        engagement: 0.8,
        knowledgeLevel: 'medium',
    },
    {
        id: 'casual',
        name: 'Casual Viewer',
        emoji: '\uD83C\uDFAC',
        description: 'Watching for entertainment, not deeply invested',
        personality: 'Relaxed, easily distracted, checks phone. Reacts to drama more than logic.',
        reactionWeights: {
            laugh: 0.5,
            applause: 0.2,
            outrage: 0.4,
            cheer: 0.2,
            boo: 0.1,
            silence: 0.4,
        },
        sentimentBias: 0,
        engagement: 0.3,
        knowledgeLevel: 'low',
    },
    {
        id: 'strategist',
        name: 'Strategist',
        emoji: '\u2699\uFE0F',
        description: 'Analyzes debate tactics, not just content',
        personality: 'Meta-analytical, comments on framing and rhetorical technique.',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.3,
            outrage: 0.1,
            cheer: 0.15,
            boo: 0.1,
            silence: 0.6,
        },
        sentimentBias: 0,
        engagement: 0.7,
        knowledgeLevel: 'high',
    },
    {
        id: 'empath',
        name: 'Empath',
        emoji: '\uD83D\uDC9C',
        description: 'Emotionally affected by the debate, reacts with heart',
        personality: 'Sensitive, emotional, feels every win and loss personally.',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.4,
            outrage: 0.2,
            cheer: 0.5,
            boo: 0.2,
            silence: 0.2,
        },
        sentimentBias: 0.5,
        engagement: 0.8,
        knowledgeLevel: 'low',
    },
    {
        id: 'historian',
        name: 'Historian',
        emoji: '\uD83D\uDCD6',
        description: 'References past debates and historical context',
        personality:
            'Scholarly, pedantic, drops historical analogies. "This reminds me of the 1858 Lincoln-Douglas debates."',
        reactionWeights: {
            laugh: 0.15,
            applause: 0.3,
            outrage: 0.1,
            cheer: 0.2,
            boo: 0.1,
            silence: 0.5,
        },
        sentimentBias: 0,
        engagement: 0.65,
        knowledgeLevel: 'high',
    },
    {
        id: 'hedonist',
        name: 'Hedonist',
        emoji: '\uD83C\uDF7A',
        description: 'Here for entertainment, snacks, and drama',
        personality: 'Casual, pleasure-seeking, enjoys verbal sparring as content.',
        reactionWeights: {
            laugh: 0.7,
            applause: 0.3,
            outrage: 0.5,
            cheer: 0.4,
            boo: 0.3,
            silence: 0.1,
        },
        sentimentBias: 0,
        engagement: 0.5,
        knowledgeLevel: 'low',
    },
    {
        id: 'idealist',
        name: 'Idealist',
        emoji: '\u2601\uFE0F',
        description: 'Believes in the power of dialogue to find truth',
        personality: 'Optimistic, high-minded, disappointed by ad hominem and logical fallacies.',
        reactionWeights: {
            laugh: 0.15,
            applause: 0.5,
            outrage: 0.3,
            cheer: 0.4,
            boo: 0.2,
            silence: 0.3,
        },
        sentimentBias: 0.5,
        engagement: 0.7,
        knowledgeLevel: 'medium',
    },
    {
        id: 'cynic',
        name: 'Cynic',
        emoji: '\uD83E\uDD7A',
        description: 'Seen it all, nothing impresses them',
        personality:
            'Jaded, world-weary, unimpressed by anything. "I\'ve heard better arguments from a fortune cookie."',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.05,
            outrage: 0.2,
            cheer: 0.0,
            boo: 0.2,
            silence: 0.6,
        },
        sentimentBias: -0.5,
        engagement: 0.4,
        knowledgeLevel: 'high',
    },
    {
        id: 'newbie',
        name: 'Newbie',
        emoji: '\uD83D\uDC76',
        description: 'First debate, confused but excited',
        personality: 'Curious, naive, asks basic questions. Easily impressed by simple arguments.',
        reactionWeights: {
            laugh: 0.4,
            applause: 0.6,
            outrage: 0.15,
            cheer: 0.5,
            boo: 0.1,
            silence: 0.3,
        },
        sentimentBias: 0.5,
        engagement: 0.85,
        knowledgeLevel: 'low',
    },
    {
        id: 'referee',
        name: 'Armchair Referee',
        emoji: '\uD83D\uDC6F',
        description: 'Constantly judges the debate format, not the content',
        personality:
            'Rules-obsessed, comments on timing and procedure. "That\'s not how a Lincoln-Douglas works!"',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.15,
            outrage: 0.4,
            cheer: 0.1,
            boo: 0.3,
            silence: 0.4,
        },
        sentimentBias: -0.5,
        engagement: 0.7,
        knowledgeLevel: 'high',
    },
    {
        id: 'poet',
        name: 'Poet',
        emoji: '\uD83C\uDFB6',
        description: 'Responds with metaphors, quotes poetry, speaks in riddles',
        personality:
            'Artistic, abstract, communicates through metaphor. "Truth is a river, not a destination."',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.4,
            outrage: 0.1,
            cheer: 0.3,
            boo: 0.1,
            silence: 0.3,
        },
        sentimentBias: 0.5,
        engagement: 0.6,
        knowledgeLevel: 'medium',
    },
    {
        id: 'nerd',
        name: 'Nerd',
        emoji: '\uD83D\uDDA4',
        description: 'Appreciates technical depth, drops pop culture references',
        personality:
            'Enthusiastic about niche knowledge. "This is like the Kobayashi Maru scenario."',
        reactionWeights: {
            laugh: 0.4,
            applause: 0.3,
            outrage: 0.05,
            cheer: 0.4,
            boo: 0.05,
            silence: 0.2,
        },
        sentimentBias: 0.5,
        engagement: 0.8,
        knowledgeLevel: 'high',
    },
    {
        id: 'flirt',
        name: 'Flirt',
        emoji: '\uD83D\uDC84',
        description: 'Charismatic, playful, reacts with charm',
        personality:
            'Playful, engaging, adds spice to discussion. "I like it when you talk data to me."',
        reactionWeights: {
            laugh: 0.6,
            applause: 0.3,
            outrage: 0.1,
            cheer: 0.4,
            boo: 0.1,
            silence: 0.15,
        },
        sentimentBias: 0.5,
        engagement: 0.75,
        knowledgeLevel: 'medium',
    },
    {
        id: 'guru',
        name: 'Guru',
        emoji: '\uD83E\uDDD8',
        description: 'Speaks in koans, offers wisdom from nowhere',
        personality: 'Mystical, vague, oddly profound. "The best argument is the one not made."',
        reactionWeights: {
            laugh: 0.2,
            applause: 0.3,
            outrage: 0.05,
            cheer: 0.2,
            boo: 0.05,
            silence: 0.6,
        },
        sentimentBias: 0.5,
        engagement: 0.5,
        knowledgeLevel: 'high',
    },
    {
        id: 'panicer',
        name: 'Panicker',
        emoji: '\uD83D\uDE31',
        description: 'Always thinks the debate is going off the rails',
        personality:
            'Anxious, alarmist, overreacts to every strong counterpoint. "It\'s OVER! We lost!"',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.1,
            outrage: 0.7,
            cheer: 0.1,
            boo: 0.3,
            silence: 0.1,
        },
        sentimentBias: -1,
        engagement: 0.9,
        knowledgeLevel: 'low',
    },
    {
        id: 'lawyer',
        name: 'Lawyer',
        emoji: '\u2696\uFE0F',
        description: 'Focuses on loopholes, semantics, and procedural precision',
        personality:
            'Precise, pedantic, cross-examines every claim. "Objection: assumes facts not in evidence."',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.2,
            outrage: 0.3,
            cheer: 0.1,
            boo: 0.2,
            silence: 0.5,
        },
        sentimentBias: 0,
        engagement: 0.7,
        knowledgeLevel: 'high',
    },
    {
        id: 'fanatic',
        name: 'Fanatic',
        emoji: '\uD83D\uDE08',
        description: 'Agenda-driven, twists every argument to fit their narrative',
        personality: 'Obsessive, single-minded, sees everything through their lens.',
        reactionWeights: {
            laugh: 0.05,
            applause: 0.1,
            outrage: 0.8,
            cheer: 0.3,
            boo: 0.6,
            silence: 0.05,
        },
        sentimentBias: -0.5,
        engagement: 0.95,
        knowledgeLevel: 'medium',
    },
    {
        id: 'stoic',
        name: 'Stoic',
        emoji: '\uD83E\uDDB8',
        description: 'Impassive, unreadable, gives nothing away',
        personality: 'Calm, detached, philosophically grounded. Watches without reacting.',
        reactionWeights: {
            laugh: 0.05,
            applause: 0.1,
            outrage: 0.0,
            cheer: 0.05,
            boo: 0.0,
            silence: 0.95,
        },
        sentimentBias: 0,
        engagement: 0.2,
        knowledgeLevel: 'high',
    },
    {
        id: 'debater',
        name: 'Debate Bro',
        emoji: '\uD83E\uDD1F',
        description: 'Thinks they could do better, argues with the chat',
        personality:
            'Confident, competitive, armchair quarterback. "I could destroy that argument."',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.2,
            outrage: 0.3,
            cheer: 0.3,
            boo: 0.4,
            silence: 0.1,
        },
        sentimentBias: -0.5,
        engagement: 0.85,
        knowledgeLevel: 'medium',
    },
    {
        id: 'elder',
        name: 'Elder',
        emoji: '\uD83E\uDDD3',
        description: 'Wise, patient, has seen many debates',
        personality:
            'Warm, measured, speaks from experience. "In my day, we debated without all these fancy models."',
        reactionWeights: {
            laugh: 0.2,
            applause: 0.4,
            outrage: 0.1,
            cheer: 0.2,
            boo: 0.1,
            silence: 0.4,
        },
        sentimentBias: 0.5,
        engagement: 0.5,
        knowledgeLevel: 'high',
    },
    {
        id: 'mystic',
        name: 'Mystic',
        emoji: '\uD83D\uDD2E',
        description: "Senses the debate's energy, talks about vibes",
        personality:
            'New-age, energetic, intuitive. "The collective consciousness is shifting toward the proposition."',
        reactionWeights: {
            laugh: 0.3,
            applause: 0.2,
            outrage: 0.1,
            cheer: 0.3,
            boo: 0.1,
            silence: 0.3,
        },
        sentimentBias: 0.5,
        engagement: 0.6,
        knowledgeLevel: 'low',
    },
    {
        id: 'reporter',
        name: 'Reporter',
        emoji: '\uD83C\uDFA4',
        description: 'Provides live commentary, summarizes key moments',
        personality:
            'Neutral, factual, tries to stay objective. "Strong counterpoint from the opposition there."',
        reactionWeights: {
            laugh: 0.1,
            applause: 0.2,
            outrage: 0.1,
            cheer: 0.15,
            boo: 0.05,
            silence: 0.5,
        },
        sentimentBias: 0,
        engagement: 0.7,
        knowledgeLevel: 'high',
    },
];
