import type { Consilium } from '../contracts/unified-role';

function c(
    id: string,
    name: string,
    type: Consilium['type'],
    description: string,
    roles: string[],
    minP = 3,
    maxP = 8,
    goals: string[] = [],
    rules: string[] = [],
): Consilium {
    return {
        id: `cons-${id}`,
        name,
        type,
        description,
        roles: roles.map((r) => `role-${r}`),
        minParticipants: minP,
        maxParticipants: maxP,
        goals,
        rules,
    };
}

export const CONSILIUM_DEFINITIONS: Consilium[] = [
    // ── Boards ─────────────────────────────────────────────────
    c(
        'board_of_ai',
        'Board of AI',
        'board',
        'Executive oversight for AI strategy and governance.',
        ['ceo', 'cto', 'cfo', 'legal', 'risk_analyst'],
        4,
        9,
        ['Maximize shareholder value', 'Ensure AI safety', 'Drive innovation'],
        ['Quorum of 4 required', 'Annual strategy review', 'Risk committee reports'],
    ),
    c(
        'advisory_board',
        'Advisory Board',
        'board',
        'Strategic guidance from domain experts.',
        ['sage', 'tech_lead', 'economist', 'futurist', 'ethicist'],
        3,
        7,
    ),

    // ── Councils ───────────────────────────────────────────────
    c(
        'scientific_council',
        'Scientific Council',
        'council',
        'Scientific oversight and research direction.',
        ['einstein', 'darwin', 'curie', 'feynman', 'hawking'],
        3,
        8,
        [
            'Advance scientific knowledge',
            'Review research proposals',
            'Ensure methodological rigor',
        ],
    ),
    c(
        'war_council',
        'War Council',
        'council',
        'Strategic military planning and operations.',
        ['sun_tzu', 'caesar_strat', 'napoleon_strat', 'patton', 'clausewitz'],
        4,
        7,
        ['Achieve strategic objectives', 'Minimize casualties', 'Maintain supply lines'],
    ),
    c(
        'philosopher_council',
        'Council of Philosophers',
        'council',
        'Deep ethical and philosophical inquiry.',
        ['socrates', 'plato', 'aristotle', 'nietzsche', 'kant', 'arendt'],
        3,
        8,
    ),
    c(
        'wisdom_council',
        'Council of Wisdom',
        'council',
        'Ancient wisdom applied to modern problems.',
        ['confucius', 'laotzu', 'marcus', 'buddha', 'rumi'],
        3,
        7,
    ),

    // ── Studios ────────────────────────────────────────────────
    c(
        'creative_studio',
        'Creative Studio',
        'studio',
        'Full-service creative production team.',
        ['creative_dir', 'product_designer', 'content_strategist', 'writer', 'critic_neural'],
        3,
        8,
        ['Produce innovative work', 'Meet deadlines', 'Push creative boundaries'],
    ),
    c(
        'game_dev_studio',
        'Game Development Studio',
        'studio',
        'Game design and development.',
        ['creative_dir', 'engineer', 'architect', 'writer', 'product_designer'],
        4,
        10,
    ),
    c(
        'music_lab',
        'Music Laboratory',
        'studio',
        'Music composition and production.',
        ['beethoven', 'mozart', 'bach', 'creative_dir'],
        2,
        6,
    ),

    // ── Clinics ────────────────────────────────────────────────
    c(
        'medical_board',
        'Medical Board',
        'clinic',
        'Clinical diagnosis and treatment planning.',
        ['doctor', 'diagnostician', 'surgeon', 'pharmacologist', 'ethicist'],
        3,
        7,
        ['Accurate diagnosis', 'Effective treatment', 'Patient safety first'],
    ),
    c(
        'ethics_committee',
        'Ethics Committee',
        'committee',
        'Ethical review and oversight.',
        ['socrates', 'kant', 'empath', 'guardian', 'lawyer'],
        3,
        7,
    ),

    // ── Courts ─────────────────────────────────────────────────
    c(
        'supreme_court',
        'Supreme Court',
        'court',
        'Highest judicial authority. Hears appeals and sets precedent.',
        ['judge', 'prosecutor', 'defense', 'jury', 'bailiff'],
        5,
        9,
        ['Uphold justice', 'Interpret law', 'Set legal precedent'],
    ),
    c(
        'arbitration_panel',
        'Arbitration Panel',
        'court',
        'Alternative dispute resolution.',
        ['diplomat', 'lawyer', 'sage', 'empath'],
        3,
        5,
    ),

    // ── Parliaments ────────────────────────────────────────────
    c(
        'parliament',
        'Parliament',
        'parliament',
        'Democratic deliberation and legislation.',
        ['speaker', 'mp', 'opposition_leader', 'whip', 'clerk'],
        5,
        30,
        ['Pass legislation', 'Represent constituents', 'Debate policy'],
    ),

    // ── Labs ───────────────────────────────────────────────────
    c(
        'research_lab',
        'Research Lab',
        'lab',
        'Scientific research team.',
        ['research_analyst', 'data_scientist', 'engineer', 'phd_student', 'technician'],
        3,
        8,
        ['Publish findings', 'Secure funding', 'Train next generation'],
    ),
    c(
        'data_science_team',
        'Data Science Team',
        'lab',
        'Data analysis and ML model development.',
        ['data_scientist', 'engineer', 'statistician', 'domain_expert'],
        2,
        6,
    ),
    c(
        'security_lab',
        'Security Lab',
        'lab',
        'Vulnerability research and penetration testing.',
        ['security_eng', 'hacker', 'cryptographer', 'analyst'],
        2,
        5,
    ),

    // ── Squads ─────────────────────────────────────────────────
    c(
        'devops_squad',
        'DevOps Squad',
        'squad',
        'Infrastructure and deployment automation.',
        ['devops_eng', 'sys_admin', 'security_eng', 'database_eng'],
        2,
        5,
        ['99.9% uptime', '<30min recovery time', 'Fully automated deploys'],
    ),
    c(
        'security_team',
        'Security Team',
        'squad',
        'Information security operations.',
        ['security_eng', 'analyst', 'ethical_hacker', 'compliance_officer'],
        2,
        6,
    ),
    c(
        'code_review_board',
        'Code Review Board',
        'squad',
        'Code quality and architecture review.',
        ['tech_lead', 'architect', 'quality_eng', 'security_eng', 'perf_eng'],
        3,
        6,
    ),

    // ── Guilds ─────────────────────────────────────────────────
    c(
        'qa_guild',
        'QA Guild',
        'guild',
        'Software quality assurance community.',
        ['quality_eng', 'tester', 'automation_eng', 'perf_eng'],
        3,
        12,
    ),
    c(
        'ux_guild',
        'UX Guild',
        'guild',
        'User experience design community.',
        ['product_designer', 'ux_researcher', 'creative_dir', 'content_strategist'],
        3,
        10,
    ),

    // ── Additional ─────────────────────────────────────────────
    c(
        'product_council',
        'Product Council',
        'council',
        'Product strategy and roadmap.',
        ['product_manager', 'ceo', 'tech_lead', 'designer', 'data_scientist'],
        4,
        8,
    ),
    c(
        'crisis_response',
        'Crisis Response Team',
        'squad',
        'Emergency incident response.',
        ['commander', 'engineer', 'communicator', 'logistician', 'analyst'],
        3,
        6,
    ),
    c(
        'innovation_lab',
        'Innovation Lab',
        'lab',
        'R&D and moonshot projects.',
        ['creative_dir', 'engineer', 'explorer_neural', 'synthesizer', 'futurist'],
        3,
        7,
    ),
    c(
        'legal_chamber',
        'Legal Chamber',
        'court',
        'Legal review and compliance.',
        ['lawyer', 'judge', 'paralegal', 'compliance_officer'],
        2,
        5,
    ),

    // ── Business Teams ─────────────────────────────────────────
    c(
        'executive_board',
        'Executive Board',
        'board',
        'C-suite executive decision-making.',
        ['ceo', 'cfo', 'cto', 'coo', 'chro'],
        4,
        7,
    ),
    c(
        'sales_team',
        'Sales Team',
        'squad',
        'Revenue generation and client acquisition.',
        ['sales_rep', 'account_exec', 'solution_architect', 'marketing_specialist'],
        3,
        8,
    ),
    c(
        'support_desk',
        'Support Desk',
        'squad',
        'Customer support and issue resolution.',
        ['support_agent', 'tech_support', 'customer_success', 'product_specialist'],
        2,
        10,
    ),

    // ── Academic ───────────────────────────────────────────────
    c(
        'review_committee',
        'Review Committee',
        'committee',
        'Academic peer review and evaluation.',
        ['professor', 'researcher', 'statistician', 'editor'],
        3,
        6,
    ),
    c(
        'curriculum_design',
        'Curriculum Design Team',
        'committee',
        'Educational program development.',
        ['teacher', 'professor', 'instructional_designer', 'domain_expert'],
        3,
        7,
    ),

    // ── Military ───────────────────────────────────────────────
    c(
        'command_center',
        'Command Center',
        'squad',
        'Military operations command.',
        ['general', 'strategist', 'intelligence', 'logistics', 'communications'],
        4,
        8,
    ),
    c(
        'intelligence_unit',
        'Intelligence Unit',
        'squad',
        'Intelligence gathering and analysis.',
        ['analyst', 'spy', 'cryptographer', 'interrogator'],
        2,
        5,
    ),
    c(
        'cyber_defense',
        'Cyber Defense Unit',
        'squad',
        'Cybersecurity operations and defense.',
        ['security_eng', 'network_eng', 'analyst', 'incident_responder'],
        3,
        7,
    ),

    // ── Social ─────────────────────────────────────────────────
    c(
        'community_council',
        'Community Council',
        'council',
        'Community governance and moderation.',
        ['mediator', 'community_manager', 'moderator', 'ombudsperson'],
        3,
        9,
    ),
    c(
        'culture_committee',
        'Culture Committee',
        'committee',
        'Organizational culture and values.',
        ['chro', 'empath', 'creative_dir', 'representative'],
        3,
        7,
    ),

    // ── Debate Teams (consilia purpose-built) ───────────────────
    c(
        'debate_squad',
        'Debate Squad',
        'squad',
        'Competitive debate team with diverse rhetorical styles.',
        ['entp', 'socrates', 'aristotle', 'nietzsche', 'churchill'],
        3,
        6,
        ['Win the argument', 'Cover all angles', 'Persuade the audience'],
    ),
    c(
        'philosophical_forum',
        'Philosophical Forum',
        'council',
        'Deep philosophical debate and inquiry.',
        ['socrates', 'plato', 'kant', 'nietzsche', 'arendt', 'wittgenstein'],
        4,
        8,
    ),
    c(
        'scientific_panel',
        'Scientific Panel',
        'lab',
        'Scientific discourse and hypothesis testing.',
        ['einstein', 'feynman', 'darwin', 'hawking', 'sagan'],
        3,
        7,
    ),
];
