import type { Creature } from '../contracts/ecosystem';

export const CREATURES: Creature[] = [
    // ── Common (20) ──
    {
        id: 'clownfish',
        name: 'Clownfish',
        emoji: '🐠',
        description: 'A small, colorful reef dweller',
        rarity: 'common',
        personality: 'hyper',
        color: '#ff6b35',
        unlockCondition: 'Add your first key',
        hungerRate: 1,
        energy: 50,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'goldfish',
        name: 'Goldfish',
        emoji: '🐟',
        description: 'The classic aquarium pet',
        rarity: 'common',
        personality: 'lazy',
        color: '#ffd700',
        unlockCondition: 'First probe success',
        hungerRate: 1,
        energy: 60,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'turtle',
        name: 'Sea Turtle',
        emoji: '🐢',
        description: 'Slow but wise ancient mariner',
        rarity: 'common',
        personality: 'lazy',
        color: '#2ecc71',
        unlockCondition: '10 successful API calls',
        hungerRate: 2,
        energy: 80,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'penguin',
        name: 'Penguin',
        emoji: '🐧',
        description: 'Dapper arctic swimmer',
        rarity: 'common',
        personality: 'brave',
        color: '#1a1a2e',
        unlockCondition: 'Add a second provider',
        hungerRate: 2,
        energy: 70,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'frog',
        name: 'Tree Frog',
        emoji: '🐸',
        description: 'Small amphibian with big eyes',
        rarity: 'common',
        personality: 'shy',
        color: '#2ecc71',
        unlockCondition: 'First chat message',
        hungerRate: 1,
        energy: 40,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'crab',
        name: 'Hermit Crab',
        emoji: '🦀',
        description: 'Always looking for a new shell',
        rarity: 'common',
        personality: 'shy',
        color: '#e74c3c',
        unlockCondition: 'Use the routing panel',
        hungerRate: 1,
        energy: 45,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'seahorse',
        name: 'Seahorse',
        emoji: '🐡',
        description: 'Gentle dancer of the currents',
        rarity: 'common',
        personality: 'shy',
        color: '#f39c12',
        unlockCondition: 'Run a debate',
        hungerRate: 1,
        energy: 35,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'starfish',
        name: 'Starfish',
        emoji: '⭐',
        description: 'Five-pointed bottom dweller',
        rarity: 'common',
        personality: 'lazy',
        color: '#e91e63',
        unlockCondition: 'View analytics dashboard',
        hungerRate: 1,
        energy: 30,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'blowfish',
        name: 'Blowfish',
        emoji: '🐡',
        description: 'Inflates when threatened',
        rarity: 'common',
        personality: 'shy',
        color: '#ff9800',
        unlockCondition: 'First error handled',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'shrimp',
        name: 'Cleaner Shrimp',
        emoji: '🦐',
        description: 'Tiny but useful crew member',
        rarity: 'common',
        personality: 'hyper',
        color: '#ff5722',
        unlockCondition: 'Connect a webhook',
        hungerRate: 1,
        energy: 25,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'koi',
        name: 'Koi Fish',
        emoji: '🐟',
        description: 'Majestic Japanese garden fish',
        rarity: 'common',
        personality: 'curious',
        color: '#ff6f61',
        unlockCondition: 'Create a role',
        hungerRate: 2,
        energy: 65,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'axolotl',
        name: 'Axolotl',
        emoji: '🦎',
        description: 'Smiling Mexican salamander',
        rarity: 'common',
        personality: 'curious',
        color: '#ff9ff3',
        unlockCondition: 'Use memory panel',
        hungerRate: 1,
        energy: 50,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'betta',
        name: 'Siamese Fighting Fish',
        emoji: '🐟',
        description: 'Vibrant and territorial',
        rarity: 'common',
        personality: 'brave',
        color: '#0984e3',
        unlockCondition: 'Win a debate',
        hungerRate: 2,
        energy: 70,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'guppy',
        name: 'Guppy',
        emoji: '🐟',
        description: 'Small, colorful live-bearer',
        rarity: 'common',
        personality: 'hyper',
        color: '#00b894',
        unlockCondition: 'Add a key to a pool',
        hungerRate: 1,
        energy: 30,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'angel',
        name: 'Angelfish',
        emoji: '🐟',
        description: 'Graceful triangular beauty',
        rarity: 'common',
        personality: 'curious',
        color: '#ffeaa7',
        unlockCondition: 'Open the trace view',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'discus',
        name: 'Discus',
        emoji: '🐟',
        description: 'Round disc-shaped cichlid',
        rarity: 'common',
        personality: 'shy',
        color: '#6c5ce7',
        unlockCondition: 'Join a group',
        hungerRate: 2,
        energy: 50,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'tetra',
        name: 'Neon Tetra',
        emoji: '🐟',
        description: 'Tiny glowing school fish',
        rarity: 'common',
        personality: 'hyper',
        color: '#00cec9',
        unlockCondition: 'View logs',
        hungerRate: 1,
        energy: 25,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'molly',
        name: 'Molly',
        emoji: '🐟',
        description: 'Hardy community fish',
        rarity: 'common',
        personality: 'curious',
        color: '#fab1a0',
        unlockCondition: 'Use the sandbox',
        hungerRate: 1,
        energy: 45,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'platy',
        name: 'Platy',
        emoji: '🐟',
        description: 'Friendly beginner fish',
        rarity: 'common',
        personality: 'hyper',
        color: '#e17055',
        unlockCondition: 'Complete first research loop',
        hungerRate: 1,
        energy: 35,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'swordtail',
        name: 'Swordtail',
        emoji: '🐟',
        description: 'Elegant with distinctive tail',
        rarity: 'common',
        personality: 'brave',
        color: '#d63031',
        unlockCondition: 'Create a persona',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },

    // ── Uncommon (12) ──
    {
        id: 'jellyfish',
        name: 'Moon Jellyfish',
        emoji: '🪼',
        description: 'Ethereal translucent drifter',
        rarity: 'uncommon',
        personality: 'shy',
        color: '#a29bfe',
        unlockCondition: '5 active keys',
        hungerRate: 1,
        energy: 40,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'octopus',
        name: 'Octopus',
        emoji: '🐙',
        description: 'Eight-armed genius escape artist',
        rarity: 'uncommon',
        personality: 'curious',
        color: '#e17055',
        unlockCondition: 'Run 3 debate sessions',
        hungerRate: 3,
        energy: 85,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'dolphin',
        name: 'Dolphin',
        emoji: '🐬',
        description: 'Playful intelligent marine mammal',
        rarity: 'uncommon',
        personality: 'hyper',
        color: '#0984e3',
        unlockCondition: '100 total API calls',
        hungerRate: 4,
        energy: 90,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'seal',
        name: 'Fur Seal',
        emoji: '🦭',
        description: 'Playful pinniped with big eyes',
        rarity: 'uncommon',
        personality: 'curious',
        color: '#636e72',
        unlockCondition: 'Use the cache panel',
        hungerRate: 3,
        energy: 70,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'eel',
        name: 'Moray Eel',
        emoji: '🐍',
        description: 'Secretive crevice dweller',
        rarity: 'uncommon',
        personality: 'shy',
        color: '#2d3436',
        unlockCondition: 'Circuit breaker opens once',
        hungerRate: 2,
        energy: 65,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'stingray',
        name: 'Stingray',
        emoji: '🦈',
        description: 'Graceful winged bottom-dweller',
        rarity: 'uncommon',
        personality: 'lazy',
        color: '#6c5ce7',
        unlockCondition: 'Use budget panel',
        hungerRate: 2,
        energy: 60,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'cuttlefish',
        name: 'Cuttlefish',
        emoji: '🐙',
        description: 'Master of camouflage',
        rarity: 'uncommon',
        personality: 'shy',
        color: '#fd79a8',
        unlockCondition: 'Change theme',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'puffer',
        name: 'Pufferfish',
        emoji: '🐡',
        description: 'Spiny inflatable comedian',
        rarity: 'uncommon',
        personality: 'brave',
        color: '#fdcb6e',
        unlockCondition: 'Handle a 429 error',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'lobster',
        name: 'Lobster',
        emoji: '🦞',
        description: 'Armored bottom-scavenger',
        rarity: 'uncommon',
        personality: 'brave',
        color: '#e74c3c',
        unlockCondition: '5 providers configured',
        hungerRate: 3,
        energy: 75,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'nautilus',
        name: 'Chambered Nautilus',
        emoji: '🐚',
        description: 'Living fossil with spiral shell',
        rarity: 'uncommon',
        personality: 'lazy',
        color: '#ffeaa7',
        unlockCondition: 'View memory palace',
        hungerRate: 1,
        energy: 40,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'seahorse2',
        name: 'Leafy Seadragon',
        emoji: '🐉',
        description: 'Camouflage master of kelp forests',
        rarity: 'uncommon',
        personality: 'shy',
        color: '#00b894',
        unlockCondition: 'Complete a research session',
        hungerRate: 2,
        energy: 50,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'anemone',
        name: 'Sea Anemone',
        emoji: '🌺',
        description: 'Venomous flower of the sea',
        rarity: 'uncommon',
        personality: 'lazy',
        color: '#e84393',
        unlockCondition: 'Add 2 keys to one provider',
        hungerRate: 1,
        energy: 35,
        maxEnergy: 100,
        isUnlocked: false,
    },

    // ── Rare (10) ──
    {
        id: 'manta',
        name: 'Manta Ray',
        emoji: '🦈',
        description: 'Gentle giant gliding through darkness',
        rarity: 'rare',
        personality: 'curious',
        color: '#2d3436',
        unlockCondition: '1000 successful API calls',
        hungerRate: 4,
        energy: 95,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'orca',
        name: 'Orca',
        emoji: '🐋',
        description: 'Apex predator of the ocean',
        rarity: 'rare',
        personality: 'brave',
        color: '#1a1a2e',
        unlockCondition: 'Win 5 debates',
        hungerRate: 5,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'narwhal',
        name: 'Narwhal',
        emoji: '🦄',
        description: 'Unicorn of the sea',
        rarity: 'rare',
        personality: 'curious',
        color: '#74b9ff',
        unlockCondition: 'Use all 12+ providers',
        hungerRate: 3,
        energy: 80,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'walrus',
        name: 'Walrus',
        emoji: '🦭',
        description: 'Massive tusked pinniped',
        rarity: 'rare',
        personality: 'lazy',
        color: '#b2bec3',
        unlockCondition: '30 days of activity',
        hungerRate: 4,
        energy: 85,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'squid',
        name: 'Giant Squid',
        emoji: '🦑',
        description: 'Deep-sea leviathan with huge eyes',
        rarity: 'rare',
        personality: 'shy',
        color: '#6c5ce7',
        unlockCondition: '100k tokens processed',
        hungerRate: 4,
        energy: 90,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'pelican',
        name: 'Pelican',
        emoji: '🐦',
        description: 'Big-beaked surface hunter',
        rarity: 'rare',
        personality: 'curious',
        color: '#fdcb6e',
        unlockCondition: 'Use webhooks 10 times',
        hungerRate: 3,
        energy: 70,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'flamingo',
        name: 'Flamingo',
        emoji: '🦩',
        description: 'Elegant pink wader',
        rarity: 'rare',
        personality: 'hyper',
        color: '#fd79a8',
        unlockCondition: 'Add 50 keys total',
        hungerRate: 2,
        energy: 60,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'turtle2',
        name: 'Leatherback Turtle',
        emoji: '🐢',
        description: 'Ancient giant of the deep',
        rarity: 'rare',
        personality: 'lazy',
        color: '#2ecc71',
        unlockCondition: 'Survive 24h without error',
        hungerRate: 3,
        energy: 90,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'dragonfish',
        name: 'Dragonfish',
        emoji: '🐉',
        description: 'Deep-sea predator with light lure',
        rarity: 'rare',
        personality: 'brave',
        color: '#e74c3c',
        unlockCondition: 'Create a consilium',
        hungerRate: 3,
        energy: 75,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'sea_dragon',
        name: 'Ruby Seadragon',
        emoji: '🐉',
        description: 'Rare deep-red relative of seahorses',
        rarity: 'rare',
        personality: 'shy',
        color: '#e84393',
        unlockCondition: 'Reach 100 achievements',
        hungerRate: 2,
        energy: 55,
        maxEnergy: 100,
        isUnlocked: false,
    },

    // ── Epic (6) ──
    {
        id: 'whale_shark',
        name: 'Whale Shark',
        emoji: '🦈',
        description: 'Largest fish in the ocean',
        rarity: 'epic',
        personality: 'lazy',
        color: '#0984e3',
        unlockCondition: '10000 total API calls',
        hungerRate: 6,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'phoenix',
        name: 'Aquatic Phoenix',
        emoji: '🔥',
        description: 'Reborn from the depths',
        rarity: 'epic',
        personality: 'brave',
        color: '#e17055',
        unlockCondition: 'Recover from 10 circuit breaks',
        hungerRate: 5,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'dragon_kite',
        name: 'Sea Serpent',
        emoji: '🐉',
        description: 'Legendary serpent of the abyss',
        rarity: 'epic',
        personality: 'brave',
        color: '#00cec9',
        unlockCondition: 'Win a tournament',
        hungerRate: 5,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'crystal_jelly',
        name: 'Crystal Jelly',
        emoji: '🪼',
        description: 'Bioluminescent deep-sea wonder',
        rarity: 'epic',
        personality: 'curious',
        color: '#a29bfe',
        unlockCondition: 'All memory stores active',
        hungerRate: 2,
        energy: 60,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'golden_crab',
        name: 'Golden King Crab',
        emoji: '🦀',
        description: 'Legendary crustacean of the deep',
        rarity: 'epic',
        personality: 'brave',
        color: '#fdcb6e',
        unlockCondition: 'Accumulate 1M tokens',
        hungerRate: 4,
        energy: 85,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'abyss_angler',
        name: 'Abyss Anglerfish',
        emoji: '🐟',
        description: 'Deepest of the deep sea predators',
        rarity: 'epic',
        personality: 'shy',
        color: '#2d3436',
        unlockCondition: 'Reach 10k latency samples',
        hungerRate: 3,
        energy: 80,
        maxEnergy: 100,
        isUnlocked: false,
    },

    // ── Legendary (4) ──
    {
        id: 'kraken',
        name: 'Kraken',
        emoji: '🐙',
        description: 'Mythical giant of the Norwegian sea',
        rarity: 'legendary',
        personality: 'brave',
        color: '#6c5ce7',
        unlockCondition: 'Have all 13 P0 gaps resolved',
        hungerRate: 7,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'leviathan',
        name: 'Leviathan',
        emoji: '🐋',
        description: 'Biblical primordial sea monster',
        rarity: 'legendary',
        personality: 'brave',
        color: '#1a1a2e',
        unlockCondition: '100k total requests',
        hungerRate: 8,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'celestial_whale',
        name: 'Celestial Whale',
        emoji: '🐋',
        description: 'Stardust-breathing cosmic entity',
        rarity: 'legendary',
        personality: 'curious',
        color: '#a29bfe',
        unlockCondition: 'Reach system level 100',
        hungerRate: 6,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
    {
        id: 'great_dragon',
        name: 'Great Dragon Turtle',
        emoji: '🐢',
        description: 'Ancient dragon-turtle hybrid',
        rarity: 'legendary',
        personality: 'curious',
        color: '#f39c12',
        unlockCondition: 'Complete all 10 arena layouts',
        hungerRate: 7,
        energy: 100,
        maxEnergy: 100,
        isUnlocked: false,
    },
];

export function getCreaturesByRarity(rarity: string): Creature[] {
    return CREATURES.filter((c) => c.rarity === rarity);
}

export function getUnlockedCreatures(): Creature[] {
    return CREATURES.filter((c) => c.isUnlocked);
}
