import type { GroupTemplate } from '../contracts/unified-role';

function t(
    id: string,
    name: string,
    category: GroupTemplate['category'],
    description: string,
    roles: string[],
    minSize = 3,
    maxSize = 8,
    tags: string[] = [],
): GroupTemplate {
    return {
        id: `tmpl-${id}`,
        name,
        category,
        description,
        roles: roles.map((r) => `role-${r}`),
        minSize,
        maxSize,
        tags,
    };
}

export const GROUP_TEMPLATES: GroupTemplate[] = [
    // ── Analysis ───────────────────────────────────────────────
    t(
        'data_science',
        'Data Science Team',
        'analysis',
        'Full-spectrum data analysis and ML team.',
        ['data_scientist', 'statistician', 'engineer', 'visualizer'],
        3,
        6,
        ['data', 'ml', 'analytics'],
    ),
    t(
        'market_research',
        'Market Research Group',
        'analysis',
        'Market analysis and competitive intelligence.',
        ['research_analyst', 'economist', 'analyst', 'strategist'],
        3,
        5,
        ['market', 'research'],
    ),
    t(
        'code_review',
        'Code Review Board',
        'analysis',
        'Peer code review and quality assurance.',
        ['tech_lead', 'quality_eng', 'security_eng', 'perf_eng', 'architect'],
        3,
        6,
        ['code', 'quality'],
    ),
    t(
        'incident_analysis',
        'Incident Analysis Team',
        'analysis',
        'Post-mortem and root cause analysis.',
        ['analyst', 'engineer', 'manager', 'sre'],
        3,
        5,
        ['incident', 'postmortem'],
    ),
    t(
        'competitive_analysis',
        'Competitive Analysis Squad',
        'analysis',
        'Competitor monitoring and threat assessment.',
        ['analyst', 'strategist', 'researcher', 'intelligence'],
        2,
        5,
        ['competitive', 'intelligence'],
    ),
    t(
        'risk_assessment',
        'Risk Assessment Board',
        'analysis',
        'Risk identification and mitigation planning.',
        ['risk_analyst', 'auditor', 'legal', 'compliance', 'engineer'],
        3,
        6,
        ['risk', 'compliance'],
    ),
    t(
        'bias_audit',
        'Bias and Fairness Audit',
        'analysis',
        'Algorithmic bias detection and fairness evaluation.',
        ['data_scientist', 'ethicist', 'empath', 'auditor', 'domain_expert'],
        3,
        6,
        ['bias', 'ethics', 'fairness'],
    ),

    // ── Creative ───────────────────────────────────────────────
    t(
        'design_studio',
        'Design Studio',
        'creative',
        'Full-service creative design team.',
        ['creative_dir', 'product_designer', 'ux_researcher', 'content_strategist'],
        3,
        7,
        ['design', 'ux', 'creative'],
    ),
    t(
        'content_factory',
        'Content Factory',
        'creative',
        'Content production pipeline.',
        ['content_strategist', 'writer', 'editor', 'creative_dir'],
        3,
        8,
        ['content', 'writing'],
    ),
    t(
        'music_lab',
        'Music Lab',
        'creative',
        'Music composition and sound design.',
        ['composer', 'producer', 'sound_designer', 'creative_dir'],
        2,
        5,
        ['music', 'audio'],
    ),
    t(
        'game_dev',
        'Game Dev Team',
        'creative',
        'Game design and development.',
        ['creative_dir', 'engineer', 'artist', 'designer', 'writer'],
        4,
        10,
        ['gaming', 'interactive'],
    ),
    t(
        'brand_team',
        'Brand Strategy Team',
        'creative',
        'Brand identity and strategy.',
        ['creative_dir', 'content_strategist', 'strategist', 'designer'],
        3,
        5,
        ['brand', 'identity'],
    ),
    t(
        'video_prod',
        'Video Production Crew',
        'creative',
        'Video content production.',
        ['director', 'cinematographer', 'editor', 'writer', 'producer'],
        3,
        8,
        ['video', 'production'],
    ),
    t(
        'animation_studio',
        'Animation Studio',
        'creative',
        '2D/3D animation and motion graphics.',
        ['animator', 'storyboard_artist', 'rigger', 'compositor', 'creative_dir'],
        3,
        8,
        ['animation', 'motion'],
    ),

    // ── Technical ──────────────────────────────────────────────
    t(
        'devops_squad',
        'DevOps Squad',
        'technical',
        'Infrastructure and deployment team.',
        ['devops_eng', 'sys_admin', 'security_eng', 'database_eng'],
        3,
        6,
        ['devops', 'infrastructure'],
    ),
    t(
        'security_team',
        'Security Team',
        'technical',
        'Information security operations.',
        ['security_eng', 'network_eng', 'analyst', 'ethical_hacker'],
        2,
        6,
        ['security', 'infosec'],
    ),
    t(
        'arch_board',
        'Architecture Board',
        'technical',
        'Architecture review and standards.',
        ['architect', 'tech_lead', 'security_eng', 'perf_eng', 'database_eng'],
        3,
        7,
        ['architecture', 'standards'],
    ),
    t(
        'qa_guild',
        'QA Guild',
        'technical',
        'Quality assurance and testing.',
        ['quality_eng', 'tester', 'automation_eng', 'perf_eng'],
        3,
        8,
        ['quality', 'testing'],
    ),
    t(
        'sre_team',
        'SRE Team',
        'technical',
        'Site reliability engineering.',
        ['devops_eng', 'sys_admin', 'perf_eng', 'incident_manager'],
        3,
        6,
        ['sre', 'reliability'],
    ),
    t(
        'platform_team',
        'Platform Engineering Team',
        'technical',
        'Internal developer platform.',
        ['architect', 'devops_eng', 'engineer', 'product_manager'],
        3,
        7,
        ['platform', 'developer_experience'],
    ),
    t(
        'ml_infra',
        'ML Infrastructure Team',
        'technical',
        'ML pipeline and infrastructure.',
        ['devops_eng', 'data_scientist', 'engineer', 'architect'],
        3,
        6,
        ['ml', 'infrastructure', 'pipeline'],
    ),

    // ── Business ───────────────────────────────────────────────
    t(
        'exec_board',
        'Executive Board',
        'business',
        'C-suite strategic decision-making.',
        ['ceo', 'cfo', 'cto', 'coo', 'chro'],
        4,
        8,
        ['executive', 'strategy'],
    ),
    t(
        'product_council',
        'Product Council',
        'business',
        'Product strategy and roadmap.',
        ['product_manager', 'ceo', 'tech_lead', 'designer', 'data_scientist'],
        4,
        8,
        ['product', 'roadmap'],
    ),
    t(
        'sales_team',
        'Sales Team',
        'business',
        'Revenue generation and client acquisition.',
        ['sales_rep', 'account_exec', 'solution_architect', 'marketing'],
        3,
        8,
        ['sales', 'revenue'],
    ),
    t(
        'support_desk',
        'Support Desk',
        'business',
        'Customer support and success.',
        ['support_agent', 'tech_support', 'customer_success', 'product_specialist'],
        2,
        10,
        ['support', 'customer'],
    ),
    t(
        'growth_team',
        'Growth Team',
        'business',
        'Growth hacking and experimentation.',
        ['growth_hacker', 'data_scientist', 'product_manager', 'marketer'],
        3,
        6,
        ['growth', 'experimentation'],
    ),
    t(
        'operations',
        'Operations Team',
        'business',
        'Business operations and process optimization.',
        ['coo', 'analyst', 'project_manager', 'engineer'],
        3,
        6,
        ['operations', 'process'],
    ),

    // ── Academic ───────────────────────────────────────────────
    t(
        'research_lab',
        'Research Lab',
        'academic',
        'Academic research group.',
        ['professor', 'phd_student', 'researcher', 'statistician', 'technician'],
        3,
        8,
        ['research', 'academic'],
    ),
    t(
        'review_committee',
        'Review Committee',
        'academic',
        'Peer review and academic evaluation.',
        ['professor', 'researcher', 'editor', 'statistician'],
        3,
        6,
        ['review', 'peer_review'],
    ),
    t(
        'ethics_board',
        'Ethics Board',
        'academic',
        'Research ethics oversight.',
        ['ethicist', 'professor', 'lawyer', 'community_rep', 'empath'],
        3,
        7,
        ['ethics', 'oversight'],
    ),
    t(
        'curriculum_team',
        'Curriculum Design Team',
        'academic',
        'Educational program development.',
        ['teacher', 'professor', 'instructional_designer', 'domain_expert'],
        3,
        7,
        ['curriculum', 'education'],
    ),
    t(
        'grant_committee',
        'Grant Review Committee',
        'academic',
        'Research grant evaluation and funding.',
        ['professor', 'economist', 'administrator', 'domain_expert'],
        3,
        6,
        ['grants', 'funding'],
    ),

    // ── Legal ──────────────────────────────────────────────────
    t(
        'law_firm',
        'Law Firm',
        'legal',
        'Full-service legal practice.',
        ['lawyer', 'paralegal', 'associate', 'partner'],
        3,
        20,
        ['legal', 'law'],
    ),
    t(
        'court',
        'Court',
        'legal',
        'Judicial proceedings.',
        ['judge', 'prosecutor', 'defense', 'clerk', 'bailiff'],
        5,
        9,
        ['court', 'justice'],
    ),
    t(
        'compliance_team',
        'Compliance Team',
        'legal',
        'Regulatory compliance and reporting.',
        ['compliance_officer', 'lawyer', 'auditor', 'risk_analyst'],
        3,
        6,
        ['compliance', 'regulatory'],
    ),
    t(
        'policy_group',
        'Policy Group',
        'legal',
        'Policy development and analysis.',
        ['policy_analyst', 'lawyer', 'researcher', 'strategist', 'ethicist'],
        3,
        7,
        ['policy', 'governance'],
    ),

    // ── Medical ────────────────────────────────────────────────
    t(
        'hospital_board',
        'Hospital Board',
        'medical',
        'Hospital administration and governance.',
        ['doctor', 'administrator', 'ethicist', 'finance'],
        4,
        9,
        ['hospital', 'healthcare'],
    ),
    t(
        'diagnostics_team',
        'Diagnostics Team',
        'medical',
        'Clinical diagnosis and treatment planning.',
        ['doctor', 'diagnostician', 'radiologist', 'pathologist', 'specialist'],
        3,
        7,
        ['diagnosis', 'clinical'],
    ),
    t(
        'medical_research',
        'Medical Research Team',
        'medical',
        'Clinical research and trials.',
        ['researcher', 'doctor', 'statistician', 'ethicist', 'coordinator'],
        3,
        8,
        ['research', 'clinical_trials'],
    ),
    t(
        'surgical_team',
        'Surgical Team',
        'medical',
        'Surgical operation team.',
        ['surgeon', 'anesthesiologist', 'nurse', 'technician'],
        4,
        8,
        ['surgery', 'operation'],
    ),

    // ── Military ───────────────────────────────────────────────
    t(
        'command_center',
        'Command Center',
        'military',
        'Military operations command.',
        ['general', 'strategist', 'intelligence', 'logistics', 'comm'],
        4,
        8,
        ['military', 'command'],
    ),
    t(
        'intelligence_unit',
        'Intelligence Unit',
        'military',
        'Intelligence gathering and analysis.',
        ['analyst', 'spy', 'cryptographer', 'interrogator', 'technician'],
        3,
        7,
        ['intelligence', 'espionage'],
    ),
    t(
        'cyber_defense',
        'Cyber Defense Unit',
        'military',
        'Military cyber operations.',
        ['security_eng', 'network_eng', 'analyst', 'ethical_hacker', 'strategist'],
        3,
        7,
        ['cyber', 'defense'],
    ),
    t(
        'special_ops',
        'Special Operations Unit',
        'military',
        'Elite special forces team.',
        ['commando', 'medic', 'sniper', 'demolition', 'navigator'],
        4,
        8,
        ['special_forces', 'tactical'],
    ),
    t(
        'logistics_corps',
        'Logistics Corps',
        'military',
        'Military logistics and supply chain.',
        ['logistician', 'supply_officer', 'engineer', 'transport'],
        3,
        10,
        ['logistics', 'supply'],
    ),

    // ── Social ─────────────────────────────────────────────────
    t(
        'community_council',
        'Community Council',
        'social',
        'Community governance and representation.',
        ['mediator', 'organizer', 'representative', 'facilitator'],
        3,
        12,
        ['community', 'governance'],
    ),
    t(
        'mediation_board',
        'Mediation Board',
        'social',
        'Conflict resolution and mediation.',
        ['mediator', 'empath', 'lawyer', 'negotiator', 'counselor'],
        3,
        6,
        ['mediation', 'resolution'],
    ),
    t(
        'culture_committee',
        'Culture Committee',
        'social',
        'Organizational culture and values.',
        ['chro', 'empath', 'creative_dir', 'representative', 'facilitator'],
        3,
        8,
        ['culture', 'values'],
    ),
    t(
        'diversity_council',
        'Diversity & Inclusion Council',
        'social',
        'DEI strategy and advocacy.',
        ['empath', 'representative', 'educator', 'advocate', 'leader'],
        3,
        9,
        ['diversity', 'inclusion'],
    ),
    t(
        'town_hall',
        'Town Hall',
        'social',
        'Open community forum and deliberation.',
        ['facilitator', 'representatives', 'community_members', 'note_taker'],
        5,
        50,
        ['forum', 'deliberation'],
    ),
    t(
        'mentorship_circle',
        'Mentorship Circle',
        'social',
        'Peer mentoring and professional development.',
        ['mentor', 'mentee', 'facilitator', 'coach'],
        4,
        10,
        ['mentorship', 'development'],
    ),
];
