import type { TeamTemplate } from '../contracts/role-team';

export const TEAM_TEMPLATES: TeamTemplate[] = [
    // ════════════════════════════════════════════
    // Scientific (15)
    // ════════════════════════════════════════════
    {
        id: 'tt-sci-research',
        name: 'Scientific Research Team',
        description: 'Research project from hypothesis to paper',
        icon: '🎓',
        color: '#3b82f6',
        domain: 'scientific',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'principal_investigator',
            'postdoc',
            'phd_student',
            'statistician',
            'reviewer',
            'lab_manager',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Research project', 'Paper writing', 'Grant proposal'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-hypothesis',
        name: 'Hypothesis Testing Panel',
        description: 'Rigorously test new hypotheses',
        icon: '💡',
        color: '#8b5cf6',
        domain: 'scientific',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'hypothesis_generator',
            'falsifier',
            'evidence_finder',
            'synthesizer',
            'critic',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Test hypothesis', 'Validate claim', 'Research review'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-peer-review',
        name: 'Peer Review Board',
        description: 'Academic paper peer review',
        icon: '🔍',
        color: '#10b981',
        domain: 'scientific',
        defaultStrategy: 'review',
        recommendedRoles: ['reviewer_1', 'reviewer_2', 'reviewer_3', 'editor', 'author'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Paper review', 'Grant review', 'Conference submission'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-experiment',
        name: 'Experimental Design Team',
        description: 'Design rigorous experiments',
        icon: '🧪',
        color: '#06b6d4',
        domain: 'scientific',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'methodologist',
            'statistician',
            'domain_expert',
            'ethicist',
            'pilot_tester',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Experiment design', 'Protocol writing', 'Methodology review'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-literature',
        name: 'Literature Review Crew',
        description: 'Comprehensive literature review',
        icon: '📚',
        color: '#f59e0b',
        domain: 'scientific',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'search_specialist',
            'summarizer',
            'synthesizer',
            'citation_checker',
            'gap_analyst',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Literature review', 'Systematic review', 'Background research'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-data-science',
        name: 'Data Science Squad',
        description: 'End-to-end data project',
        icon: '📊',
        color: '#a855f7',
        domain: 'scientific',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'data_engineer',
            'data_scientist',
            'ml_engineer',
            'domain_expert',
            'visualizer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Data analysis', 'ML pipeline', 'Data visualization'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-theory',
        name: 'Theory Development Group',
        description: 'Develop new theoretical frameworks',
        icon: '🧠',
        color: '#6366f1',
        domain: 'scientific',
        defaultStrategy: 'consensus',
        recommendedRoles: ['theorist', 'mathematician', 'logician', 'critic', 'synthesizer'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Theory building', 'Model development', 'Framework design'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-replication',
        name: 'Replication Team',
        description: 'Replicate published studies',
        icon: '🔄',
        color: '#14b8a6',
        domain: 'scientific',
        defaultStrategy: 'sequential',
        recommendedRoles: ['original_author', 'replicator', 'statistician', 'independent_reviewer'],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Study replication', 'Result verification', 'Method validation'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-interdisciplinary',
        name: 'Interdisciplinary Panel',
        description: 'Cross-disciplinary problem solving',
        icon: '🌐',
        color: '#ec4899',
        domain: 'scientific',
        defaultStrategy: 'debate',
        recommendedRoles: ['physicist', 'biologist', 'chemist', 'mathematician', 'philosopher'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Cross-disciplinary problem', 'Complex research', 'Innovation'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-grant',
        name: 'Grant Writing Team',
        description: 'Write competitive grant proposals',
        icon: '💰',
        color: '#10b981',
        domain: 'scientific',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'principal_investigator',
            'grant_writer',
            'budget_analyst',
            'research_designer',
            'reviewer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Grant writing', 'Proposal development', 'Budget planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-conference',
        name: 'Conference Panel',
        description: 'Academic conference panel discussion',
        icon: '🎤',
        color: '#f97316',
        domain: 'scientific',
        defaultStrategy: 'round-robin',
        recommendedRoles: [
            'moderator',
            'subject_expert_1',
            'subject_expert_2',
            'subject_expert_3',
            'devils_advocate',
            'summarizer',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Panel discussion', 'Conference session', 'Expert roundtable'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-phd-defense',
        name: 'PhD Defense Committee',
        description: 'PhD defense simulation',
        icon: '🎓',
        color: '#8b5cf6',
        domain: 'scientific',
        defaultStrategy: 'review',
        recommendedRoles: [
            'advisor',
            'committee_member_1',
            'committee_member_2',
            'external_examiner',
            'chair',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['PhD defense', 'Thesis review', 'Oral examination'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-meta-analysis',
        name: 'Meta-Analysis Team',
        description: 'Systematic review and meta-analysis',
        icon: '📈',
        color: '#3b82f6',
        domain: 'scientific',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'search_specialist',
            'data_extractor',
            'statistician',
            'bias_auditor',
            'writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Meta-analysis', 'Systematic review', 'Evidence synthesis'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-innovation',
        name: 'Innovation Lab',
        description: 'Brainstorm breakthrough ideas',
        icon: '💡',
        color: '#f59e0b',
        domain: 'scientific',
        defaultStrategy: 'swarm',
        recommendedRoles: ['visionary', 'technologist', 'domain_expert', 'designer', 'prototyper'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Innovation session', 'Brainstorming', 'Idea generation'],
        isBuiltin: true,
    },
    {
        id: 'tt-sci-citizen',
        name: 'Citizen Science Coordination',
        description: 'Coordinate citizen science projects',
        icon: '🤝',
        color: '#14b8a6',
        domain: 'scientific',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'project_lead',
            'communications',
            'data_validator',
            'domain_expert',
            'community_manager',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Citizen science', 'Community research', 'Crowdsourced data'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Medical (12)
    // ════════════════════════════════════════════
    {
        id: 'tt-med-diagnostic',
        name: 'Diagnostic Council',
        description: 'Complex multi-disciplinary diagnosis',
        icon: '🩺',
        color: '#ef4444',
        domain: 'medical',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'diagnostician',
            'radiologist',
            'pathologist',
            'pharmacologist',
            'specialist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Complex diagnosis', 'Second opinion', 'Case consultation'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-treatment',
        name: 'Treatment Planning Team',
        description: 'Multi-modal treatment plan',
        icon: '💊',
        color: '#f97316',
        domain: 'medical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'attending_physician',
            'surgeon',
            'oncologist',
            'radiologist',
            'patient_advocate',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Treatment planning', 'Care coordination', 'Multimodal therapy'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-case-conference',
        name: 'Case Conference',
        description: 'Weekly case conference',
        icon: '📋',
        color: '#3b82f6',
        domain: 'medical',
        defaultStrategy: 'round-robin',
        recommendedRoles: [
            'presenting_physician',
            'discussant_1',
            'discussant_2',
            'pathologist',
            'radiologist',
            'chair',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Case conference', 'Peer consultation', 'Education'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-mortality',
        name: 'Morbidity & Mortality Review',
        description: 'M&M conference for learning',
        icon: '🔍',
        color: '#dc2626',
        domain: 'medical',
        defaultStrategy: 'review',
        recommendedRoles: [
            'case_presenter',
            'reviewer',
            'quality_officer',
            'systems_analyst',
            'patient_safety_officer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['M&M review', 'Quality improvement', 'Patient safety'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-drug-dev',
        name: 'Drug Development Team',
        description: 'New drug development pipeline',
        icon: '🧬',
        color: '#8b5cf6',
        domain: 'medical',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'pharmacologist',
            'toxicologist',
            'clinical_researcher',
            'statistician',
            'regulatory_specialist',
            'medical_writer',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Drug development', 'Clinical trial prep', 'Regulatory submission'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-clinical-trial',
        name: 'Clinical Trial Design',
        description: 'Design clinical trial protocol',
        icon: '📋',
        color: '#10b981',
        domain: 'medical',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'principal_investigator',
            'biostatistician',
            'ethicist',
            'protocol_writer',
            'safety_officer',
            'data_manager',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Trial design', 'Protocol writing', 'IRB submission'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-tumor-board',
        name: 'Tumor Board',
        description: 'Cancer treatment decision',
        icon: '🎗️',
        color: '#a855f7',
        domain: 'medical',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'medical_oncologist',
            'surgical_oncologist',
            'radiation_oncologist',
            'pathologist',
            'radiologist',
            'nurse_navigator',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Cancer treatment', 'Multidisciplinary decision', 'Care planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-ethics',
        name: 'Ethics Committee',
        description: 'Medical ethics consultation',
        icon: '⚖️',
        color: '#6366f1',
        domain: 'medical',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'ethicist',
            'physician',
            'legal_counsel',
            'patient_advocate',
            'religious_counselor',
            'community_member',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Ethics consultation', 'Policy review', 'Case ethics'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-public-health',
        name: 'Public Health Response',
        description: 'Outbreak response coordination',
        icon: '🌍',
        color: '#f59e0b',
        domain: 'medical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'epidemiologist',
            'public_health_officer',
            'communications',
            'policy_advisor',
            'logistics',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Outbreak response', 'Public health alert', 'Health policy'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-rehab',
        name: 'Rehabilitation Team',
        description: 'Multi-disciplinary rehab plan',
        icon: '💪',
        color: '#06b6d4',
        domain: 'medical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'physiatrist',
            'physical_therapist',
            'occupational_therapist',
            'speech_therapist',
            'social_worker',
            'patient',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Rehab planning', 'Functional assessment', 'Care coordination'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-palliative',
        name: 'Palliative Care Team',
        description: 'End-of-life care planning',
        icon: '🕊️',
        color: '#14b8a6',
        domain: 'medical',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'palliative_care_physician',
            'nurse',
            'social_worker',
            'chaplain',
            'bereavement_counselor',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Palliative care', 'Advance care planning', 'Family support'],
        isBuiltin: true,
    },
    {
        id: 'tt-med-education',
        name: 'Medical Education Team',
        description: 'Medical education scenarios',
        icon: '🎓',
        color: '#3b82f6',
        domain: 'medical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'attending',
            'resident',
            'medical_student',
            'simulation_specialist',
            'curriculum_designer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Medical education', 'Simulation training', 'Curriculum design'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Technical (15)
    // ════════════════════════════════════════════
    {
        id: 'tt-tech-dev',
        name: 'Software Development Team',
        description: 'Full-stack product development',
        icon: '💻',
        color: '#3b82f6',
        domain: 'technical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'architect',
            'frontend_dev',
            'backend_dev',
            'devops',
            'qa_engineer',
            'product_owner',
            'designer',
            'security',
        ],
        minRoles: 3,
        maxRoles: 10,
        useCases: ['Product development', 'Feature implementation', 'Sprint execution'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-code-review',
        name: 'Code Review Swarm',
        description: 'Comprehensive PR review',
        icon: '🔍',
        color: '#8b5cf6',
        domain: 'technical',
        defaultStrategy: 'review',
        recommendedRoles: [
            'senior_dev_1',
            'senior_dev_2',
            'senior_dev_3',
            'security',
            'performance',
            'ux',
            'architect',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Code review', 'PR review', 'Architecture review'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-architecture',
        name: 'Architecture Review Board',
        description: 'Architecture decision review',
        icon: '🏗️',
        color: '#f59e0b',
        domain: 'technical',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'system_architect',
            'security_engineer',
            'performance_engineer',
            'db_expert',
            'ux_architect',
            'domain_expert',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Architecture decision', 'Technology choice', 'Design review'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-incident',
        name: 'Incident Response (SRE)',
        description: 'Production incident response',
        icon: '🚨',
        color: '#ef4444',
        domain: 'technical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['incident_commander', 'sre', 'oncall_dev', 'comms', 'manager'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Incident response', 'Outage management', 'Postmortem'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-bug-investigation',
        name: 'Bug Investigation Team',
        description: 'Track down elusive bugs',
        icon: '🐛',
        color: '#f97316',
        domain: 'technical',
        defaultStrategy: 'pipeline',
        recommendedRoles: ['reproducer', 'debugger', 'log_analyst', 'fix_developer', 'test_writer'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Bug investigation', 'Root cause analysis', 'Hotfix'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-migration',
        name: 'Migration Team',
        description: 'System migration planning',
        icon: '🔄',
        color: '#06b6d4',
        domain: 'technical',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'migration_architect',
            'db_specialist',
            'backend_dev',
            'qa',
            'rollback_planner',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['System migration', 'Platform upgrade', 'Data migration'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-security',
        name: 'Security Audit Team',
        description: 'Security assessment',
        icon: '🛡️',
        color: '#dc2626',
        domain: 'technical',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'pentester',
            'architect',
            'code_reviewer',
            'compliance_officer',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Security audit', 'Penetration test', 'Compliance review'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-perf',
        name: 'Performance Optimization',
        description: 'Performance bottleneck analysis',
        icon: '⚡',
        color: '#10b981',
        domain: 'technical',
        defaultStrategy: 'parallel',
        recommendedRoles: ['profiler', 'architect', 'db_tuner', 'frontend_optimizer', 'infra'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Performance optimization', 'Load testing', 'Bottleneck analysis'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-api-design',
        name: 'API Design Team',
        description: 'Design new APIs',
        icon: '🔌',
        color: '#8b5cf6',
        domain: 'technical',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'api_architect',
            'backend_dev',
            'frontend_dev',
            'docs_writer',
            'sdk_generator',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['API design', 'Specification', 'SDK development'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-debt',
        name: 'Tech Debt Remediation',
        description: 'Address technical debt',
        icon: '🔧',
        color: '#f59e0b',
        domain: 'technical',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'architect',
            'refactoring_specialist',
            'test_writer',
            'risk_analyst',
            'pm',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Tech debt reduction', 'Refactoring', 'Code quality'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-onboarding',
        name: 'Onboarding Team',
        description: 'Onboard new team members',
        icon: '👋',
        color: '#14b8a6',
        domain: 'technical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['tech_lead', 'mentor', 'documentation', 'buddy', 'manager'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['New hire onboarding', 'Knowledge transfer', 'Mentorship'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-hackathon',
        name: 'Hackathon Team',
        description: 'Hackathon project',
        icon: '🏆',
        color: '#ec4899',
        domain: 'technical',
        defaultStrategy: 'swarm',
        recommendedRoles: ['idea_person', 'coder', 'designer', 'pitcher', 'hustler'],
        minRoles: 2,
        maxRoles: 6,
        useCases: ['Hackathon', 'Rapid prototyping', 'MVP building'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-oss',
        name: 'Open Source Maintainers',
        description: 'OSS project management',
        icon: '🌐',
        color: '#3b82f6',
        domain: 'technical',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'maintainer',
            'contributor',
            'issue_triage',
            'documentation',
            'community_manager',
        ],
        minRoles: 2,
        maxRoles: 7,
        useCases: ['OSS maintenance', 'Community management', 'Release management'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-devops',
        name: 'DevOps Pipeline Team',
        description: 'Build CI/CD pipeline',
        icon: '🚀',
        color: '#06b6d4',
        domain: 'technical',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'cicd_specialist',
            'infra_architect',
            'security',
            'monitoring',
            'cost_optimizer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['CI/CD pipeline', 'Infrastructure as code', 'Monitoring setup'],
        isBuiltin: true,
    },
    {
        id: 'tt-tech-ai-ml',
        name: 'AI/ML Team',
        description: 'ML product development',
        icon: '🤖',
        color: '#a855f7',
        domain: 'technical',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'ml_researcher',
            'data_engineer',
            'mlops',
            'domain_expert',
            'ethics_officer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['ML model development', 'Training pipeline', 'Model deployment'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Legal (10)
    // ════════════════════════════════════════════
    {
        id: 'tt-legal-litigation',
        name: 'Litigation Team',
        description: 'Trial preparation and strategy',
        icon: '⚖️',
        color: '#6366f1',
        domain: 'legal',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'lead_attorney',
            'associate',
            'paralegal',
            'expert_witness',
            'investigator',
            'strategist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Trial prep', 'Case strategy', 'Brief writing'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-negotiation',
        name: 'Contract Negotiation',
        description: 'Contract negotiation',
        icon: '🤝',
        color: '#10b981',
        domain: 'legal',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'lead_negotiator',
            'subject_expert',
            'legal_counsel',
            'risk_analyst',
            'relationship_manager',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Contract negotiation', 'Deal structuring', 'Terms review'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-due-diligence',
        name: 'Due Diligence Team',
        description: 'M&A due diligence',
        icon: '🔍',
        color: '#3b82f6',
        domain: 'legal',
        defaultStrategy: 'parallel',
        recommendedRoles: ['financial_analyst', 'legal', 'tech', 'hr', 'strategy', 'risk'],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['M&A due diligence', 'Vendor assessment', 'Compliance check'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-compliance',
        name: 'Compliance Audit',
        description: 'Regulatory compliance audit',
        icon: '✅',
        color: '#14b8a6',
        domain: 'legal',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'compliance_officer',
            'auditor',
            'subject_expert',
            'report_writer',
            'fix_planner',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Compliance audit', 'Regulatory review', 'Gap analysis'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-ip',
        name: 'IP Strategy Team',
        description: 'IP portfolio strategy',
        icon: '💡',
        color: '#a855f7',
        domain: 'legal',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'patent_attorney',
            'inventor',
            'prior_art_researcher',
            'tech_expert',
            'business_strategist',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['IP strategy', 'Patent filing', 'Portfolio management'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-research',
        name: 'Legal Research Team',
        description: 'Legal research pipeline',
        icon: '📚',
        color: '#8b5cf6',
        domain: 'legal',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'research_attorney',
            'database_specialist',
            'summarizer',
            'strategist',
            'citator',
        ],
        minRoles: 2,
        maxRoles: 6,
        useCases: ['Legal research', 'Case law analysis', 'Memorandum writing'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-mediation',
        name: 'Mediation Panel',
        description: 'Mediation session',
        icon: '🕊️',
        color: '#f59e0b',
        domain: 'legal',
        defaultStrategy: 'round-robin',
        recommendedRoles: [
            'mediator',
            'party_1_rep',
            'party_2_rep',
            'expert_advisor',
            'note_taker',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Mediation', 'Dispute resolution', 'Facilitated negotiation'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-policy',
        name: 'Policy Drafting Team',
        description: 'Draft policy/legislation',
        icon: '📝',
        color: '#3b82f6',
        domain: 'legal',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'policy_expert',
            'legal_counsel',
            'stakeholder_rep',
            'writer',
            'reviewer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Policy drafting', 'Legislation writing', 'Regulatory framework'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-regulatory',
        name: 'Regulatory Affairs',
        description: 'Regulatory submission',
        icon: '📋',
        color: '#f97316',
        domain: 'legal',
        defaultStrategy: 'pipeline',
        recommendedRoles: ['regulatory_specialist', 'scientist', 'legal', 'writer', 'liaison'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Regulatory submission', 'FDA filing', 'Compliance documentation'],
        isBuiltin: true,
    },
    {
        id: 'tt-legal-mock-trial',
        name: 'Mock Trial Team',
        description: 'Trial preparation and practice',
        icon: '🎭',
        color: '#ef4444',
        domain: 'legal',
        defaultStrategy: 'debate',
        recommendedRoles: ['judge', 'prosecutor', 'defense', 'witness_1', 'witness_2', 'jury'],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Mock trial', 'Argument practice', 'Witness prep'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Business (15)
    // ════════════════════════════════════════════
    {
        id: 'tt-biz-executive',
        name: 'Executive Team',
        description: 'Strategic decision making',
        icon: '👔',
        color: '#3b82f6',
        domain: 'business',
        defaultStrategy: 'consensus',
        recommendedRoles: ['ceo', 'cfo', 'cto', 'coo', 'cmo', 'chro'],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Strategic decision', 'Board meeting', 'Company direction'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-startup',
        name: 'Startup Advisory',
        description: 'Startup strategy and mentoring',
        icon: '🚀',
        color: '#10b981',
        domain: 'business',
        defaultStrategy: 'round-robin',
        recommendedRoles: ['ceo_coach', 'cto_advisor', 'marketing', 'legal', 'finance', 'product'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Startup strategy', 'Mentorship', 'Growth planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-product-launch',
        name: 'Product Launch Team',
        description: 'Go-to-market execution',
        icon: '🎯',
        color: '#ef4444',
        domain: 'business',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'pm',
            'marketing',
            'sales',
            'customer_success',
            'engineer',
            'designer',
            'pr',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Product launch', 'GTM strategy', 'Release coordination'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-ma',
        name: 'M&A Team',
        description: 'Merger and acquisition',
        icon: '🤝',
        color: '#8b5cf6',
        domain: 'business',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['strategy', 'financial_analyst', 'legal', 'tech', 'hr', 'comms'],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['M&A execution', 'Due diligence', 'Post-merger integration'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-crisis',
        name: 'Business Crisis Management',
        description: 'Business crisis response',
        icon: '🚨',
        color: '#dc2626',
        domain: 'business',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['incident_commander', 'comms', 'legal', 'tech_lead', 'hr', 'executive'],
        minRoles: 4,
        maxRoles: 7,
        useCases: ['Crisis response', 'Reputation management', 'Recovery'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-strategic-planning',
        name: 'Strategic Planning',
        description: 'Strategic plan development',
        icon: '📈',
        color: '#3b82f6',
        domain: 'business',
        defaultStrategy: 'consensus',
        recommendedRoles: ['strategist', 'analyst', 'market_researcher', 'finance', 'visionary'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Strategic planning', 'Annual planning', 'OKR setting'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-investment',
        name: 'Investment Committee',
        description: 'Investment decision',
        icon: '💰',
        color: '#10b981',
        domain: 'business',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'chair',
            'investment_analyst',
            'risk_manager',
            'domain_expert',
            'compliance',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Investment decision', 'Portfolio review', 'Risk assessment'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-sales',
        name: 'Sales Pursuit Team',
        description: 'Major deal pursuit',
        icon: '🤝',
        color: '#f59e0b',
        domain: 'business',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'account_manager',
            'sales_engineer',
            'solution_architect',
            'pricing',
            'executive_sponsor',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Sales pursuit', 'RFP response', 'Deal closing'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-customer-success',
        name: 'Customer Success Pod',
        description: 'Customer success management',
        icon: '🌟',
        color: '#14b8a6',
        domain: 'business',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'csm',
            'onboarding_specialist',
            'support',
            'product_expert',
            'escalation_manager',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Customer success', 'Onboarding', 'Account management'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-marketing',
        name: 'Marketing Campaign',
        description: 'Campaign development',
        icon: '📢',
        color: '#ec4899',
        domain: 'business',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'creative_director',
            'copywriter',
            'designer',
            'data_analyst',
            'channel_specialist',
            'strategist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Campaign development', 'Content strategy', 'Media planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-brand',
        name: 'Brand Strategy',
        description: 'Brand positioning',
        icon: '🎯',
        color: '#a855f7',
        domain: 'business',
        defaultStrategy: 'swarm',
        recommendedRoles: [
            'brand_strategist',
            'designer',
            'market_researcher',
            'copywriter',
            'cultural_analyst',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Brand positioning', 'Rebranding', 'Brand guidelines'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-pricing',
        name: 'Pricing Strategy',
        description: 'Pricing decisions',
        icon: '💰',
        color: '#f97316',
        domain: 'business',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'pricing_analyst',
            'economist',
            'product',
            'finance',
            'sales',
            'competitor_analyst',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Pricing strategy', 'Monetization', 'Revenue optimization'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-partnership',
        name: 'Partnership Team',
        description: 'Strategic partnership deal',
        icon: '🤝',
        color: '#3b82f6',
        domain: 'business',
        defaultStrategy: 'sequential',
        recommendedRoles: ['bd_lead', 'legal', 'tech', 'strategy', 'finance'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Partnership deal', 'Alliance building', 'Channel development'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-board',
        name: 'Board Meeting',
        description: 'Board of directors meeting',
        icon: '🏛️',
        color: '#6366f1',
        domain: 'business',
        defaultStrategy: 'debate',
        recommendedRoles: ['chair', 'ceo', 'independent_directors', 'secretary', 'treasurer'],
        minRoles: 4,
        maxRoles: 10,
        useCases: ['Board meeting', 'Governance', 'Strategic oversight'],
        isBuiltin: true,
    },
    {
        id: 'tt-biz-innovation',
        name: 'Innovation Skunkworks',
        description: 'Disruptive innovation',
        icon: '💡',
        color: '#f59e0b',
        domain: 'business',
        defaultStrategy: 'swarm',
        recommendedRoles: [
            'innovator',
            'designer',
            'engineer',
            'business_modeler',
            'customer_interviewer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Innovation', 'New product ideas', 'Disruptive strategy'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Creative (12)
    // ════════════════════════════════════════════
    {
        id: 'tt-creative-film',
        name: 'Film Production',
        description: 'Film production pipeline',
        icon: '🎬',
        color: '#ef4444',
        domain: 'creative',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'director',
            'writer',
            'cinematographer',
            'editor',
            'composer',
            'production_designer',
            'producer',
        ],
        minRoles: 4,
        maxRoles: 10,
        useCases: ['Film production', 'Video creation', 'Story development'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-editorial',
        name: 'Editorial Board',
        description: 'Publication pipeline',
        icon: '📝',
        color: '#3b82f6',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'editor_in_chief',
            'section_editor',
            'copy_editor',
            'fact_checker',
            'layout_designer',
            'photo_editor',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Publishing', 'Editorial planning', 'Content production'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-book',
        name: 'Book Publishing',
        description: 'Book publication pipeline',
        icon: '📚',
        color: '#8b5cf6',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'author',
            'editor',
            'literary_agent',
            'designer',
            'marketer',
            'publicist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Book publishing', 'Manuscript development', 'Author platform'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-music',
        name: 'Music Production',
        description: 'Music production pipeline',
        icon: '🎵',
        color: '#ec4899',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'producer',
            'songwriter',
            'audio_engineer',
            'musician',
            'arranger',
            'mastering_engineer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Music production', 'Album creation', 'Sound design'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-game',
        name: 'Game Studio',
        description: 'Game development',
        icon: '🎮',
        color: '#a855f7',
        domain: 'creative',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'game_designer',
            'programmer',
            'artist',
            'writer',
            'composer',
            'qa',
            'producer',
        ],
        minRoles: 4,
        maxRoles: 10,
        useCases: ['Game development', 'Game design', 'Level creation'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-animation',
        name: 'Animation Studio',
        description: 'Animation production',
        icon: '🎨',
        color: '#f59e0b',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'director',
            'storyboard_artist',
            'animator',
            'voice_director',
            'sound_designer',
            'editor',
        ],
        minRoles: 3,
        maxRoles: 8,
        useCases: ['Animation production', 'Motion graphics', 'Character animation'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-theater',
        name: 'Theater Production',
        description: 'Theater production',
        icon: '🎭',
        color: '#f97316',
        domain: 'creative',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'director',
            'playwright',
            'set_designer',
            'costume_designer',
            'lighting_designer',
            'stage_manager',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Theater production', 'Play development', 'Stage design'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-podcast',
        name: 'Podcast Team',
        description: 'Podcast production',
        icon: '🎤',
        color: '#06b6d4',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: ['host', 'cohost', 'producer', 'editor', 'researcher', 'sound_designer'],
        minRoles: 2,
        maxRoles: 6,
        useCases: ['Podcast production', 'Episode planning', 'Audio editing'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-photography',
        name: 'Photography Crew',
        description: 'Photo shoot production',
        icon: '📸',
        color: '#3b82f6',
        domain: 'creative',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'photographer',
            'art_director',
            'stylist',
            'lighting_tech',
            'photo_editor',
            'producer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Photo shoot', 'Campaign photography', 'Editorial shoot'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-fashion',
        name: 'Fashion Design',
        description: 'Fashion collection development',
        icon: '👗',
        color: '#ec4899',
        domain: 'creative',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'creative_director',
            'designer',
            'pattern_maker',
            'stylist',
            'production_manager',
            'buyer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Fashion collection', 'Seasonal line', 'Fashion show'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-architecture',
        name: 'Architecture Studio',
        description: 'Building design',
        icon: '🏛️',
        color: '#8b5cf6',
        domain: 'creative',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'lead_architect',
            'designer',
            'engineer',
            'sustainability_specialist',
            'interior_designer',
            'project_manager',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Building design', 'Architecture competition', 'Urban planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-creative-advertising',
        name: 'Ad Agency Creative',
        description: 'Advertising campaign',
        icon: '📢',
        color: '#f59e0b',
        domain: 'creative',
        defaultStrategy: 'swarm',
        recommendedRoles: [
            'creative_director',
            'copywriter',
            'art_director',
            'strategist',
            'producer',
            'pitch_specialist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Ad campaign', 'Creative concept', 'Pitch presentation'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Educational (10)
    // ════════════════════════════════════════════
    {
        id: 'tt-edu-curriculum',
        name: 'Curriculum Design Team',
        description: 'Course design',
        icon: '📚',
        color: '#f59e0b',
        domain: 'educational',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'curriculum_designer',
            'subject_expert',
            'pedagogy_specialist',
            'assessment_designer',
            'tech_integrator',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Course design', 'Curriculum development', 'Learning objectives'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-tutoring',
        name: 'Tutoring Squad',
        description: 'Personalized tutoring',
        icon: '🎓',
        color: '#3b82f6',
        domain: 'educational',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'subject_tutor',
            'skills_coach',
            'motivator',
            'assessor',
            'parent_liaison',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Personalized tutoring', 'Homework help', 'Exam preparation'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-mentorship',
        name: 'Research Mentorship',
        description: 'PhD mentoring',
        icon: '🧪',
        color: '#8b5cf6',
        domain: 'educational',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'pi',
            'postdoc_advisor',
            'phd_mentor',
            'peer_mentor',
            'career_counselor',
        ],
        minRoles: 2,
        maxRoles: 6,
        useCases: ['PhD mentoring', 'Research guidance', 'Career development'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-exam',
        name: 'Exam Preparation Team',
        description: 'Exam preparation',
        icon: '📝',
        color: '#ef4444',
        domain: 'educational',
        defaultStrategy: 'parallel',
        recommendedRoles: [
            'content_expert',
            'test_strategist',
            'anxiety_coach',
            'time_manager',
            'practice_designer',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Exam prep', 'Test strategy', 'Study planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-distance',
        name: 'Distance Learning Pod',
        description: 'Online course delivery',
        icon: '💻',
        color: '#06b6d4',
        domain: 'educational',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'instructor',
            'tech_support',
            'discussion_facilitator',
            'assignment_grader',
            'student_success_coach',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Online course', 'Distance learning', 'Virtual classroom'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-assessment',
        name: 'Educational Assessment',
        description: 'Design and evaluate assessments',
        icon: '✅',
        color: '#10b981',
        domain: 'educational',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'assessment_designer',
            'statistician',
            'subject_expert',
            'fairness_auditor',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Assessment design', 'Test validation', 'Grading rubric'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-advising',
        name: 'Academic Advising',
        description: 'Student academic advising',
        icon: '🧭',
        color: '#14b8a6',
        domain: 'educational',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'advisor',
            'career_counselor',
            'subject_specialist',
            'registrar_liaison',
            'student_advocate',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Academic advising', 'Course selection', 'Career guidance'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-research',
        name: 'Educational Research',
        description: 'Education research',
        icon: '🔬',
        color: '#3b82f6',
        domain: 'educational',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'researcher',
            'statistician',
            'classroom_observer',
            'teacher_interviewer',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Education research', 'Classroom study', 'Policy evaluation'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-training',
        name: 'Workplace Training Team',
        description: 'Corporate training',
        icon: '🏢',
        color: '#8b5cf6',
        domain: 'educational',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'instructional_designer',
            'subject_expert',
            'trainer',
            'materials_designer',
            'evaluator',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Corporate training', 'Professional development', 'Workshop design'],
        isBuiltin: true,
    },
    {
        id: 'tt-edu-language',
        name: 'Language Learning Pod',
        description: 'Language learning',
        icon: '🗣️',
        color: '#ec4899',
        domain: 'educational',
        defaultStrategy: 'round-robin',
        recommendedRoles: [
            'conversation_partner',
            'grammar_coach',
            'pronunciation_tutor',
            'cultural_guide',
            'progress_tracker',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Language learning', 'Conversation practice', 'Cultural immersion'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Crisis (8)
    // ════════════════════════════════════════════
    {
        id: 'tt-crisis-comms',
        name: 'Crisis Communications Team',
        description: 'PR crisis response',
        icon: '📢',
        color: '#ef4444',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'pr_lead',
            'legal',
            'executive',
            'social_media',
            'customer_comms',
            'internal_comms',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['PR crisis', 'Media response', 'Stakeholder communication'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-disaster',
        name: 'Disaster Response',
        description: 'Emergency disaster response',
        icon: '🚨',
        color: '#dc2626',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'incident_commander',
            'logistics',
            'medical',
            'comms',
            'safety',
            'liaison',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Disaster response', 'Emergency management', 'Relief coordination'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-cyber',
        name: 'Cybersecurity Incident',
        description: 'Cyber breach response',
        icon: '🛡️',
        color: '#dc2626',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'incident_commander',
            'forensics',
            'comms',
            'legal',
            'tech_lead',
            'executive',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Cyber incident', 'Breach response', 'Forensic investigation'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-recall',
        name: 'Product Recall Team',
        description: 'Product recall coordination',
        icon: '📦',
        color: '#f97316',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'recall_coordinator',
            'legal',
            'comms',
            'logistics',
            'customer_service',
            'quality',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Product recall', 'Quality incident', 'Consumer safety'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-financial',
        name: 'Financial Crisis Team',
        description: 'Financial crisis management',
        icon: '💰',
        color: '#ef4444',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['cfo', 'treasurer', 'legal', 'comms', 'banker', 'restructuring_advisor'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Financial crisis', 'Liquidity crunch', 'Restructuring'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-public-health',
        name: 'Public Health Emergency',
        description: 'Health emergency response',
        icon: '🏥',
        color: '#ef4444',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'public_health_officer',
            'epidemiologist',
            'comms',
            'policy',
            'logistics',
            'medical',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Health emergency', 'Pandemic response', 'Vaccination campaign'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-reputation',
        name: 'Reputation Recovery',
        description: 'Reputation repair',
        icon: '🌟',
        color: '#f59e0b',
        domain: 'crisis',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'pr_strategist',
            'crisis_comms',
            'seo_specialist',
            'social_media',
            'legal',
            'customer_outreach',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Reputation repair', 'Brand recovery', 'Trust rebuilding'],
        isBuiltin: true,
    },
    {
        id: 'tt-crisis-continuity',
        name: 'Business Continuity',
        description: 'Business continuity planning',
        icon: '🔄',
        color: '#3b82f6',
        domain: 'crisis',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['bc_manager', 'it', 'facilities', 'hr', 'comms', 'operations'],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Business continuity', 'Disaster recovery', 'BCP testing'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Ethical (5)
    // ════════════════════════════════════════════
    {
        id: 'tt-eth-ai-review',
        name: 'AI Ethics Review',
        description: 'AI system safety audit',
        icon: '🤖',
        color: '#8b5cf6',
        domain: 'ethical',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'ethicist',
            'bias_auditor',
            'security_engineer',
            'domain_expert',
            'red_team',
            'blue_team',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['AI audit', 'Bias testing', 'Safety review'],
        isBuiltin: true,
    },
    {
        id: 'tt-eth-bioethics',
        name: 'Bioethics Panel',
        description: 'Bioethics consultation',
        icon: '🧬',
        color: '#10b981',
        domain: 'ethical',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'bioethicist',
            'scientist',
            'religious_representative',
            'patient_advocate',
            'legal',
            'philosopher',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Bioethics consultation', 'Research ethics', 'Clinical ethics'],
        isBuiltin: true,
    },
    {
        id: 'tt-eth-civic',
        name: 'Civic Policy Panel',
        description: 'Public policy',
        icon: '🏛️',
        color: '#3b82f6',
        domain: 'ethical',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'policy_expert',
            'economist',
            'sociologist',
            'legal',
            'community_rep',
            'ethicist',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Public policy', 'Civic engagement', 'Community decision'],
        isBuiltin: true,
    },
    {
        id: 'tt-eth-environmental',
        name: 'Environmental Review',
        description: 'Environmental impact decision',
        icon: '🌍',
        color: '#22c55e',
        domain: 'ethical',
        defaultStrategy: 'debate',
        recommendedRoles: [
            'environmental_scientist',
            'economist',
            'policy_expert',
            'industry_rep',
            'community_advocate',
            'legal',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Environmental review', 'Impact assessment', 'Sustainability'],
        isBuiltin: true,
    },
    {
        id: 'tt-eth-data',
        name: 'Data Ethics Board',
        description: 'Data ethics decision',
        icon: '📊',
        color: '#6366f1',
        domain: 'ethical',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'data_scientist',
            'privacy_expert',
            'legal',
            'ethicist',
            'user_advocate',
            'security',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Data ethics', 'Privacy review', 'Consent framework'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Investigation (5)
    // ════════════════════════════════════════════
    {
        id: 'tt-investigation-team',
        name: 'Investigation Team',
        description: 'Complex investigation',
        icon: '🔍',
        color: '#3b82f6',
        domain: 'investigation',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'lead_detective',
            'forensics',
            'psychologist',
            'tech_specialist',
            'legal_advisor',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Investigation', 'Case analysis', 'Evidence review'],
        isBuiltin: true,
    },
    {
        id: 'tt-investigation-fraud',
        name: 'Fraud Investigation',
        description: 'Financial fraud investigation',
        icon: '💰',
        color: '#ef4444',
        domain: 'investigation',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'forensic_accountant',
            'investigator',
            'data_analyst',
            'legal',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Fraud investigation', 'Financial crime', 'Audit'],
        isBuiltin: true,
    },
    {
        id: 'tt-investigation-compliance',
        name: 'Internal Investigation',
        description: 'Workplace investigation',
        icon: '📋',
        color: '#f97316',
        domain: 'investigation',
        defaultStrategy: 'sequential',
        recommendedRoles: ['investigator', 'hr_rep', 'legal', 'interviewer', 'evidence_analyst'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Internal investigation', 'HR matter', 'Policy violation'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Financial (5)
    // ════════════════════════════════════════════
    {
        id: 'tt-fin-audit',
        name: 'Financial Audit Team',
        description: 'Financial audit',
        icon: '📊',
        color: '#10b981',
        domain: 'financial',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'lead_auditor',
            'auditor',
            'financial_analyst',
            'compliance',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Financial audit', 'Internal controls', 'Compliance review'],
        isBuiltin: true,
    },
    {
        id: 'tt-fin-budget',
        name: 'Budget Planning Team',
        description: 'Annual budget planning',
        icon: '💰',
        color: '#3b82f6',
        domain: 'financial',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'cfo',
            'budget_analyst',
            'department_head',
            'finance_manager',
            'strategist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Budget planning', 'Forecasting', 'Resource allocation'],
        isBuiltin: true,
    },
    {
        id: 'tt-fin-valuation',
        name: 'Valuation Team',
        description: 'Company/asset valuation',
        icon: '📈',
        color: '#8b5cf6',
        domain: 'financial',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'valuation_analyst',
            'financial_modeler',
            'industry_expert',
            'risk_analyst',
            'reviewer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Valuation', 'Fairness opinion', 'Asset pricing'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Editorial & Research (5)
    // ════════════════════════════════════════════
    {
        id: 'tt-editorial-news',
        name: 'Newsroom',
        description: 'Daily news production',
        icon: '📰',
        color: '#3b82f6',
        domain: 'editorial',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'editor_in_chief',
            'reporter',
            'fact_checker',
            'copy_editor',
            'photographer',
            'publisher',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['News production', 'Breaking news', 'Editorial planning'],
        isBuiltin: true,
    },
    {
        id: 'tt-editorial-content',
        name: 'Content Strategy Team',
        description: 'Content marketing strategy',
        icon: '📝',
        color: '#f59e0b',
        domain: 'editorial',
        defaultStrategy: 'consensus',
        recommendedRoles: ['content_strategist', 'seo_specialist', 'writer', 'editor', 'analytics'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Content strategy', 'SEO planning', 'Editorial calendar'],
        isBuiltin: true,
    },
    {
        id: 'tt-editorial-technical',
        name: 'Technical Writing Team',
        description: 'Technical documentation',
        icon: '📖',
        color: '#14b8a6',
        domain: 'editorial',
        defaultStrategy: 'review',
        recommendedRoles: [
            'tech_writer',
            'subject_expert',
            'editor',
            'information_architect',
            'reviewer',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['Documentation', 'API docs', 'User guides'],
        isBuiltin: true,
    },
    {
        id: 'tt-research-market',
        name: 'Market Research Team',
        description: 'Market research and analysis',
        icon: '📊',
        color: '#8b5cf6',
        domain: 'research',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'market_researcher',
            'data_analyst',
            'industry_expert',
            'survey_designer',
            'report_writer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Market research', 'Competitive analysis', 'Consumer insights'],
        isBuiltin: true,
    },
    {
        id: 'tt-research-ux',
        name: 'UX Research Team',
        description: 'User experience research',
        icon: '🔍',
        color: '#ec4899',
        domain: 'research',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'ux_researcher',
            'usability_tester',
            'interviewer',
            'data_analyst',
            'designer',
        ],
        minRoles: 2,
        maxRoles: 5,
        useCases: ['UX research', 'Usability testing', 'User interviews'],
        isBuiltin: true,
    },

    // ════════════════════════════════════════════
    // Specialty (10)
    // ════════════════════════════════════════════
    {
        id: 'tt-specialty-wine',
        name: 'Wine Tasting Panel',
        description: 'Wine evaluation',
        icon: '🍷',
        color: '#a855f7',
        domain: 'custom',
        defaultStrategy: 'round-robin',
        recommendedRoles: ['sommelier', 'viticulturist', 'chemist', 'chef', 'marketing'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Wine evaluation', 'Product tasting', 'Quality assessment'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-sports',
        name: 'Sports Analytics',
        description: 'Team sports strategy',
        icon: '🏆',
        color: '#3b82f6',
        domain: 'custom',
        defaultStrategy: 'hierarchical',
        recommendedRoles: ['statistician', 'coach', 'scout', 'sports_scientist', 'strategist'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Sports analytics', 'Game strategy', 'Player evaluation'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-archaeology',
        name: 'Archeological Dig',
        description: 'Excavation project',
        icon: '⛏️',
        color: '#f59e0b',
        domain: 'custom',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'archeologist',
            'historian',
            'geologist',
            'conservationist',
            'photographer',
            'lab_tech',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Excavation', 'Field research', 'Artifact analysis'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-space',
        name: 'Space Mission Design',
        description: 'Space mission planning',
        icon: '🚀',
        color: '#6366f1',
        domain: 'custom',
        defaultStrategy: 'sequential',
        recommendedRoles: [
            'mission_architect',
            'astrodynamist',
            'engineer',
            'scientist',
            'medical',
            'psychologist',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Mission planning', 'Spacecraft design', 'Trajectory analysis'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-culinary',
        name: 'Culinary R&D Team',
        description: 'New dish development',
        icon: '🍳',
        color: '#f97316',
        domain: 'custom',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'executive_chef',
            'food_scientist',
            'nutritionist',
            'recipe_developer',
            'sensory_analyst',
            'marketing',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Recipe development', 'Menu planning', 'Food innovation'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-hiring',
        name: 'Hiring Panel',
        description: 'Candidate evaluation',
        icon: '👔',
        color: '#10b981',
        domain: 'custom',
        defaultStrategy: 'consensus',
        recommendedRoles: [
            'hiring_manager',
            'tech_lead',
            'hr',
            'culture_fit',
            'skill_assessor',
            'diversity_officer',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Candidate evaluation', 'Interview panel', 'Hiring decision'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-patent',
        name: 'Patent Application',
        description: 'Patent drafting and filing',
        icon: '📜',
        color: '#8b5cf6',
        domain: 'custom',
        defaultStrategy: 'pipeline',
        recommendedRoles: [
            'inventor',
            'patent_attorney',
            'tech_writer',
            'prior_art_researcher',
            'reviewer',
        ],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Patent drafting', 'IP protection', 'Patent filing'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-wedding',
        name: 'Wedding Planning',
        description: 'Wedding coordination',
        icon: '💒',
        color: '#ec4899',
        domain: 'custom',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'wedding_planner',
            'bride',
            'groom',
            'caterer',
            'photographer',
            'florist',
        ],
        minRoles: 3,
        maxRoles: 7,
        useCases: ['Event planning', 'Wedding coordination', 'Vendor management'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-conference',
        name: 'Conference Organizing',
        description: 'Conference organization',
        icon: '🎪',
        color: '#3b82f6',
        domain: 'custom',
        defaultStrategy: 'hierarchical',
        recommendedRoles: [
            'chair',
            'program_committee',
            'local_arrangements',
            'sponsorship',
            'comms',
            'proceedings',
        ],
        minRoles: 4,
        maxRoles: 8,
        useCases: ['Conference planning', 'Event management', 'Program curation'],
        isBuiltin: true,
    },
    {
        id: 'tt-specialty-debate',
        name: 'Debate Tournament',
        description: 'Organize a debate tournament',
        icon: '🎯',
        color: '#ef4444',
        domain: 'custom',
        defaultStrategy: 'tournament',
        recommendedRoles: ['tournament_director', 'judge', 'timekeeper', 'scorer', 'moderator'],
        minRoles: 3,
        maxRoles: 6,
        useCases: ['Debate tournament', 'Competition', 'Event management'],
        isBuiltin: true,
    },
];
