import type { Theme } from '../contracts/ecosystem';

export const THEMES: Theme[] = [
    // ── Aquatic ──
    {
        id: 'coral_reef',
        name: 'Coral Reef',
        description: 'Vibrant tropical reef with colorful fish',
        category: 'aquatic',
        colors: ['#00b4d8', '#0077b6', '#f4a261', '#e76f51'],
        bgGradient: ['#03045e', '#0077b6', '#00b4d8'],
        creatures: ['clownfish', 'angelfish', 'seahorse', 'turtle', 'starfish'],
        unlocksAt: 0,
        isUnlocked: true,
    },
    {
        id: 'deep_ocean',
        name: 'Deep Ocean',
        description: 'Mysterious abyssal zone with glowing creatures',
        category: 'aquatic',
        colors: ['#020024', '#090979', '#00d4ff'],
        bgGradient: ['#000000', '#020024', '#090979'],
        creatures: ['jellyfish', 'squid', 'eel', 'anglerfish', 'nautilus'],
        unlocksAt: 100,
        isUnlocked: false,
    },
    {
        id: 'freshwater',
        name: 'Freshwater Stream',
        description: 'Crystal clear mountain stream',
        category: 'aquatic',
        colors: ['#2ecc71', '#27ae60', '#3498db', '#2980b9'],
        bgGradient: ['#0f2027', '#203a43', '#2c5364'],
        creatures: ['turtle', 'frog', 'koi', 'axolotl', 'dragonfish'],
        unlocksAt: 50,
        isUnlocked: false,
    },
    {
        id: 'arctic',
        name: 'Arctic Waters',
        description: 'Frozen polar sea with ice floes',
        category: 'aquatic',
        colors: ['#dfe6e9', '#b2bec3', '#74b9ff', '#0984e3'],
        bgGradient: ['#0c0c0c', '#1a1a2e', '#16213e'],
        creatures: ['penguin', 'seal', 'narwhal', 'orca', 'walrus'],
        unlocksAt: 200,
        isUnlocked: false,
    },
    {
        id: 'mangrove',
        name: 'Mangrove Forest',
        description: 'Coastal mangrove ecosystem',
        category: 'aquatic',
        colors: ['#2d6a4f', '#40916c', '#52b788', '#95d5b2'],
        bgGradient: ['#0b130e', '#143d22', '#2d6a4f'],
        creatures: ['crab', 'shrimp', 'stingray', 'pelican', 'anemone'],
        unlocksAt: 150,
        isUnlocked: false,
    },

    // ── Terrestrial ──
    {
        id: 'forest',
        name: 'Enchanted Forest',
        description: 'Mystical woodland with hidden pools',
        category: 'terrestrial',
        colors: ['#2ecc71', '#27ae60', '#8e44ad', '#9b59b6'],
        bgGradient: ['#0a1f0a', '#1a3a1a', '#2a5a2a'],
        creatures: ['frog', 'turtle', 'axolotl', 'dragonfish', 'goldfish'],
        unlocksAt: 300,
        isUnlocked: false,
    },
    {
        id: 'desert',
        name: 'Desert Oasis',
        description: 'Rare water in endless sands',
        category: 'terrestrial',
        colors: ['#f4a260', '#e76f51', '#2a9d8f', '#264653'],
        bgGradient: ['#3e1f00', '#6b3a00', '#9b5e00'],
        creatures: ['turtle', 'crab', 'seahorse', 'blowfish', 'molly'],
        unlocksAt: 400,
        isUnlocked: false,
    },
    {
        id: 'savanna',
        name: 'Savanna Waterhole',
        description: 'African savanna watering hole',
        category: 'terrestrial',
        colors: ['#e76f51', '#f4a261', '#e9c46a', '#2a9d8f'],
        bgGradient: ['#4a2800', '#7a4200', '#a46200'],
        creatures: ['pelican', 'turtle', 'flamingo', 'koi', 'betta'],
        unlocksAt: 500,
        isUnlocked: false,
    },
    {
        id: 'japanese',
        name: 'Japanese Garden',
        description: 'Serene koi pond with cherry blossoms',
        category: 'terrestrial',
        colors: ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff'],
        bgGradient: ['#1a0a0a', '#3a1a1a', '#5a2a2a'],
        creatures: ['koi', 'turtle', 'crab', 'starfish', 'guppy'],
        unlocksAt: 350,
        isUnlocked: false,
    },
    {
        id: 'underground',
        name: 'Underground Cavern',
        description: 'Subterranean lake with bioluminescence',
        category: 'terrestrial',
        colors: ['#2dd4bf', '#14b8a6', '#0d9488', '#0f766e'],
        bgGradient: ['#000000', '#0a0a0a', '#141414'],
        creatures: ['axolotl', 'eel', 'cuttlefish', 'nautilus', 'crystal_jelly'],
        unlocksAt: 600,
        isUnlocked: false,
    },

    // ── Fantasy ──
    {
        id: 'fantasy',
        name: 'Fantasy Realm',
        description: 'Magical waters with mythical creatures',
        category: 'fantasy',
        colors: ['#a855f7', '#d946ef', '#ec4899', '#f472b6'],
        bgGradient: ['#1a002e', '#3a005e', '#5a008e'],
        creatures: ['dragon_kite', 'phoenix', 'sea_dragon', 'crystal_jelly', 'great_dragon'],
        unlocksAt: 800,
        isUnlocked: false,
    },
    {
        id: 'steampunk',
        name: 'Steampunk Reservoir',
        description: 'Victorian-industrial aquatic world',
        category: 'fantasy',
        colors: ['#d4a574', '#8b7355', '#4a4a4a', '#2c1810'],
        bgGradient: ['#1a0f08', '#2c1810', '#3d2118'],
        creatures: ['golden_crab', 'nautilus', 'cuttlefish', 'squid', 'puffer'],
        unlocksAt: 700,
        isUnlocked: false,
    },
    {
        id: 'space',
        name: 'Cosmic Ocean',
        description: 'Nebula-filled space with alien creatures',
        category: 'fantasy',
        colors: ['#6c5ce7', '#a29bfe', '#fd79a8', '#00cec9'],
        bgGradient: ['#05001a', '#0a003a', '#10005a'],
        creatures: ['celestial_whale', 'crystal_jelly', 'abyss_angler', 'jellyfish', 'dragonfish'],
        unlocksAt: 1200,
        isUnlocked: false,
    },
    {
        id: 'mythological',
        name: 'Mythological Depths',
        description: 'Greek and Norse mythical waters',
        category: 'fantasy',
        colors: ['#f39c12', '#e74c3c', '#2c3e50', '#f1c40f'],
        bgGradient: ['#1a0000', '#3a0000', '#5a0000'],
        creatures: ['kraken', 'leviathan', 'great_dragon', 'sea_dragon', 'phoenix'],
        unlocksAt: 2000,
        isUnlocked: false,
    },
    {
        id: 'crystal',
        name: 'Crystal Caverns',
        description: 'Geometric crystal formations with light',
        category: 'fantasy',
        colors: ['#e8a0ff', '#a78bfa', '#60a5fa', '#34d399'],
        bgGradient: ['#0a001a', '#1a003a', '#2a005a'],
        creatures: ['crystal_jelly', 'nautilus', 'jellyfish', 'cuttlefish', 'manta'],
        unlocksAt: 900,
        isUnlocked: false,
    },

    // ── Tech ──
    {
        id: 'cyberpunk',
        name: 'Cyberpunk Aquarium',
        description: 'Neon-lit digital sea',
        category: 'tech',
        colors: ['#ff006e', '#8338ec', '#3a86ff', '#00f5d4'],
        bgGradient: ['#0a0020', '#1a0040', '#2a0060'],
        creatures: ['jellyfish', 'eel', 'cuttlefish', 'seahorse2', 'dragonfish'],
        unlocksAt: 500,
        isUnlocked: false,
    },
    {
        id: 'hologram',
        name: 'Holographic Sea',
        description: 'Digital projection with shifting colors',
        category: 'tech',
        colors: ['#06b6d4', '#8b5cf6', '#d946ef', '#f43f5e'],
        bgGradient: ['#0a0a1a', '#1a1a3a', '#2a2a5a'],
        creatures: ['crystal_jelly', 'jellyfish', 'starfish', 'cuttlefish', 'abyss_angler'],
        unlocksAt: 1000,
        isUnlocked: false,
    },
    {
        id: 'circuit',
        name: 'Circuit Board Reef',
        description: 'PCB-inspired underwater world',
        category: 'tech',
        colors: ['#00ff41', '#00cc33', '#009926', '#006619'],
        bgGradient: ['#000500', '#001a00', '#003300'],
        creatures: ['eel', 'crab', 'shrimp', 'lobster', 'golden_crab'],
        unlocksAt: 750,
        isUnlocked: false,
    },
    {
        id: 'matrix',
        name: 'Matrix Ocean',
        description: 'Digital rain meets deep sea',
        category: 'tech',
        colors: ['#00ff00', '#00cc00', '#009900', '#006600'],
        bgGradient: ['#000a00', '#001500', '#002000'],
        creatures: ['jellyfish', 'eel', 'squid', 'manta', 'crystal_jelly'],
        unlocksAt: 1500,
        isUnlocked: false,
    },
    {
        id: 'glitch',
        name: 'Glitch Realm',
        description: 'Bent digital aquatic reality',
        category: 'tech',
        colors: ['#f43f5e', '#a855f7', '#06b6d4', '#eab308'],
        bgGradient: ['#0a000a', '#1a001a', '#2a002a'],
        creatures: ['dragonfish', 'jellyfish', 'cuttlefish', 'squid', 'phoenix'],
        unlocksAt: 1300,
        isUnlocked: false,
    },

    // ── Prehistoric ──
    {
        id: 'prehistoric',
        name: 'Prehistoric Seas',
        description: 'Ancient oceans with primordial life',
        category: 'prehistoric',
        colors: ['#4a5d23', '#6b8e23', '#8fbc8f', '#2f4f4f'],
        bgGradient: ['#0a1a0a', '#1a2a1a', '#2a3a2a'],
        creatures: ['nautilus', 'turtle2', 'eel', 'stingray', 'great_dragon'],
        unlocksAt: 1000,
        isUnlocked: false,
    },
    {
        id: 'jurassic',
        name: 'Jurassic Lagoon',
        description: 'Prehistoric lagoon from dinosaur era',
        category: 'prehistoric',
        colors: ['#228b22', '#32cd32', '#8fbc8f', '#556b2f'],
        bgGradient: ['#0a1a05', '#1a3a0a', '#2a5a0f'],
        creatures: ['turtle2', 'nautilus', 'squid', 'stingray', 'sea_dragon'],
        unlocksAt: 800,
        isUnlocked: false,
    },
    {
        id: 'ice_age',
        name: 'Ice Age Waters',
        description: 'Glacial meltwater from ice age',
        category: 'prehistoric',
        colors: ['#87ceeb', '#b0e0e6', '#e0ffff', '#f0f8ff'],
        bgGradient: ['#0a0a1a', '#1a1a3a', '#2a3a5a'],
        creatures: ['walrus', 'seal', 'penguin', 'turtle2', 'leviathan'],
        unlocksAt: 1100,
        isUnlocked: false,
    },

    // ── Cultural ──
    {
        id: 'aztec',
        name: 'Aztec Floating Gardens',
        description: 'Chinampas with ancient Mesoamerican life',
        category: 'cultural',
        colors: ['#e67e22', '#d35400', '#16a085', '#27ae60'],
        bgGradient: ['#1a0a00', '#3a1a00', '#5a2a00'],
        creatures: ['betta', 'turtle', 'koi', 'crab', 'dragonfish'],
        unlocksAt: 900,
        isUnlocked: false,
    },
    {
        id: 'egyptian',
        name: 'Nile Waters',
        description: 'Ancient Egyptian river life',
        category: 'cultural',
        colors: ['#f1c40f', '#e67e22', '#d35400', '#c0392b'],
        bgGradient: ['#1a1000', '#3a2000', '#5a3000'],
        creatures: ['pelican', 'turtle', 'flamingo', 'crocodile', 'goldfish'],
        unlocksAt: 850,
        isUnlocked: false,
    },
    {
        id: 'pixel',
        name: '8-Bit Aquarium',
        description: 'Retro pixel-art underwater world',
        category: 'cultural',
        colors: ['#ff0000', '#00ff00', '#0000ff', '#ffff00'],
        bgGradient: ['#0a003a', '#1a005a', '#2a007a'],
        creatures: ['goldfish', 'starfish', 'crab', 'seahorse', 'turtle'],
        unlocksAt: 450,
        isUnlocked: false,
    },
    {
        id: 'oriental',
        name: 'Oriental Waters',
        description: 'East Asian ink-wash painting style',
        category: 'cultural',
        colors: ['#e8d5b7', '#d4a373', '#8cb369', '#5c4a72'],
        bgGradient: ['#0a0a05', '#1a1a0a', '#2a2a0f'],
        creatures: ['koi', 'crane', 'turtle', 'dragonfish', 'seahorse2'],
        unlocksAt: 600,
        isUnlocked: false,
    },
    {
        id: 'volcanic',
        name: 'Volcanic Hot Springs',
        description: 'Geothermal waters with minerals',
        category: 'cultural',
        colors: ['#ff4500', '#ff6347', '#8b0000', '#ff8c00'],
        bgGradient: ['#1a0000', '#3a0500', '#5a0a00'],
        creatures: ['lobster', 'crab', 'blowfish', 'anglerfish', 'phoenix'],
        unlocksAt: 700,
        isUnlocked: false,
    },
];

export function getThemesByCategory(category: string): Theme[] {
    return THEMES.filter((t) => t.category === category);
}

export function getUnlockedThemes(): Theme[] {
    return THEMES.filter((t) => t.isUnlocked);
}
