import { EVENT_REGISTRY, type EventMap } from './event-registry';

export const DomainEvents = {
    DEBATE_UPDATED: EVENT_REGISTRY.DEBATE_UPDATED.name,
    DEBATE_STARTED: EVENT_REGISTRY.DEBATE_STARTED.name,
    DEBATE_ARGUMENT: EVENT_REGISTRY.DEBATE_ARGUMENT.name,
    DEBATE_CONSENSUS: EVENT_REGISTRY.DEBATE_CONSENSUS.name,
    MEMORY_UPDATED: EVENT_REGISTRY.MEMORY_UPDATED.name,
    TOOLS_UPDATED: EVENT_REGISTRY.TOOLS_UPDATED.name,
    TOOL_EXECUTION_START: EVENT_REGISTRY.TOOL_EXECUTION_START.name,
    TOOL_EXECUTION_SUCCESS: EVENT_REGISTRY.TOOL_EXECUTION_SUCCESS.name,
    TOOL_EXECUTION_ERROR: EVENT_REGISTRY.TOOL_EXECUTION_ERROR.name,
    ROLES_UPDATED: EVENT_REGISTRY.ROLES_UPDATED.name,
    ROLE_ASSIGNED: EVENT_REGISTRY.ROLE_ASSIGNED.name,
    ROLE_UNASSIGNED: EVENT_REGISTRY.ROLE_UNASSIGNED.name,
    MCP_UPDATED: EVENT_REGISTRY.MCP_UPDATED.name,
    SETTINGS_UPDATED: EVENT_REGISTRY.SETTINGS_UPDATED.name,
    POLICY_VIOLATION: EVENT_REGISTRY.POLICY_VIOLATION.name,
    SKILLS_UPDATED: EVENT_REGISTRY.SKILLS_UPDATED.name,
    PRICING_UPDATED: EVENT_REGISTRY.PRICING_UPDATED.name,
    BUDGET_ALERT: EVENT_REGISTRY.BUDGET_ALERT.name,
    KEYSTATE_UPDATED: EVENT_REGISTRY.KEYSTATE_UPDATED.name,
    KEYSTATE_REMOVED: EVENT_REGISTRY.KEYSTATE_REMOVED.name,
    SNAPSHOT_CAPTURED: EVENT_REGISTRY.SNAPSHOT_CAPTURED.name,
    SNAPSHOT_RESTORED: EVENT_REGISTRY.SNAPSHOT_RESTORED.name,
    AGENT_CONFIG_UPDATED: EVENT_REGISTRY.AGENT_CONFIG_UPDATED.name,
    AGENT_LIFECYCLE_CHANGE: EVENT_REGISTRY.AGENT_LIFECYCLE_CHANGE.name,
    AGENT_HEALTH_CHANGE: EVENT_REGISTRY.AGENT_HEALTH_CHANGE.name,
    AGENT_RESTARTED: EVENT_REGISTRY.AGENT_RESTARTED.name,
    AGENT_RATE_LIMITED: EVENT_REGISTRY.AGENT_RATE_LIMITED.name,
    AGENT_BLACKBOARD_UPDATED: EVENT_REGISTRY.AGENT_BLACKBOARD_UPDATED.name,
    AGENT_HANDOFF_INITIATED: EVENT_REGISTRY.AGENT_HANDOFF_INITIATED.name,
    ROUTER_SIGNAL: EVENT_REGISTRY.ROUTER_SIGNAL.name,
    ADVISOR_SUGGESTION: EVENT_REGISTRY.ADVISOR_SUGGESTION.name,
    ADVISOR_SUGGESTION_EXECUTED: EVENT_REGISTRY.ADVISOR_SUGGESTION_EXECUTED.name,
    ADVISOR_SUGGESTION_DISMISSED: EVENT_REGISTRY.ADVISOR_SUGGESTION_DISMISSED.name,
    DIAGNOSTIC_COMPLETE: EVENT_REGISTRY.DIAGNOSTIC_COMPLETE.name,
    SYSTEM_TOPOLOGY_MOUNTED: EVENT_REGISTRY.SYSTEM_TOPOLOGY_MOUNTED.name,
    SYSTEM_NODE_SPAWN: EVENT_REGISTRY.SYSTEM_NODE_SPAWN.name,
    SYSTEM_NODE_REMOVED: EVENT_REGISTRY.SYSTEM_NODE_REMOVED.name,
    SETTINGS_LATENCY_THRESHOLD: EVENT_REGISTRY.SETTINGS_LATENCY_THRESHOLD.name,
    VIRTUAL_KEY_CREATED: EVENT_REGISTRY.VIRTUAL_KEY_CREATED.name,
    VIRTUAL_KEY_RESOLVED: EVENT_REGISTRY.VIRTUAL_KEY_RESOLVED.name,
    VIRTUAL_KEY_REVOKED: EVENT_REGISTRY.VIRTUAL_KEY_REVOKED.name,
    DEBATE_ENDED: EVENT_REGISTRY.DEBATE_ENDED.name,
    DEBATE_FACT_CHECKED: EVENT_REGISTRY.DEBATE_FACT_CHECKED.name,
    ELO_RATING_UPDATED: EVENT_REGISTRY.ELO_RATING_UPDATED.name,
    CACHE_INVALIDATED: EVENT_REGISTRY.CACHE_INVALIDATED.name,
    DEBATE_VERDICT_GENERATED: EVENT_REGISTRY.DEBATE_VERDICT_GENERATED.name,
    DEBATE_SESSION_CONFLICT: EVENT_REGISTRY.DEBATE_SESSION_CONFLICT.name,
    SESSION_DELETED: EVENT_REGISTRY.SESSION_DELETED.name,
    CHAT_BOOKMARK_ADDED: EVENT_REGISTRY.CHAT_BOOKMARK_ADDED.name,
    CHAT_BOOKMARK_REMOVED: EVENT_REGISTRY.CHAT_BOOKMARK_REMOVED.name,
    CHAT_BOOKMARK_CLEARED: EVENT_REGISTRY.CHAT_BOOKMARK_CLEARED.name,
    AGENT_JOURNAL_ADDED: EVENT_REGISTRY.AGENT_JOURNAL_ADDED.name,
    AGENT_JOURNAL_REMOVED: EVENT_REGISTRY.AGENT_JOURNAL_REMOVED.name,
    AGENT_JOURNAL_CLEARED: EVENT_REGISTRY.AGENT_JOURNAL_CLEARED.name,
    WHATIF_SIMULATION_COMPLETED: EVENT_REGISTRY.WHATIF_SIMULATION_COMPLETED.name,
    PRESSURE_MAP_UPDATED: EVENT_REGISTRY.PRESSURE_MAP_UPDATED.name,
    PRESSURE_ALERT_RAISED: EVENT_REGISTRY.PRESSURE_ALERT_RAISED.name,
    WEBHOOK_DELIVERY_FAILED: EVENT_REGISTRY.WEBHOOK_DELIVERY_FAILED.name,
    SECRETS_LOOKUP_FAILED: EVENT_REGISTRY.SECRETS_LOOKUP_FAILED.name,
    COMPROMISE_SIGNAL_REJECTED: EVENT_REGISTRY.COMPROMISE_SIGNAL_REJECTED.name,
    TOPOLOGY_EVALUATED: EVENT_REGISTRY.TOPOLOGY_EVALUATED.name,
    QUEUE_TASK_FAILED: EVENT_REGISTRY.QUEUE_TASK_FAILED.name,
    DEBATE_HUMAN_VOTE: EVENT_REGISTRY.DEBATE_HUMAN_VOTE.name,
    HYPOTHESES_UPDATED: EVENT_REGISTRY.HYPOTHESES_UPDATED.name,
    RESEARCH_SESSION_UPDATED: EVENT_REGISTRY.RESEARCH_SESSION_UPDATED.name,
    KEY_INTELLIGENCE_PIPELINE_ERROR: EVENT_REGISTRY.KEY_INTELLIGENCE_PIPELINE_ERROR.name,
} as const;

export type DomainEventMap = Pick<
    EventMap,
    | 'debate:updated'
    | 'debate:started'
    | 'debate:argument'
    | 'debate:consensus'
    | 'debate:ended'
    | 'debate:fact:checked'
    | 'debate:verdict:generated'
    | 'debate:session:conflict'
    | 'debate:human:vote'
    | 'memory:updated'
    | 'tools:updated'
    | 'tool:execution:start'
    | 'tool:execution:success'
    | 'tool:execution:error'
    | 'roles:updated'
    | 'role:assigned'
    | 'role:unassigned'
    | 'mcp:updated'
    | 'settings:updated'
    | 'settings:latency:threshold'
    | 'policy:violation'
    | 'skills:updated'
    | 'pricing:updated'
    | 'budget:alert'
    | 'keystate:updated'
    | 'keystate:removed'
    | 'snapshot:captured'
    | 'snapshot:restored'
    | 'agent:config:updated'
    | 'agent:lifecycle:change'
    | 'agent:health:change'
    | 'agent:restarted'
    | 'agent:rate:limited'
    | 'agent:blackboard:updated'
    | 'agent:handoff:initiated'
    | 'router:signal'
    | 'advisor:suggestion'
    | 'advisor:suggestion:executed'
    | 'advisor:suggestion:dismissed'
    | 'diagnostic:complete'
    | 'system:topology:mounted'
    | 'system:node:spawn'
    | 'system:node:removed'
    | 'virtual:key:created'
    | 'virtual:key:resolved'
    | 'virtual:key:revoked'
    | 'elo:rating:updated'
    | 'cache:invalidated'
    | 'session:deleted'
    | 'chat:bookmark:added'
    | 'chat:bookmark:removed'
    | 'chat:bookmark:cleared'
    | 'agent:journal:added'
    | 'agent:journal:removed'
    | 'agent:journal:cleared'
    | 'whatif:simulation:completed'
    | 'pressure:map:updated'
    | 'pressure:alert:raised'
    | 'webhook:delivery:failed'
    | 'secrets:lookup:failed'
    | 'compromise:signal:rejected'
    | 'topology:evaluated'
    | 'queue:task:failed'
    | 'hypotheses:updated'
    | 'research:session:updated'
    | 'key:intelligence:pipeline:error'
>;
