import { Icons } from './route-registry-icons';
import type { NavSection } from './types/routing';

export const CONTENT_SECTIONS: NavSection[] = [
    {
        id: 'section-knowledge',
        labelKey: 'nav.section_knowledge',
        items: [
            {
                id: 'patterns',
                labelKey: 'nav.patterns',
                icon: Icons.bookOpen,
                color: '#10b981',
            },
            {
                id: 'knowledge',
                labelKey: 'nav.knowledge',
                icon: Icons.brain,
                color: '#a855f7',
            },
            {
                id: 'docs',
                labelKey: 'nav.docs',
                icon: Icons.bookText,
                color: '#8b5cf6',
            },
            {
                id: 'decision-log',
                labelKey: 'nav.decision_log',
                icon: Icons.clipboardList,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'eval-datasets',
                labelKey: 'nav.eval_datasets',
                icon: Icons.barChart3,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'project-os',
                labelKey: 'nav.project_os_explorer',
                icon: Icons.search,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'hypothesis-gen',
                labelKey: 'nav.hypothesis_generator',
                icon: Icons.flaskConical,
                color: '#3b82f6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'lenses',
                labelKey: 'nav.lenses',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'crystals',
                labelKey: 'nav.crystals',
                icon: Icons.gem,
                color: '#10b981',
                lazy: true,
                experimental: true,
            },
            {
                id: 'junctions',
                labelKey: 'nav.junctions',
                icon: Icons.waypoints,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'synthesis',
                labelKey: 'nav.synthesis',
                icon: Icons.combine,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
            {
                id: 'knowledge-generator',
                labelKey: 'nav.knowledge_generator',
                icon: Icons.lightbulb,
                color: '#22c55e',
                lazy: true,
                experimental: true,
            },
            {
                id: 'forum',
                labelKey: 'nav.forum',
                icon: Icons.messagesSquare,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'builder',
                labelKey: 'nav.builder',
                icon: Icons.wrench,
                color: '#f97316',
                lazy: true,
                experimental: true,
            },
            {
                id: 'director',
                labelKey: 'nav.director',
                icon: Icons.director,
                color: '#06b6d4',
                lazy: true,
                experimental: true,
            },
            {
                id: 'room',
                labelKey: 'nav.room',
                icon: Icons.room,
                color: '#22d3ee',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-engine',
                labelKey: 'nav.research_engine',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'tutorials',
                labelKey: 'nav.tutorials',
                icon: Icons.sparkles,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'arch-review',
                labelKey: 'nav.architecture_review',
                icon: Icons.bookText,
                color: '#10b981',
                lazy: true,
                experimental: true,
            },
            {
                id: 'prompt-audit',
                labelKey: 'nav.prompt_strategy_audit',
                icon: Icons.terminal,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
            {
                id: 'routing-experiments',
                labelKey: 'nav.model_routing_experiments',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'gov-stress-test',
                labelKey: 'nav.governance_stress_test',
                icon: Icons.shield,
                color: '#ef4444',
                lazy: true,
                experimental: true,
            },
            {
                id: 'obs-gaps',
                labelKey: 'nav.observability_gaps_scanner',
                icon: Icons.crosshair,
                color: '#f97316',
                lazy: true,
                experimental: true,
            },
            {
                id: 'debate-system-research',
                labelKey: 'nav.debate_system_research',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-reports',
                labelKey: 'nav.research_reports',
                icon: Icons.bookOpen,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-advanced',
                labelKey: 'nav.research_advanced',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-gemini',
                labelKey: 'nav.research_gemini',
                icon: Icons.sparkles,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'template-sharing',
                labelKey: 'nav.template_sharing',
                icon: Icons.share2,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'experimental',
                labelKey: 'nav.experimental',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-integrations',
        labelKey: 'nav.section_integrations',
        items: [
            {
                id: 'skills',
                labelKey: 'nav.skills',
                icon: Icons.gitMerge,
                color: '#f59e0b',
            },
            {
                id: 'tools',
                labelKey: 'nav.tools',
                icon: Icons.wrench,
                color: '#f59e0b',
            },
            {
                id: 'editors',
                labelKey: 'nav.editors',
                icon: Icons.fileCode,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'cache',
                labelKey: 'nav.cache',
                icon: Icons.hardDrive,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'webhooks',
                labelKey: 'nav.webhooks',
                icon: Icons.webhook,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'rotations',
                labelKey: 'nav.rotations',
                icon: Icons.refreshCw,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'service-registry',
                labelKey: 'nav.service_registry',
                icon: Icons.box,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'topology-templates',
                labelKey: 'nav.topology_templates',
                icon: Icons.grid3X3,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'playground',
                labelKey: 'nav.playground',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'prompts',
                labelKey: 'nav.prompts',
                icon: Icons.fileText,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'prompt-versions',
                labelKey: 'nav.prompt_version_history',
                icon: Icons.history,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'batch',
                labelKey: 'nav.batch_processing',
                icon: Icons.listOrdered,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'workflows',
                labelKey: 'nav.workflows',
                icon: Icons.gitPullRequest,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'security',
                labelKey: 'nav.security_scan',
                icon: Icons.shield,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'ab-testing',
                labelKey: 'nav.ab_testing',
                icon: Icons.gitCompare,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'fine-tuning',
                labelKey: 'nav.fine_tuning',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'team-collaboration',
                labelKey: 'nav.team_collaboration',
                icon: Icons.users,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'community-hub',
                labelKey: 'nav.community_hub',
                icon: Icons.share2,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'google-studio',
                labelKey: 'nav.google_studio',
                icon: Icons.shield,
                color: '#4285F4',
                lazy: true,
            },
            {
                id: 'google-cache',
                labelKey: 'nav.google_cache',
                icon: Icons.container,
                color: '#4285F4',
                lazy: true,
            },
            {
                id: 'gemini-live',
                labelKey: 'nav.gemini_live',
                icon: Icons.mic,
                color: '#4285F4',
                lazy: true,
                experimental: true,
            },
            {
                id: 'meta-learning',
                labelKey: 'nav.meta_learning',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'quantum-inspiration',
                labelKey: 'nav.quantum_inspiration',
                icon: Icons.atom,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'model-distillation',
                labelKey: 'nav.model_distillation',
                icon: Icons.brain,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'deploy',
                labelKey: 'nav.deploy',
                icon: Icons.rocket,
                color: '#22c55e',
                lazy: true,
            },
            {
                id: 'voice-input',
                labelKey: 'nav.voice_input',
                icon: Icons.mic,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'plugin-sdk',
                labelKey: 'nav.plugin_sdk',
                icon: Icons.puzzle,
                color: '#a855f7',
                lazy: true,
            },
        ],
    },
    {
        id: 'section-settings',
        labelKey: 'nav.section_settings',
        items: [
            {
                id: 'settings',
                labelKey: 'nav.settings',
                icon: Icons.settings,
                color: '#64748b',
            },
            {
                id: 'policies',
                labelKey: 'nav.policies',
                icon: Icons.shield,
                color: '#10b981',
            },
            {
                id: 'policy-editor',
                labelKey: 'nav.policy_editor',
                icon: Icons.zap,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'audit',
                labelKey: 'nav.audit_log',
                icon: Icons.search,
                color: '#94a3b8',
            },
            {
                id: 'history',
                labelKey: 'nav.config_history',
                icon: Icons.history,
                color: '#f59e0b',
            },
            {
                id: 'export-import',
                labelKey: 'nav.export_import',
                icon: Icons.database,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'time-machine',
                labelKey: 'nav.time_machine',
                icon: Icons.clock,
                color: '#8b5cf6',
                lazy: true,
            },
        ],
    },
];
