import { Icons } from './route-registry-icons';
import type { NavSection } from './types/routing';

export const CORE_SECTIONS: NavSection[] = [
    {
        id: 'section-dashboard',
        labelKey: 'nav.section_dashboard',
        items: [
            {
                id: 'dashboard',
                labelKey: 'nav.overview',
                icon: Icons.dashboard,
                color: '#3b82f6',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'analytics',
                labelKey: 'nav.analytics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                level: 'L1',
            },
            {
                id: 'pricing',
                labelKey: 'nav.economics',
                icon: Icons.dollarSign,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'budget',
                labelKey: 'nav.budget',
                icon: Icons.trendingUp,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'cost-analytics',
                labelKey: 'nav.cost_analytics',
                icon: Icons.barChart3,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'cost-optimization',
                labelKey: 'nav.cost_optimization',
                icon: Icons.dollarSign,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'custom-metrics',
                labelKey: 'nav.custom_metrics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'budget-alerts',
                labelKey: 'nav.budget_alerts',
                icon: Icons.bell,
                color: '#f97316',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'key-usage-analytics',
                labelKey: 'nav.key_usage_analytics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'routing',
                labelKey: 'nav.routing_ai',
                icon: Icons.route,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'contribution-graph',
                labelKey: 'nav.contribution_graph',
                icon: Icons.gitCommit,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
        ],
    },
    {
        id: 'section-chat',
        labelKey: 'nav.section_chat',
        items: [
            {
                id: 'chat',
                labelKey: 'nav.chat',
                icon: Icons.chat,
                color: '#10b981',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'chat-sessions',
                labelKey: 'nav.chat_sessions',
                icon: Icons.folderTree,
                color: '#06b6d4',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'session-hub',
                labelKey: 'nav.session_hub',
                icon: Icons.sessionHub,
                color: '#8b5cf6',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'bookmarks',
                labelKey: 'nav.bookmarks',
                icon: Icons.bookmark,
                color: '#f59e0b',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'tasks',
                labelKey: 'nav.tasks',
                icon: Icons.checkSquare,
                color: '#f59e0b',
                level: 'L1',
            },
            {
                id: 'files',
                labelKey: 'nav.files',
                icon: Icons.folderOpen,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
        ],
    },
    {
        id: 'section-debates',
        labelKey: 'nav.section_debates',
        items: [
            {
                id: 'debate',
                labelKey: 'nav.debate_arena',
                icon: Icons.messageCircle,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'builder',
                labelKey: 'nav.builder',
                icon: Icons.box,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-live',
                labelKey: 'nav.debate_live',
                icon: Icons.radio,
                color: '#ef4444',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-workspace',
                labelKey: 'nav.debate_rooms',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-replay',
                labelKey: 'nav.debate_replay',
                icon: Icons.history,
                color: '#6b7280',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-tournament',
                labelKey: 'nav.tournament',
                icon: Icons.zap,
                color: '#f97316',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'audience',
                labelKey: 'nav.audience',
                icon: Icons.users,
                color: '#ec4899',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'argument-graph',
                labelKey: 'nav.argument_graph',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'strategy-builder',
                labelKey: 'nav.strategy_builder',
                icon: Icons.gitMerge,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-analysis',
                labelKey: 'nav.debate_analysis',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-history',
                labelKey: 'nav.debate_history',
                icon: Icons.history,
                color: '#6b7280',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debates-manager',
                labelKey: 'nav.debates_manager',
                icon: Icons.folderTree,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'topics',
                labelKey: 'nav.topics',
                icon: Icons.sparkles,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-templates',
                labelKey: 'nav.debate_templates',
                icon: Icons.fileText,
                color: '#06b6d4',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-quality',
                labelKey: 'nav.debate_quality',
                icon: Icons.slidersHorizontal,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'quality-impact',
                labelKey: 'nav.quality_impact',
                icon: Icons.barChart3,
                color: '#06b6d4',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'steelman',
                labelKey: 'nav.steelman',
                icon: Icons.shield,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'bayesian-judge',
                labelKey: 'nav.bayesian_judge',
                icon: Icons.barChart3,
                color: '#7c3aed',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'blind-eval',
                labelKey: 'nav.blind_eval',
                icon: Icons.eye,
                color: '#6366f1',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'credibility',
                labelKey: 'nav.credibility',
                icon: Icons.star,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'calibration',
                labelKey: 'nav.calibration',
                icon: Icons.slidersHorizontal,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'consistency',
                labelKey: 'nav.consistency',
                icon: Icons.checkSquare,
                color: '#a855f7',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'frame-tracker',
                labelKey: 'nav.frame_tracker',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'stance-drift',
                labelKey: 'nav.stance_drift',
                icon: Icons.activity,
                color: '#ef4444',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'insight-bus',
                labelKey: 'nav.insight_bus',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'entanglement',
                labelKey: 'nav.entanglement',
                icon: Icons.network,
                color: '#7c3aed',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'anchoring',
                labelKey: 'nav.anchoring',
                icon: Icons.box,
                color: '#f97316',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'meta-agent',
                labelKey: 'nav.meta_agent',
                icon: Icons.bot,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'outcome-forecaster',
                labelKey: 'nav.outcome_forecaster',
                icon: Icons.trendingUp,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'concept-blender',
                labelKey: 'nav.concept_blender',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'belief-mining',
                labelKey: 'nav.belief_mining',
                icon: Icons.search,
                color: '#6366f1',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'minimax-planner',
                labelKey: 'nav.minimax_planner',
                icon: Icons.gitMerge,
                color: '#f97316',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'expert-witness',
                labelKey: 'nav.expert_witness',
                icon: Icons.bookOpen,
                color: '#7c3aed',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'rhetoric',
                labelKey: 'nav.rhetoric',
                icon: Icons.messageCircle,
                color: '#ec4899',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'bias-profiler',
                labelKey: 'nav.bias_profiler',
                icon: Icons.crosshair,
                color: '#ef4444',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'incentive-detector',
                labelKey: 'nav.incentive_detector',
                icon: Icons.zap,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'stakeholder',
                labelKey: 'nav.stakeholder',
                icon: Icons.users,
                color: '#ec4899',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'scratchpad',
                labelKey: 'nav.scratchpad',
                icon: Icons.stickyNote,
                color: '#6366f1',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'persona-mixer',
                labelKey: 'nav.persona_mixer',
                icon: Icons.shuffle,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'bop-tracker',
                labelKey: 'nav.bop_tracker',
                icon: Icons.listOrdered,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'got-deliberation',
                labelKey: 'nav.got_deliberation',
                icon: Icons.gitCommit,
                color: '#a855f7',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'similarity',
                labelKey: 'nav.similarity',
                icon: Icons.gitCompare,
                color: '#7c3aed',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'drift-detector',
                labelKey: 'nav.drift_detector',
                icon: Icons.thermometer,
                color: '#ef4444',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'shadow-opponent',
                labelKey: 'nav.shadow_opponent',
                icon: Icons.fileCode,
                color: '#6366f1',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'adversarial-source',
                labelKey: 'nav.adversarial_source',
                icon: Icons.shield,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'vuln-targeting',
                labelKey: 'nav.vuln_targeting',
                icon: Icons.crosshair,
                color: '#ef4444',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'justification',
                labelKey: 'nav.justification',
                icon: Icons.clipboardList,
                color: '#a855f7',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'logical-form',
                labelKey: 'nav.logical_form',
                icon: Icons.terminal,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
        ],
    },
];
