import { Icons } from './route-registry-icons';
import type { NavSection } from './types/routing';

export const CORE_SECTIONS: NavSection[] = [
    {
        id: 'section-dashboard',
        labelKey: 'nav.section_dashboard',
        items: [
            {
                id: 'dashboard',
                labelKey: 'nav.overview',
                icon: Icons.dashboard,
                color: '#3b82f6',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'analytics',
                labelKey: 'nav.analytics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                level: 'L1',
            },
            {
                id: 'pricing',
                labelKey: 'nav.economics',
                icon: Icons.dollarSign,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'budget',
                labelKey: 'nav.budget',
                icon: Icons.trendingUp,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'cost-analytics',
                labelKey: 'nav.cost_analytics',
                icon: Icons.barChart3,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'cost-optimization',
                labelKey: 'nav.cost_optimization',
                icon: Icons.dollarSign,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'custom-metrics',
                labelKey: 'nav.custom_metrics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'budget-alerts',
                labelKey: 'nav.budget_alerts',
                icon: Icons.bell,
                color: '#f97316',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'key-usage-analytics',
                labelKey: 'nav.key_usage_analytics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'routing',
                labelKey: 'nav.routing_ai',
                icon: Icons.route,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'contribution-graph',
                labelKey: 'nav.contribution_graph',
                icon: Icons.gitCommit,
                color: '#10b981',
                lazy: true,
                level: 'L2',
            },
        ],
    },
    {
        id: 'section-chat',
        labelKey: 'nav.section_chat',
        items: [
            {
                id: 'chat',
                labelKey: 'nav.chat',
                icon: Icons.chat,
                color: '#10b981',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'chat-sessions',
                labelKey: 'nav.chat_sessions',
                icon: Icons.folderTree,
                color: '#06b6d4',
                lazy: true,
                level: 'L0',
            },
            {
                id: 'session-hub',
                labelKey: 'nav.session_hub',
                icon: Icons.sessionHub,
                color: '#8b5cf6',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'bookmarks',
                labelKey: 'nav.bookmarks',
                icon: Icons.bookmark,
                color: '#f59e0b',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'tasks',
                labelKey: 'nav.tasks',
                icon: Icons.checkSquare,
                color: '#f59e0b',
                level: 'L1',
            },
            {
                id: 'files',
                labelKey: 'nav.files',
                icon: Icons.folderOpen,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
        ],
    },
    {
        id: 'section-debates',
        labelKey: 'nav.section_debates',
        items: [
            {
                id: 'debate',
                labelKey: 'nav.debate_arena',
                icon: Icons.messageCircle,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'builder',
                labelKey: 'nav.builder',
                icon: Icons.box,
                color: '#f59e0b',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-live',
                labelKey: 'nav.debate_live',
                icon: Icons.radio,
                color: '#ef4444',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-workspace',
                labelKey: 'nav.debate_rooms',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-replay',
                labelKey: 'nav.debate_replay',
                icon: Icons.history,
                color: '#6b7280',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-tournament',
                labelKey: 'nav.tournament',
                icon: Icons.zap,
                color: '#f97316',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'audience',
                labelKey: 'nav.audience',
                icon: Icons.users,
                color: '#ec4899',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'argument-graph',
                labelKey: 'nav.argument_graph',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'strategy-builder',
                labelKey: 'nav.strategy_builder',
                icon: Icons.gitMerge,
                color: '#06b6d4',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'debate-analysis',
                labelKey: 'nav.debate_analysis',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-history',
                labelKey: 'nav.debate_history',
                icon: Icons.history,
                color: '#6b7280',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debates-manager',
                labelKey: 'nav.debates_manager',
                icon: Icons.folderTree,
                color: '#8b5cf6',
                lazy: true,
                level: 'L2',
            },
            {
                id: 'topics',
                labelKey: 'nav.topics',
                icon: Icons.sparkles,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-templates',
                labelKey: 'nav.debate_templates',
                icon: Icons.fileText,
                color: '#06b6d4',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'debate-quality',
                labelKey: 'nav.debate_quality',
                icon: Icons.slidersHorizontal,
                color: '#a855f7',
                lazy: true,
                level: 'L1',
            },
            {
                id: 'quality-impact',
                labelKey: 'nav.quality_impact',
                icon: Icons.barChart3,
                color: '#06b6d4',
                lazy: true,
                level: 'L1',
            },
        ],
    },
];
