import {
    LayoutDashboard,
    Settings,
    MessageSquare as MessageSquareIcon,
    FolderTree,
    Bookmark,
    CheckSquare,
    FolderOpen,
    Bot,
    Star,
    Radio,
    Zap,
    Users,
    BookOpen,
    MessageCircle,
    GitBranch,
    History,
    GitMerge,
    Brain,
    Box,
    Sparkles,
    BarChart3,
    DollarSign,
    Activity,
    TrendingUp,
    Key,
    Layers,
    StickyNote,
    Gauge,
    Share2,
    Server,
    Terminal,
    Database,
    Heart,
    Thermometer,
    Shuffle,
    Network,
    Crosshair,
    Eye,
    FileCode,
    GitCompare,
    BookText,
    Search as SearchIcon,
    FlaskConical,
    Shield,
    ClipboardList,
    Wrench,
    HardDrive,
    Webhook,
    Fish,
    RefreshCw,
    FileText,
    ListOrdered,
    GitPullRequest,
    Rocket,
    Bell,
    Grid3X3,
    SlidersHorizontal,
    Trophy,
    Mic,
    Puzzle,
    Store,
    Upload,
    Clock as ClockIcon,
    GitCommit as GitCommitIcon,
    Atom,
    Route as RouteIcon,
    Container as ContainerIcon,
    Gem,
    Waypoints,
    BrainCircuit,
    Lightbulb,
    MessagesSquare,
    Clapperboard,
    Hash,
} from 'lucide-react';

const s = 18;

export const Icons = {
    dashboard: <LayoutDashboard size={s} />,
    chat: <MessageSquareIcon size={s} />,
    sessionHub: <LayoutDashboard size={s} />,
    bookmark: <Bookmark size={s} />,
    checkSquare: <CheckSquare size={s} />,
    folderOpen: <FolderOpen size={s} />,
    bot: <Bot size={s} />,
    star: <Star size={s} />,
    radio: <Radio size={s} />,
    zap: <Zap size={s} />,
    users: <Users size={s} />,
    bookOpen: <BookOpen size={s} />,
    messageCircle: <MessageCircle size={s} />,
    gitBranch: <GitBranch size={s} />,
    history: <History size={s} />,
    gitMerge: <GitMerge size={s} />,
    brain: <Brain size={s} />,
    box: <Box size={s} />,
    sparkles: <Sparkles size={s} />,
    barChart3: <BarChart3 size={s} />,
    dollarSign: <DollarSign size={s} />,
    activity: <Activity size={s} />,
    trendingUp: <TrendingUp size={s} />,
    key: <Key size={s} />,
    layers: <Layers size={s} />,
    folderTree: <FolderTree size={s} />,
    stickyNote: <StickyNote size={s} />,
    gauge: <Gauge size={s} />,
    share2: <Share2 size={s} />,
    server: <Server size={s} />,
    terminal: <Terminal size={s} />,
    database: <Database size={s} />,
    heart: <Heart size={s} />,
    thermometer: <Thermometer size={s} />,
    shuffle: <Shuffle size={s} />,
    network: <Network size={s} />,
    crosshair: <Crosshair size={s} />,
    eye: <Eye size={s} />,
    fileCode: <FileCode size={s} />,
    gitCompare: <GitCompare size={s} />,
    bookText: <BookText size={s} />,
    search: <SearchIcon size={s} />,
    flaskConical: <FlaskConical size={s} />,
    shield: <Shield size={s} />,
    clipboardList: <ClipboardList size={s} />,
    wrench: <Wrench size={s} />,
    hardDrive: <HardDrive size={s} />,
    webhook: <Webhook size={s} />,
    fish: <Fish size={s} />,
    refreshCw: <RefreshCw size={s} />,
    fileText: <FileText size={s} />,
    listOrdered: <ListOrdered size={s} />,
    gitPullRequest: <GitPullRequest size={s} />,
    rocket: <Rocket size={s} />,
    bell: <Bell size={s} />,
    grid3X3: <Grid3X3 size={s} />,
    slidersHorizontal: <SlidersHorizontal size={s} />,
    trophy: <Trophy size={s} />,
    mic: <Mic size={s} />,
    puzzle: <Puzzle size={s} />,
    store: <Store size={s} />,
    upload: <Upload size={s} />,
    clock: <ClockIcon size={s} />,
    gitCommit: <GitCommitIcon size={s} />,
    atom: <Atom size={s} />,
    route: <RouteIcon size={s} />,
    container: <ContainerIcon size={s} />,
    gem: <Gem size={s} />,
    waypoints: <Waypoints size={s} />,
    combine: <BrainCircuit size={s} />,
    lightbulb: <Lightbulb size={s} />,
    messagesSquare: <MessagesSquare size={s} />,
    settings: <Settings size={s} />,
    director: <Clapperboard size={s} />,
    room: <Hash size={s} />,
} as const;
