export const SERVICE_PHASE: Record<string, string> = {
    runtime: 'core',
    database: 'core',
    dal: 'core',
    eventBus: 'core',
    securityService: 'core',
    BucketStorageAdapter: 'core',
    schedulerService: 'core',
    storageLayer: 'core',
    logger: 'core',
    container: 'core',

    eventBridge: 'phase0',
    projectionRegistry: 'phase0',
    routerProjection: 'phase0',

    settingsService: 'phase1',
    pricingService: 'phase1',
    keyStateStore: 'phase1',
    providerTracker: 'phase1',
    kernel: 'phase1',
    metricsService: 'phase1',
    providerAdapterRegistry: 'phase1',
    keyService: 'phase1',
    groupManagerService: 'phase1',
    sessionManagerService: 'phase1',
    executionGovernor: 'phase1',
    fingerprints: 'phase1',
    deadLetterQueue: 'phase1',

    sessionAffinityStore: 'phase2',
    chatBookmarksService: 'phase2',
    agentJournalService: 'phase2',
    systemStatusService: 'phase2',
    rotationService: 'phase2',
    policyService: 'phase2',
    toolService: 'phase2',
    memoryService: 'phase2',
    externalSecretsService: 'phase2',
    blackboardService: 'phase2',
    cognitiveService: 'phase2',

    qualityImpactCollector: 'phase3',
    experimentEngine: 'phase3',
    factCheckService: 'phase3',
    debateService: 'phase3',
    collaborativeService: 'phase3',
    debateApiService: 'phase3',
    debateKnowledgeSync: 'phase3',
    hypothesisService: 'phase3',
    researchRunService: 'phase3',
    architectureReviewService: 'phase3',
    promptAuditService: 'phase3',
    routingExperimentsService: 'phase3',
    debatePolicyEngine: 'phase3',
    entanglementEngine: 'phase3',
    anchoringService: 'phase3',
    argumentGraphService: 'phase3',
    vulnerabilityTargetingService: 'phase3',
    shadowOpponentService: 'phase3',
    adversarialSourceService: 'phase3',
    beliefMiningService: 'phase3',
    minimaxPlannerService: 'phase3',
    metaAgentController: 'phase3',
    steelmanService: 'phase3',
    boPTrackerService: 'phase3',
    consistencyService: 'phase3',
    credibilityScorer: 'phase3',
    similarityMonitor: 'phase3',
    driftDetector: 'phase3',
    insightBus: 'phase3',
    logicalFormExtractor: 'phase3',
    justificationEnforcer: 'phase3',
    biasProfiler: 'phase3',
    interruptQueue: 'phase3',
    stakeholderMapper: 'phase3',
    calibrationService: 'phase3',
    personaMixer: 'phase3',
    frameTracker: 'phase3',
    expertWitnessService: 'phase3',
    bayesianJudge: 'phase3',
    stanceDriftTracker: 'phase3',
    rhetoricalDeviceSelector: 'phase3',
    scratchpadService: 'phase3',
    blindEval: 'phase3',
    incentiveDetector: 'phase3',
    gotDeliberation: 'phase3',
    conceptBlender: 'phase3',
    outcomeForecaster: 'phase3',
    debateEmbeddingPipeline: 'phase3',
    debateRAGRetriever: 'phase3',
    debateMemoryExtractor: 'phase3',
    debateEvaluator: 'phase3',
    debateEngine: 'phase3',
    debateHumanService: 'phase3',
    strategyManager: 'phase3',
    debateModeManager: 'phase3',
    debateWorkspace: 'phase3',
    cognitiveIntelligenceService: 'phase3',
    whatIfService: 'phase3',
    pressureMapService: 'phase3',
    diagnosticService: 'phase3',

    agentService: 'phase4',
    templateService: 'phase4',
    agentVersionService: 'phase4',
    roleVersionService: 'phase4',
    agentHealthMonitor: 'phase4',
    taskHandoffService: 'phase4',
    traceService: 'phase4',
    orchestrator: 'phase4',
    roleService: 'phase4',
    govStressTestService: 'phase4',
    obsGapsService: 'phase4',
    skillService: 'phase4',
    mcpService: 'phase4',
    sandboxService: 'phase4',
    budgetService: 'phase4',
    routingPolicyService: 'phase4',

    raceExecutor: 'phase5',
    routerService: 'phase5',
    usageTracker: 'phase5',
    cacheService: 'phase5',
    configService: 'phase5',
    snapshotService: 'phase5',
    advisorService: 'phase5',
    adminService: 'phase5',
    timelineService: 'phase5',
    monitoringService: 'phase5',
    llmClientService: 'phase5',
    freeTierLimits: 'phase5',
    virtualKeyService: 'phase5',
    providerRuntimeService: 'phase5',

    chatService: 'phase6',
    workspaceService: 'phase6',
    probeService: 'phase6',
    autoDebateService: 'phase6',
    eventSourcingService: 'phase6',
    notificationWebhookService: 'phase6',
    compromiseWebhookService: 'phase6',
    consistencyChecker: 'phase6',
    consistencyHealingPipeline: 'phase6',
    topologyManager: 'phase6',
    workforceFederation: 'phase6',
    agentMarketplace: 'phase6',
    eloService: 'phase6',
    chatSummarizerService: 'phase6',
    agentWizardService: 'phase6',
    roleTestingSandboxService: 'phase6',
    personaService: 'phase6',
    bridgeKeeperService: 'phase6',
    reconnectionService: 'phase6',
    audienceService: 'phase6',
    tutorialService: 'phase6',
    teamCollaborationService: 'phase6',
    fineTuningService: 'phase6',
    distillationService: 'phase6',
    deployService: 'phase6',
    budgetAlertService: 'phase6',
    topologyTemplateService: 'phase6',
    keyUsageAnalyticsService: 'phase6',
    promptVersionService: 'phase6',
    providerMigrationService: 'phase6',
    healthSlaService: 'phase6',
    researchReportService: 'phase6',
    voiceInputService: 'phase6',
    agentProtocolService: 'phase6',
    federatedMemoryService: 'phase6',
    pluginSdkService: 'phase6',
    personaMarketplaceService: 'phase6',
    templateSharingService: 'phase6',
    memoryTransferService: 'phase6',
    aquariumTradingService: 'phase6',
    timeMachineService: 'phase6',
    contributionService: 'phase6',
    promptSecurityService: 'phase6',
    googleGenAIService: 'phase6',
    workflowService: 'phase6',
    sourceAdapterRegistry: 'phase6',
    promptLibraryService: 'phase6',
    batchProcessorService: 'phase6',
    agentAvatarService: 'phase6',
    metaLearningService: 'phase6',
    quantumInspirationService: 'phase6',
    smartRoutingService: 'phase6',
    nvidiaEnterpriseService: 'phase6',
    geminiCacheService: 'phase6',
    providerAchievementService: 'phase6',
    geminiLiveService: 'phase6',
    connectorService: 'phase6',

    memoryOrchestrator: 'phase7',
    evalDatasetService: 'phase7',
    customMetricsService: 'phase7',

    unifiedRoleRegistry: 'phase8',
    roleTeamService: 'phase8',

    researchEngine: 'phase9',
    geminiResearchService: 'phase9',

    ecosystemEngine: 'phase10',

    causalScopeManager: 'phase11',
    causalTimelineService: 'phase11',
    counterfactualEngine: 'phase11',
    counterfactualExplanationService: 'phase11',
    counterfactualNarrativeService: 'phase11',
    temporalReplayService: 'phase11',
    truthConsistencyMonitor: 'phase11',

    lensEngine: 'phase13',
    crystalVault: 'phase14',
    junctionEngine: 'phase15',
    synthesisEngine: 'phase16',
    knowledgeGenerator: 'phase17',
    forumService: 'phase18',
    builderAgent: 'phase19',
};

// All registered route IDs from PANEL_COMPONENTS
export const VALID_ROUTE_IDS: string[] = [
    'analytics',
    'pricing',
    'budget',
    'cost-analytics',
    'routing',
    'chat',
    'chat-sessions',
    'session-hub',
    'bookmarks',
    'tasks',
    'files',
    'debate',
    'builder',
    'debate-live',
    'debate-workspace',
    'debate-replay',
    'debate-tournament',
    'audience',
    'editors',
    'argument-graph',
    'strategy-builder',
    'debate-analysis',
    'debate-history',
    'debates-manager',
    'topics',
    'agents',
    'roles',
    'roles-consortia',
    'sre',
    'agent-journal',
    'mission',
    'live',
    'agent-marketplace',
    'agent-comparison',
    'agent-protocol',
    'persona-marketplace',
    'persona-picker',
    'keys',
    'pools',
    'groups',
    'key-notes',
    'provider-dashboard',
    'groq-speed',
    'smart-routing',
    'nvidia-enterprise',
    'provider-marketplace',
    'connectors',
    'mcp',
    'session-bindings',
    'guardians',
    'playground',
    'prompts',
    'prompt-versions',
    'batch',
    'workflows',
    'security',
    'ab-testing',
    'custom-metrics',
    'fine-tuning',
    'team-collaboration',
    'community-hub',
    'google-studio',
    'google-cache',
    'gemini-live',
    'meta-learning',
    'quantum-inspiration',
    'model-distillation',
    'deploy',
    'voice-input',
    'plugin-sdk',
    'topology-templates',
    'cost-optimization',
    'logs',
    'debugger',
    'router-trace',
    'memory',
    'memory-palace',
    'memory-export-import',
    'health',
    'system-health',
    'docs-health',
    'pressure',
    'runtime-pressure',
    'what-if',
    'dependency-map',
    'diagnostics',
    'state-inspector',
    'performance-profiler',
    'shadow',
    'causal-debugger',
    'counterfactual',
    'aquarium',
    'ecosystem',
    'health-sla',
    'leaderboard',
    'federated-memory',
    'aquarium-trading',
    'patterns',
    'knowledge',
    'docs',
    'decision-log',
    'project-os',
    'hypothesis-gen',
    'lenses',
    'crystals',
    'junctions',
    'synthesis',
    'knowledge-generator',
    'forum',
    'research-engine',
    'research-advanced',
    'research-gemini',
    'research-reports',
    'eval-datasets',
    'arch-review',
    'prompt-audit',
    'routing-experiments',
    'gov-stress-test',
    'obs-gaps',
    'debate-system-research',
    'tutorials',
    'template-sharing',
    'skills',
    'tools',
    'cache',
    'webhooks',
    'rotations',
    'service-registry',
    'settings',
    'policies',
    'policy-editor',
    'audit',
    'history',
    'export-import',
    'time-machine',
    'debate-templates',
    'debate-quality',
    'quality-impact',
    'budget-alerts',
    'key-usage-analytics',
    'contribution-graph',
    // Phase 3 debate sub-service panels were collapsed into a single
    // `experimental` hub (Q8 hygiene) — see ExperimentalPanel.
    // Core
    'experimental',
    'scheduler',
];

// Route ID → display path
export const ROUTE_PATH: Record<string, string> = {
    analytics: '/analytics',
    pricing: '/pricing',
    budget: '/budget',
    'cost-analytics': '/cost-analytics',
    routing: '/routing',
    chat: '/chat',
    'chat-sessions': '/chat-sessions',
    'session-hub': '/session-hub',
    bookmarks: '/bookmarks',
    tasks: '/tasks',
    files: '/files',
    debate: '/debate',
    builder: '/builder',
    'debate-live': '/debate-live',
    'debate-workspace': '/debate-workspace',
    'debate-replay': '/debate-replay',
    'debate-tournament': '/debate-tournament',
    audience: '/audience',
    editors: '/editors',
    'argument-graph': '/argument-graph',
    'strategy-builder': '/strategy-builder',
    'debate-analysis': '/debate-analysis',
    'debate-history': '/debate-history',
    'debates-manager': '/debates-manager',
    topics: '/topics',
    agents: '/agents',
    roles: '/roles',
    'roles-consortia': '/roles-consortia',
    sre: '/sre',
    'agent-journal': '/agent-journal',
    mission: '/mission',
    live: '/live',
    'agent-marketplace': '/agent-marketplace',
    'agent-comparison': '/agent-comparison',
    'agent-protocol': '/agent-protocol',
    'persona-marketplace': '/persona-marketplace',
    'persona-picker': '/persona-picker',
    keys: '/keys',
    pools: '/pools',
    groups: '/groups',
    'key-notes': '/key-notes',
    'provider-dashboard': '/provider-dashboard',
    'groq-speed': '/groq-speed',
    'smart-routing': '/smart-routing',
    'nvidia-enterprise': '/nvidia-enterprise',
    'provider-marketplace': '/provider-marketplace',
    connectors: '/connectors',
    mcp: '/mcp',
    'session-bindings': '/session-bindings',
    guardians: '/guardians',
    playground: '/playground',
    prompts: '/prompts',
    'prompt-versions': '/prompt-versions',
    batch: '/batch',
    workflows: '/workflows',
    security: '/security',
    'ab-testing': '/ab-testing',
    'custom-metrics': '/custom-metrics',
    'fine-tuning': '/fine-tuning',
    'team-collaboration': '/team-collaboration',
    'community-hub': '/community-hub',
    'google-studio': '/google-studio',
    'google-cache': '/google-cache',
    'gemini-live': '/gemini-live',
    'meta-learning': '/meta-learning',
    'quantum-inspiration': '/quantum-inspiration',
    'model-distillation': '/model-distillation',
    deploy: '/deploy',
    'voice-input': '/voice-input',
    'plugin-sdk': '/plugin-sdk',
    'topology-templates': '/topology-templates',
    'cost-optimization': '/cost-optimization',
    logs: '/logs',
    debugger: '/debugger',
    'router-trace': '/router-trace',
    memory: '/memory',
    'memory-palace': '/memory-palace',
    'memory-export-import': '/memory-export-import',
    health: '/health',
    'system-health': '/system-health',
    'docs-health': '/docs-health',
    pressure: '/pressure',
    'runtime-pressure': '/runtime-pressure',
    'what-if': '/what-if',
    'dependency-map': '/dependency-map',
    diagnostics: '/diagnostics',
    'state-inspector': '/state-inspector',
    'performance-profiler': '/performance-profiler',
    shadow: '/shadow',
    'causal-debugger': '/causal-debugger',
    counterfactual: '/counterfactual',
    aquarium: '/aquarium',
    ecosystem: '/ecosystem',
    'health-sla': '/health-sla',
    leaderboard: '/leaderboard',
    'federated-memory': '/federated-memory',
    'aquarium-trading': '/aquarium-trading',
    patterns: '/patterns',
    knowledge: '/knowledge',
    docs: '/docs',
    'decision-log': '/decision-log',
    'project-os': '/project-os',
    'hypothesis-gen': '/hypothesis-gen',
    lenses: '/lenses',
    crystals: '/crystals',
    junctions: '/junctions',
    synthesis: '/synthesis',
    'knowledge-generator': '/knowledge-generator',
    forum: '/forum',
    'research-engine': '/research-engine',
    'research-advanced': '/research-advanced',
    'research-gemini': '/research-gemini',
    'research-reports': '/research-reports',
    'eval-datasets': '/eval-datasets',
    'arch-review': '/arch-review',
    'prompt-audit': '/prompt-audit',
    'routing-experiments': '/routing-experiments',
    'gov-stress-test': '/gov-stress-test',
    'obs-gaps': '/obs-gaps',
    'debate-system-research': '/debate-system-research',
    tutorials: '/tutorials',
    'template-sharing': '/template-sharing',
    skills: '/skills',
    tools: '/tools',
    cache: '/cache',
    webhooks: '/webhooks',
    rotations: '/rotations',
    'service-registry': '/service-registry',
    settings: '/settings',
    policies: '/policies',
    'policy-editor': '/policy-editor',
    audit: '/audit',
    history: '/history',
    'export-import': '/export-import',
    'time-machine': '/time-machine',
    'debate-templates': '/debate-templates',
    'debate-quality': '/debate-quality',
    'quality-impact': '/quality-impact',
    'budget-alerts': '/budget-alerts',
    'key-usage-analytics': '/key-usage-analytics',
    'contribution-graph': '/contribution-graph',
    // Phase 3 debate sub-service panels
    steelman: '/steelman',
    'bayesian-judge': '/bayesian-judge',
    'blind-eval': '/blind-eval',
    credibility: '/credibility',
    calibration: '/calibration',
    consistency: '/consistency',
    'frame-tracker': '/frame-tracker',
    'stance-drift': '/stance-drift',
    'insight-bus': '/insight-bus',
    entanglement: '/entanglement',
    anchoring: '/anchoring',
    'meta-agent': '/meta-agent',
    'outcome-forecaster': '/outcome-forecaster',
    'concept-blender': '/concept-blender',
    'belief-mining': '/belief-mining',
    'minimax-planner': '/minimax-planner',
    'expert-witness': '/expert-witness',
    rhetoric: '/rhetoric',
    'bias-profiler': '/bias-profiler',
    'incentive-detector': '/incentive-detector',
    stakeholder: '/stakeholder',
    scratchpad: '/scratchpad',
    'persona-mixer': '/persona-mixer',
    'bop-tracker': '/bop-tracker',
    'got-deliberation': '/got-deliberation',
    similarity: '/similarity',
    'drift-detector': '/drift-detector',
    'shadow-opponent': '/shadow-opponent',
    'adversarial-source': '/adversarial-source',
    'vuln-targeting': '/vuln-targeting',
    justification: '/justification',
    'logical-form': '/logical-form',
    scheduler: '/scheduler',
};

// Explicit service name → route ID mapping.
// Only services that NEED a UI panel are listed here.
// If a service is in this map but its route doesn't exist in VALID_ROUTE_IDS → MISSING.
export const SERVICE_ROUTE_MAP: Record<string, string> = {
    // Phase 1 — Foundation
    settingsService: 'settings',
    pricingService: 'pricing',
    keyService: 'keys',
    metricsService: 'analytics',
    sessionManagerService: 'chat-sessions',
    groupManagerService: 'groups',
    fingerprints: 'security',
    executionGovernor: 'state-inspector',
    deadLetterQueue: 'logs',
    keyIntelligencePipeline: 'key-notes',
    keyStateStore: 'keys',
    providerTracker: 'provider-dashboard',
    providerAdapterRegistry: 'provider-dashboard',

    // Phase 2 — Infrastructure
    chatBookmarksService: 'bookmarks',
    agentJournalService: 'agent-journal',
    systemStatusService: 'system-health',
    rotationService: 'rotations',
    policyService: 'policies',
    toolService: 'tools',
    memoryService: 'memory',
    cognitiveService: 'builder',
    externalSecretsService: 'security',
    blackboardService: 'tools',
    sessionAffinityStore: 'session-bindings',

    // Phase 3 — Debate
    debateService: 'debate',
    debateEngine: 'debate',
    debateHumanService: 'debate',
    debateApiService: 'debate',
    debateEvaluator: 'debate',
    debateModeManager: 'debate',
    debateKnowledgeSync: 'debate',
    debateWorkspace: 'debate-workspace',
    argumentGraphService: 'argument-graph',
    strategyManager: 'strategy-builder',
    pressureMapService: 'pressure',
    whatIfService: 'what-if',
    diagnosticService: 'diagnostics',
    hypothesisService: 'hypothesis-gen',
    lensEngine: 'lenses',
    crystalVault: 'crystals',
    junctionEngine: 'junctions',
    synthesisEngine: 'synthesis',
    knowledgeGenerator: 'knowledge-generator',
    forumService: 'forum',
    builderAgent: 'builder',
    architectureReviewService: 'arch-review',
    promptAuditService: 'prompt-audit',
    routingExperimentsService: 'routing-experiments',
    cognitiveIntelligenceService: 'builder',
    qualityImpactCollector: 'quality-impact',
    experimentEngine: 'debate-quality',
    factCheckService: 'debate',
    debateRAGRetriever: 'debate',
    debateMemoryExtractor: 'debate',
    collaborativeService: 'debate',
    audienceService: 'audience',
    researchRunService: 'research-engine',
    debatePolicyEngine: 'policies',
    steelmanService: 'steelman',
    bayesianJudge: 'bayesian-judge',
    blindEval: 'blind-eval',
    credibilityScorer: 'credibility',
    calibrationService: 'calibration',
    consistencyService: 'consistency',
    frameTracker: 'frame-tracker',
    stanceDriftTracker: 'stance-drift',
    insightBus: 'insight-bus',
    entanglementEngine: 'entanglement',
    anchoringService: 'anchoring',
    metaAgentController: 'meta-agent',
    outcomeForecaster: 'outcome-forecaster',
    conceptBlender: 'concept-blender',
    beliefMiningService: 'belief-mining',
    minimaxPlannerService: 'minimax-planner',
    expertWitnessService: 'expert-witness',
    rhetoricalDeviceSelector: 'rhetoric',
    biasProfiler: 'bias-profiler',
    incentiveDetector: 'incentive-detector',
    stakeholderMapper: 'stakeholder',
    scratchpadService: 'scratchpad',
    personaMixer: 'persona-mixer',
    boPTrackerService: 'bop-tracker',
    gotDeliberation: 'got-deliberation',
    similarityMonitor: 'similarity',
    driftDetector: 'drift-detector',
    shadowOpponentService: 'shadow-opponent',
    adversarialSourceService: 'adversarial-source',
    vulnerabilityTargetingService: 'vuln-targeting',
    justificationEnforcer: 'justification',
    logicalFormExtractor: 'logical-form',

    // Phase 4 — Agents
    agentService: 'agents',
    roleService: 'roles',
    agentHealthMonitor: 'health',
    taskHandoffService: 'tasks',
    traceService: 'debugger',
    orchestrator: 'agents',
    skillService: 'skills',
    mcpService: 'mcp',
    sandboxService: 'playground',
    budgetService: 'budget',
    govStressTestService: 'gov-stress-test',
    obsGapsService: 'obs-gaps',
    unifiedRoleRegistry: 'roles-consortia',
    templateService: 'agents',
    agentVersionService: 'agents',
    roleVersionService: 'roles',
    routingPolicyService: 'routing',

    // Phase 5 — Routing
    routerService: 'routing',
    usageTracker: 'key-usage-analytics',
    cacheService: 'cache',
    configService: 'settings',
    snapshotService: 'time-machine',
    adminService: 'chat',
    timelineService: 'history',
    monitoringService: 'system-health',
    raceExecutor: 'routing',
    advisorService: 'chat',
    virtualKeyService: 'keys',
    freeTierLimits: 'settings',
    providerRuntimeService: 'provider-dashboard',
    llmClientService: 'routing',

    // Phase 6 — High-level services
    chatService: 'chat',
    workspaceService: 'files',
    autoDebateService: 'debate',
    notificationWebhookService: 'webhooks',
    consistencyChecker: 'docs-health',
    agentMarketplace: 'agent-marketplace',
    chatSummarizerService: 'chat',
    agentWizardService: 'agents',
    personaService: 'persona-picker',
    tutorialService: 'tutorials',
    teamCollaborationService: 'team-collaboration',
    fineTuningService: 'fine-tuning',
    distillationService: 'model-distillation',
    deployService: 'deploy',
    budgetAlertService: 'budget-alerts',
    topologyTemplateService: 'topology-templates',
    keyUsageAnalyticsService: 'key-usage-analytics',
    promptVersionService: 'prompt-versions',
    healthSlaService: 'health-sla',
    researchReportService: 'research-reports',
    voiceInputService: 'voice-input',
    agentProtocolService: 'agent-protocol',
    federatedMemoryService: 'federated-memory',
    pluginSdkService: 'plugin-sdk',
    personaMarketplaceService: 'persona-marketplace',
    templateSharingService: 'template-sharing',
    memoryTransferService: 'memory-export-import',
    aquariumTradingService: 'aquarium-trading',
    timeMachineService: 'time-machine',
    promptSecurityService: 'security',
    googleGenAIService: 'google-studio',
    workflowService: 'workflows',
    batchProcessorService: 'batch',
    metaLearningService: 'meta-learning',
    quantumInspirationService: 'quantum-inspiration',
    smartRoutingService: 'smart-routing',
    nvidiaEnterpriseService: 'nvidia-enterprise',
    geminiCacheService: 'google-cache',
    geminiLiveService: 'gemini-live',
    connectorService: 'connectors',
    providerAchievementService: 'provider-dashboard',
    promptLibraryService: 'prompts',
    probeService: 'diagnostics',
    eventSourcingService: 'history',
    compromiseWebhookService: 'webhooks',
    consistencyHealingPipeline: 'docs-health',
    topologyManager: 'topology-templates',
    workforceFederation: 'agents',
    eloService: 'leaderboard',
    roleTestingSandboxService: 'playground',
    bridgeKeeperService: 'agent-protocol',
    reconnectionService: 'settings',
    providerMigrationService: 'provider-dashboard',
    contributionService: 'contribution-graph',
    sourceAdapterRegistry: 'connectors',
    agentAvatarService: 'agents',

    // Phase 7 — Memory
    memoryOrchestrator: 'memory',
    evalDatasetService: 'eval-datasets',
    customMetricsService: 'custom-metrics',

    // Phase 8 — Consortia
    roleTeamService: 'roles',

    // Phase 9 — Research
    researchEngine: 'research-engine',
    geminiResearchService: 'research-gemini',

    // Phase 10 — Ecosystem
    ecosystemEngine: 'ecosystem',

    // Phase 11 — Causal
    schedulerService: 'scheduler',
    causalScopeManager: 'causal-debugger',
    causalTimelineService: 'causal-debugger',
    counterfactualEngine: 'counterfactual',
    counterfactualExplanationService: 'counterfactual',
    counterfactualNarrativeService: 'counterfactual',
    temporalReplayService: 'causal-debugger',
    truthConsistencyMonitor: 'docs-health',
};
