import {
    BookOpen,
    Code,
    HeadphonesIcon,
    BarChart3,
    Sparkles,
    Shield,
    Layout,
    Cpu,
} from 'lucide-react';
import type { UiAgentTemplate } from './AgentsPanelContext';

export const AGENT_TEMPLATES: UiAgentTemplate[] = [
    {
        id: 'research',
        name: 'Research',
        description: 'Deep research agent with web search and summarization tools.',
        icon: <BookOpen size={20} />,
        color: 'var(--purple)',
        config: {
            roleName: 'Research Analyst',
            prompt: 'You are a thorough research analyst. Search the web, analyze documents, and provide comprehensive summaries with citations.',
            tools: ['web_search', 'read_document', 'summarize'],
            temperature: 0.3,
        },
    },
    {
        id: 'coding',
        name: 'Coding',
        description: 'Code generation and review specialist with sandbox execution.',
        icon: <Code size={20} />,
        color: 'var(--success)',
        config: {
            roleName: 'Software Engineer',
            prompt: 'You are an expert software engineer. Write clean, efficient code with tests. Review code for bugs and security issues.',
            tools: ['code_generation', 'code_review', 'sandbox_exec', 'debug'],
            temperature: 0.2,
        },
    },
    {
        id: 'support',
        name: 'Support',
        description: 'Customer-facing support agent with ticket management.',
        icon: <HeadphonesIcon size={20} />,
        color: 'var(--warning)',
        config: {
            roleName: 'Customer Support Agent',
            prompt: 'You are a helpful customer support agent. Be empathetic, resolve issues quickly, and escalate when needed.',
            tools: ['ticket_search', 'knowledge_base', 'send_email'],
            temperature: 0.5,
        },
    },
    {
        id: 'analyst',
        name: 'Data Analyst',
        description: 'Analyzes data, generates charts, and produces reports.',
        icon: <BarChart3 size={20} />,
        color: 'var(--accent)',
        config: {
            roleName: 'Data Analyst',
            prompt: 'You are a senior data analyst. Import datasets, generate visualizations, and produce actionable insights with statistical rigor.',
            tools: ['data_query', 'chart_gen', 'csv_import', 'report_gen'],
            temperature: 0.4,
        },
    },
    {
        id: 'creative',
        name: 'Creative Writer',
        description: 'Generates creative content like stories, poems, and marketing copy.',
        icon: <Sparkles size={20} />,
        color: '#ec4899',
        config: {
            roleName: 'Creative Director',
            prompt: 'You are a creative genius. Write engaging stories, poems, marketing copy, and content with unique voice and style.',
            tools: ['creative_writing', 'content_optimization', 'style_transfer'],
            temperature: 1.2,
        },
    },
    {
        id: 'security',
        name: 'Security Auditor',
        description: 'Analyzes security vulnerabilities and provides recommendations.',
        icon: <Shield size={20} />,
        color: '#06b6d4',
        config: {
            roleName: 'Security Engineer',
            prompt: 'You are a cybersecurity expert. Audit code and systems for security vulnerabilities, provide remediation steps.',
            tools: ['security_scan', 'vuln_analysis', 'pen_test'],
            temperature: 0.1,
        },
    },
    {
        id: 'teacher',
        name: 'Tutor',
        description: 'Educational agent that explains complex topics simply.',
        icon: <BookOpen size={20} />,
        color: '#a855f7',
        config: {
            roleName: 'Personal Tutor',
            prompt: 'You are a patient and knowledgeable tutor. Explain complex topics in simple terms, use examples, and answer questions.',
            tools: ['explain', 'quiz', 'summarize'],
            temperature: 0.6,
        },
    },
    {
        id: 'product',
        name: 'Product Manager',
        description: 'Defines product strategy, writes requirements, and prioritizes features.',
        icon: <Layout size={20} />,
        color: '#f97316',
        config: {
            roleName: 'Product Manager',
            prompt: 'You are a strategic product manager. Define product vision, write clear requirements, and prioritize features based on user needs and business goals.',
            tools: ['requirements', 'roadmap', 'user_research'],
            temperature: 0.7,
        },
    },
    {
        id: 'ux',
        name: 'UX Designer',
        description: 'Creates user-centered designs, wireframes, and usability tests.',
        icon: <Sparkles size={20} />,
        color: '#0ea5e9',
        config: {
            roleName: 'UX Designer',
            prompt: 'You are a user experience designer. Create intuitive, beautiful designs, wireframes, and conduct usability testing to improve user satisfaction.',
            tools: ['wireframe', 'usability_test', 'design_system'],
            temperature: 0.9,
        },
    },
    {
        id: 'devops',
        name: 'DevOps Engineer',
        description: 'Manages CI/CD pipelines, infrastructure, and deployment automation.',
        icon: <Cpu size={20} />,
        color: 'var(--success)',
        config: {
            roleName: 'DevOps Engineer',
            prompt: 'You are a DevOps engineer. Manage CI/CD pipelines, infrastructure as code, and automate deployments for reliability and scalability.',
            tools: ['ci_cd', 'infrastructure', 'monitoring'],
            temperature: 0.2,
        },
    },
];
