export interface QualityTechnique {
    id: string;
    name: string;
    nameRu: string;
    description: string;
    descriptionRu: string;
    category: 'P0' | 'P1' | 'P2';
    defaultEnabled: boolean;
}

export const QUALITY_TECHNIQUES: QualityTechnique[] = [
    // ═══ P0 ═══
    {
        id: 'cross-examination',
        name: 'Cross-Examination',
        nameRu: 'Перекрёстный допрос',
        description: 'Directly question opponent claims, demand missing evidence',
        descriptionRu: 'Прямой вопрос оппоненту, требование недостающих доказательств',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'delta-focusing',
        name: 'Delta-Focusing',
        nameRu: 'Фокус на расхождениях',
        description: 'Highlight only points of disagreement, skip consensus',
        descriptionRu: 'Выделяй только точки разногласий, пропускай консенсус',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'shadow-opponent',
        name: 'Shadow Opponent',
        nameRu: 'Теневой оппонент',
        description: 'Anticipate and pre-rebut unspoken counter-arguments',
        descriptionRu: 'Предвосхищай и опровергай невысказанные контраргументы',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'adversarial-source',
        name: 'Adversarial Source',
        nameRu: 'Проверка источников',
        description: 'Verify factual claims against source URLs, flag fabrications',
        descriptionRu: 'Проверяй фактические утверждения по URL',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'vulnerability-targeting',
        name: 'Vulnerability Targeting',
        nameRu: 'Атака уязвимостей',
        description: 'Identify and attack weakest claims in opponent argument graph',
        descriptionRu: 'Находи и атакуй слабейшие утверждения оппонента',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'agreement-anchoring',
        name: 'Agreement Anchoring',
        nameRu: 'Якорение согласия',
        description: 'Start from shared premises, then reveal logical inconsistencies',
        descriptionRu: 'Начинай с общих посылок, затем вскрывай противоречия',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'belief-mining',
        name: 'Belief Mining',
        nameRu: 'Добыча убеждений',
        description: 'Detect contradictions between stated positions and earlier claims',
        descriptionRu: 'Находи противоречия между текущей позицией и прошлыми заявлениями',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'graph-minimax',
        name: 'Graph Minimax',
        nameRu: 'Графовый минимакс',
        description: 'Plan argument moves several steps ahead using argument graph',
        descriptionRu: 'Планируй аргументы на несколько шагов вперёд',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'meta-agent',
        name: 'Meta-Agent',
        nameRu: 'Мета-агент',
        description: 'Tactical directives: when to attack, defend, pivot, or concede',
        descriptionRu: 'Тактические директивы: когда атаковать, защищаться, отступать',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'steelman',
        name: 'Steelman',
        nameRu: 'Стальной аргумент',
        description: 'Strengthen opponent position before refuting — steelman fallacies',
        descriptionRu: 'Усиль позицию оппонента перед опровержением',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'burden-of-proof',
        name: 'Burden of Proof',
        nameRu: 'Бремя доказательства',
        description: 'Track which claims remain unsupported; demand evidence',
        descriptionRu: 'Отслеживай неподтверждённые утверждения',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'entanglement',
        name: 'Entanglement',
        nameRu: 'Запутывание',
        description: 'Force opponent to defend two incompatible positions simultaneously',
        descriptionRu: 'Заставь оппонента защищать две несовместимые позиции',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'consistency-check',
        name: 'Consistency Check',
        nameRu: 'Проверка согласованности',
        description: 'Detect self-contradictions across rounds',
        descriptionRu: 'Находи самопротиворечия между раундами',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'credibility-scoring',
        name: 'Credibility Scoring',
        nameRu: 'Оценка достоверности',
        description: 'Track source reliability of each participant',
        descriptionRu: 'Отслеживай надёжность источников каждого участника',
        category: 'P0',
        defaultEnabled: true,
    },
    {
        id: 'causal-graph',
        name: 'Causal Loop Mapping',
        nameRu: 'Карта причинно-следственных связей',
        description: 'Force systems thinking: detect feedback loops and second-order effects',
        descriptionRu: 'Принуждай к системному мышлению: обнаруживай петли обратной связи',
        category: 'P0',
        defaultEnabled: true,
    },

    // ═══ P1 ═══
    {
        id: 'pre-publish-critic',
        name: 'Pre-Publish Critic',
        nameRu: 'Критик перед публикацией',
        description: 'Internal critic evaluates argument before release',
        descriptionRu: 'Внутренний критик оценивает аргумент перед публикацией',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'fact-checking',
        name: 'Fact-Checking',
        nameRu: 'Факт-чекинг',
        description: 'Verify factual claims in real-time against knowledge base',
        descriptionRu: 'Проверяй факты в реальном времени',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'epistemic-calibration',
        name: 'Epistemic Calibration',
        nameRu: 'Эпистемическая калибровка',
        description: 'Enforce confidence calibration: penalize over/under-confidence',
        descriptionRu: 'Штрафуй за излишнюю/недостаточную уверенность',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'socratic-pivot',
        name: 'Socratic Pivot',
        nameRu: 'Сократический разворот',
        description: 'Switch from arguing to questioning when opponent is inconsistent',
        descriptionRu: 'Переключайся с аргументации на вопросы при противоречиях',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'concession-engine',
        name: 'Concession Engine',
        nameRu: 'Механизм уступок',
        description: 'Monitor concession opportunities based on argument strength shift',
        descriptionRu: 'Отслеживай моменты для уступок',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'bayesian-judges',
        name: 'Bayesian Judges',
        nameRu: 'Байесовские судьи',
        description:
            'Probabilistic evaluation: update belief in each position after every argument',
        descriptionRu: 'Вероятностная оценка после каждого аргумента',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'humility-scoring',
        name: 'Humility Scoring',
        nameRu: 'Оценка скромности',
        description: 'Reward acknowledging uncertainty and limitations',
        descriptionRu: 'Поощряй признание неопределённости',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'stance-drift',
        name: 'Stance Drift',
        nameRu: 'Дрейф позиции',
        description: 'Detect when agent silently changes position across rounds',
        descriptionRu: 'Замечай тихую смену позиции между раундами',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'persona-mixer',
        name: 'Persona Mixer',
        nameRu: 'Смешение персон',
        description: 'Blend multiple persona archetypes for richer argumentation',
        descriptionRu: 'Смешивай архетипы для богатой аргументации',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'dpo-sampler',
        name: 'DPO Sampler',
        nameRu: 'DPO-сэмплер',
        description: 'Sample argument styles from high-win-rate past debates',
        descriptionRu: 'Сэмплируй стили из успешных прошлых дебатов',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'critic',
        name: 'Self-Critic',
        nameRu: 'Самокритика',
        description: 'Pre-validate own argument before submission',
        descriptionRu: 'Проверяй свой аргумент перед отправкой',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'pivot',
        name: 'Pivot Strategy',
        nameRu: 'Смена стратегии',
        description: 'Change argument direction when current approach is failing',
        descriptionRu: 'Меняй направление при неудаче',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'concession',
        name: 'Strategic Concession',
        nameRu: 'Стратегическая уступка',
        description: 'Concede minor points to gain credibility on major ones',
        descriptionRu: 'Уступай в малом ради доверия в главном',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'counterfactual',
        name: 'Counterfactual Analysis',
        nameRu: 'Контрфактический анализ',
        description: 'Explore "what if" scenarios to test opponent logic',
        descriptionRu: 'Исследуй сценарии "что если"',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'synthesis',
        name: 'Synthesis Engine',
        nameRu: 'Синтез',
        description: 'Combine best arguments from both sides into coherent whole',
        descriptionRu: 'Объединяй лучшие аргументы обеих сторон',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'triangulation',
        name: 'Triangulation',
        nameRu: 'Триангуляция',
        description: 'Cross-reference claims against multiple independent sources',
        descriptionRu: 'Сверяй утверждения с несколькими источниками',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'empathy',
        name: 'Empathy Mirroring',
        nameRu: 'Эмпатическое зеркало',
        description: 'Acknowledge opponent perspective before refuting',
        descriptionRu: 'Признай точку зрения оппонента перед опровержением',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'heat',
        name: 'Heat Detection',
        nameRu: 'Детектор накала',
        description: 'Detect emotional escalation, adjust tone accordingly',
        descriptionRu: 'Определяй эмоциональный накал и корректируй тон',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'sentinel',
        name: 'Argument Sentinel',
        nameRu: 'Страж аргументов',
        description: 'Monitor for abandoned claims and re-introduce them',
        descriptionRu: 'Отслеживай забытые утверждения',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'redundancy',
        name: 'Redundancy Detector',
        nameRu: 'Детектор повторов',
        description: 'Penalize repeating same evidence or reasoning',
        descriptionRu: 'Штрафуй за повтор одних и тех же доводов',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'insight-bus',
        name: 'Insight Bus',
        nameRu: 'Шина инсайтов',
        description: 'Broadcast cross-argument patterns to all agents',
        descriptionRu: 'Распространяй паттерны между агентами',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'replay',
        name: 'Replay Selector',
        nameRu: 'Выбор повторений',
        description: 'Re-engage with strongest unresolved points from earlier rounds',
        descriptionRu: 'Возвращайся к сильнейшим неразрешённым точкам',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'enthymeme',
        name: 'Enthymeme Attack',
        nameRu: 'Атака энтимем',
        description: 'Target hidden premises in opponent arguments',
        descriptionRu: 'Атакуй скрытые посылки оппонента',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'multi-hop',
        name: 'Multi-Hop Reasoning',
        nameRu: 'Многошаговое рассуждение',
        description: 'Require multi-step justification for complex claims',
        descriptionRu: 'Требуй многошагового обоснования',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'bias-exploit',
        name: 'Bias Exploitation',
        nameRu: 'Эксплуатация искажений',
        description: 'Identify and exploit opponent cognitive biases',
        descriptionRu: 'Определяй и используй когнитивные искажения',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'interrupt',
        name: 'Clarification Interrupt',
        nameRu: 'Запрос уточнения',
        description: 'Send targeted clarification requests to ambiguous claims',
        descriptionRu: 'Запрашивай уточнения по неясным утверждениям',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'stakeholder',
        name: 'Stakeholder Mapper',
        nameRu: 'Карта стейкхолдеров',
        description: 'Map which groups are affected by each position',
        descriptionRu: 'Покажи, какие группы затрагивает каждая позиция',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'frame',
        name: 'Frame Tracker',
        nameRu: 'Отслеживание фреймов',
        description: 'Track how each side frames the issue, reframe strategically',
        descriptionRu: 'Отслеживай и меняй фрейминг',
        category: 'P1',
        defaultEnabled: true,
    },
    {
        id: 'expert-witness',
        name: 'Expert Witness',
        nameRu: 'Эксперт-свидетель',
        description: 'Cite relevant domain experts and their credibility scores',
        descriptionRu: 'Цитируй экспертов и их оценки',
        category: 'P1',
        defaultEnabled: true,
    },

    // ═══ P2 ═══
    {
        id: 'rhetorical-device',
        name: 'Rhetorical Device',
        nameRu: 'Риторические приёмы',
        description: 'Inject rhetorical devices (anaphora, tricolon, chiasmus)',
        descriptionRu: 'Используй риторические приёмы',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'scratchpad',
        name: 'Hidden Scratchpad',
        nameRu: 'Скрытый черновик',
        description: 'Internal deliberation before public response',
        descriptionRu: 'Внутреннее обдумывание перед ответом',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'narrative-arc',
        name: 'Narrative Arc',
        nameRu: 'Нарративная дуга',
        description: 'Structure arguments as story arcs (hero journey, mystery, etc.)',
        descriptionRu: 'Структурируй аргументы как истории',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'abstraction-ladder',
        name: 'Abstraction Ladder',
        nameRu: 'Лестница абстракции',
        description: 'Switch between concrete evidence and abstract principles',
        descriptionRu: 'Переключайся между конкретикой и абстракцией',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'role-reversal',
        name: 'Role-Reversal',
        nameRu: 'Смена ролей',
        description: 'Occasionally argue from opponent perspective',
        descriptionRu: 'Иногда аргументируй с позиции оппонента',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'fog-of-war',
        name: 'Fog of War',
        nameRu: 'Туман войны',
        description: 'Limit information available to each agent',
        descriptionRu: 'Ограничивай информацию для каждого агента',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'evidence-revelation',
        name: 'Evidence Revelation',
        nameRu: 'Раскрытие доказательств',
        description: 'Stage evidence release by round',
        descriptionRu: 'Поэтапное раскрытие доказательств',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'humor',
        name: 'Humor Injection',
        nameRu: 'Юмор',
        description: 'Inject wit, irony, or analogy where appropriate',
        descriptionRu: 'Используй остроумие и аналогии',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'status-dynamics',
        name: 'Status Dynamics',
        nameRu: 'Статусная динамика',
        description: 'Assign social status levels that affect persuasiveness',
        descriptionRu: 'Назначай социальный статус',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'style-matching',
        name: 'Style Matching',
        nameRu: 'Подстройка стиля',
        description: 'Mirror opponent communication style',
        descriptionRu: 'Подстраивайся под стиль оппонента',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'dynamic-persona',
        name: 'Dynamic Persona',
        nameRu: 'Динамическая персона',
        description: 'Topic-matched persona variant selection',
        descriptionRu: 'Выбор персоны под тему',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'strategist',
        name: 'Strategist',
        nameRu: 'Стратег',
        description: 'Adaptive strategic directives (flank, fortify, probe, etc.)',
        descriptionRu: 'Адаптивные стратегические директивы',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'whisper-channels',
        name: 'Whisper Channels',
        nameRu: 'Шёпотные каналы',
        description: 'Private coordination signals between allied agents',
        descriptionRu: 'Приватная координация между союзниками',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'audience',
        name: 'Audience Sentiment',
        nameRu: 'Реакция аудитории',
        description: 'Simulate audience reactions to each argument',
        descriptionRu: 'Симулируй реакцию аудитории',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'alliance',
        name: 'Dynamic Alliance',
        nameRu: 'Динамический альянс',
        description: 'Form and leverage coalitions between agents',
        descriptionRu: 'Формируй коалиции между агентами',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'prediction-market',
        name: 'Prediction Market',
        nameRu: 'Рынок предсказаний',
        description: 'Agents predict debate trajectory, reputation on the line',
        descriptionRu: 'Агенты предсказывают ход дебатов',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'rtom',
        name: 'Theory of Mind',
        nameRu: 'Теория разума',
        description: 'Model other agents beliefs about the debate state',
        descriptionRu: 'Моделируй убеждения других агентов',
        category: 'P2',
        defaultEnabled: true,
    },
    {
        id: 'strategy-fingerprint',
        name: 'Strategy Fingerprinting',
        nameRu: 'Идентификация стратегий',
        description: 'Detect and counter opponent debate strategies',
        descriptionRu: 'Определяй и противодействуй стратегиям оппонента',
        category: 'P2',
        defaultEnabled: true,
    },
];

export const QUALITY_SETTINGS_STORAGE_KEY = 'debate-quality-settings';
